### ISSUE TITLE
Update docs for newcomers 

### ISSUE THREAD

**Issue by jonjamz** [xolvio/meteor-cucumber#101]
Today was my first time digging into Cucumber. Let me say thank you for your work on this package--once I sorted a few things out, I became confident that I could use it to great effect!

As a newcomer, several things caught me:

1. Working with Meteor methods proved to be frustrating. Return values from Meteor methods called from `this.mirror.call()` are not available in the usual async callback. An example showing how to get these would be very helpful, and perhaps a link to [bluebird](https://github.com/petkaantonov/bluebird).

2. The package is *actually using a custom fork of the DDP client from oortcloud*, although there is a link to the [original repository](https://github.com/oortcloud/node-ddp-client) in the docs. I was using that repository's code as a reference while figuring out the Meteor methods, and it just made things more confusing.

3. It took me a while to figure out where I could access the `Meteor` namespace in my tests. During my struggles with  `this.mirror.call()` and return values, I eventually found that I could call `this.browser.executeAsync` to get access to the browser's environment, which then passes data back to Cucumber's environment via `done`:

```javascript
// From browser, call server-side method and test response with `assert`.
this.browser.executeAsync(function (done) {
  Meteor.call('tester', function (err, res) {
    done(res); // Don't pass `err` into this as the first argument!
  });
}, function (err, res) {
  assert.equal(res.value, 'yes');
  callback();
});
```

If these items could make their way to the docs, I'm sure they would save others from dealing with the same initial hurdles.

**Comment by samhatoum** [comment]
Thank you so much for this feedback, this is exactly the type of feedback we need to get some good updates. I'll get your updates into the docs.

**Comment by samhatoum** [comment]
and I just realized who this is :)

**Comment by jonjamz** [comment]
Ha! Yes it's me :)

**Comment by samhatoum** [comment]
All these items have made it to the docs, I've also added two new aliases which I'm now using by default in the book and readmes. They are:

* `this.server` (in addition to `this.mirror` and `this.ddp` aliases)
* `this.client` (in addition to `this.browser` and `this.driver` aliases)

I'm hoping this will make it easier to understand :)

Thanks for your feedback, let's catch up soon
