### ISSUE TITLE
how to test for non-existence?

### ISSUE THREAD

**Issue by adamwong246** [xolvio/meteor-cucumber#104]
```
    this.Then(/^I should not see a link to create an offering$/, function (callback) {

      this.browser.
        waitForVisible("body").
        element("a[href='/new_offering']").
        should.eventually.not.exist.and.notify(callback);
    });
```

this returns `Unable to find element with css selector 'a[href='/new_offering']'`, which is exactly what I'm trying to assert. What's going on here?

**Comment by samhatoum** [comment]
waitForVisible is returning a false as it's timing out. The element you're looking for doesn't exists and therefore can't be visible. Try http://webdriver.io/api/state/isExisting.html

**Comment by adamwong246** [comment]
thanks for the help! Here's the correct implementation, I think
```
    this.Then(/^I should not see a link to create an offering$/, function (callback) {
      this.browser.
        waitForVisible("body").
        isExisting("a[href='/new_offering']").
        should.eventually.be.false.and.notify(callback);
    });
```

**Comment by samhatoum** [comment]
awesome
