### ISSUE TITLE
Testing an angular-meteor application

### ISSUE THREAD

**Issue by netanelgilad** [xolvio/meteor-cucumber#108]
Hey,
Awesome package and cucumber seems awesome! 
I'm working on the [angular-meteor](https://github.com/Urigo/angular-meteor) package and I'm currently looking for the best way to do e2e testing. Now angular provides [protractor](https://github.com/angular/protractor) for its e2e testing, which is a tool made specifically to test angular apps. But I want to make this package work with angular as well, and the main problem I have is waiting in tests for angular to be done with everything it does to render the view.
The solution I found for this is in this repository https://github.com/webdriverio/webdriverjs-angular, which wraps WebDriver in way that waits for angular in certain calls.
What would be the best way to make that work with this package?
I don't have any experience with WebDriver and such so I'm a bit clueless here, your help would be greatly appreciated. 

Thanks!

**Comment by Sanjo** [comment]
Just as a note (for me and Sam): This is basically a replacement of webdriverio with webdriverjs-angular.

**Comment by samhatoum** [comment]
Hey @netanelgilad 

A very quick test to do this would be:

1. Check out chimp
https://github.com/xolvio/chimp

2. Replace the standard [WebdriverIO](https://github.com/xolvio/chimp/blob/develop/lib/session-manager.js#L36) with webdriverjs-angular

3. add the `xolvio:cucumber` package

4. run with `CHIMP_PATH=</path/to/xolvio/chimp> meteor`

This will tell xolvio:cucumber to use a local chimp where you can depend on a custom webdriver. 

If you can play a little with that and see if it works for you, we can surely generalize a custom webdriver option in chimp.

One thing that I noticed is that webdriverjs-angular uses an older version of WebdriverIO so you might want to fork that and upgrade it also. 

happy to help

**Comment by netanelgilad** [comment]
Thanks @samhatoum, but I couldn't get it to work.
I tried following your steps and after it didn't work, I tried to isolate it and tried running without changing chimp. It still didn't work. Here is what I did:
1. check out chimp
2. npm install inside chimp (with no changes)
3. added the package
4. ran with your command (after double checking the path, and I tried both the path to the chimp dir and the path to the chimp file in the bin dir).

I get this error in the log file:
`[xolvio:cucumber] Bad response from chimp server. Try rerunning`

When I ran with VELOCITY_DEBUG I could see a message saying that chimp server in running on port 8866.

What have I missed?

**Comment by samhatoum** [comment]
There's a bug I'm working on where chimp starts after meteor-cucumber tries to call it. Are you seeing the messages in this order?

```
[xolvio:cucumber] Bad response from chimp server. Try rerunning
Chimp server in running on port 8866
```

To continue testing for your purposes, you can trigger a run either by changing a file under `/tests/cucumber` or by hitting `http://localhost:8866/run`

**Comment by samhatoum** [comment]
I can pair with you on this if you like

**Comment by netanelgilad** [comment]
I'd love that. Me and @Urigo would like to talk about a few other stuff as well. How can I contact you?

**Comment by Sanjo** [comment]
http://xolv.io/ or directly via e-mail sam@xolv.io and jonas@xolv.io ;-)

I just had a look at the current state of angular-meteor and I must say that I'm very impressed where you have taken the project to. I have about two years experience with Angular ;-)

**Comment by netanelgilad** [comment]
Awesome @Sanjo! We have started looking into testing right now (a bit late, we know ;)) and we would love your help.
Will contact soon.

About the issue itself, I got it to work with what @samhatoum suggested but I get other errors while running the scenarios:
<code>
RuntimeError: RuntimeError
           (UnknownError:13) An unknown server-side error occurred while processing the command.
           Problem: [ng:btstrpd] App Already Bootstrapped with this Element 'document'
      http://errors.angularjs.org/1.3.15/ng/btstrpd?p0=document
</code>
I think it may be related to my project and the way webdriverjs-angular works but I'm checking that..

**Comment by samhatoum** [comment]
I would start with a small hello world angular app (perhaps you're already doing that?)

**Comment by samhatoum** [comment]
let us know if you need anything guys

**Comment by borisfeldmann** [comment]
Hi everybody, 

thanks to all of you for providing such great packages as angular-meteor, xolvio:cucumber and sanjo:jasmine. I really like test-driven development.

But I have found a weird bug when combining angular-meteor with xolvio:cucumber. When I enable Angular's `$locationProvider.html5Mode` then cucumber's chimp reports an error "Bad response from chimp server." After removing the xolvio:cucumber package, setting `$locationProvider.html5Mode(false)`, and adding xolvio:cucumber package again, everything works fine again.

Do you have any clue what's happening here?

Thanks for your help!
Boris

**Comment by Sanjo** [comment]
@borisfeldmann Could you open a new issue please.
