### ISSUE TITLE
Keyword "And" not working

### ISSUE THREAD

**Issue by kjetilge** [xolvio/meteor-cucumber#112]
When I use: ```this.And(/../)``` in a step I get:
```TypeError: Object #<Object> has no method 'And'```

**Comment by samhatoum** [comment]
you should use `Given` `When` or `Then`. Use the correct phrase from the previous statement. So if it's `Given`.. `And`, use `Given`. If it's `Then`... `And`, use `Then`. This is how cucumber works :)
