### ISSUE TITLE
Functions in lib/collections/ are undefined in step_definitions/

### ISSUE THREAD

**Issue by j6k4m8** [xolvio/meteor-cucumber#115]
I have a function,

`lib/collections/items.js`
```javascript
Item = function(doc) {
    _.extend(this, doc);
};
```

but in `tests/cucumber/features/step_definitions/items.js`,
```javascript
this.When(/^I create a test item$/, function(callback) {
    var test = new Item({
        . . .
    });
    callback();
});
```
**...the above fails, `Item` is not defined.**

My guess is this has something to do with Meteor's file load-order, but I assumed everything was loaded on the mirror prior to running tests. (It's also very possible that I've misunderstood the structure of this framework, very new to cucumber.js!)

**Comment by samhatoum** [comment]
hey @j6k4m8 

the step def code doesn't run in a Meteor context. You can use `this.mirror.call()` to call a method over DDP to the mirror, and you can define the method in a fixture. Try the sample app to see how this works

**Comment by j6k4m8** [comment]
Aha — definitely an oversight on my part, thanks for setting me straight!

Should I close the issue or would you like me to modify the code for future readers?

**Comment by samhatoum** [comment]
Of you could post the code that would be great for new users. Thanks!
