### ISSUE TITLE
How can I use cucumber to fake logging in with oauth?

### ISSUE THREAD

**Issue by cjsauer** [xolvio/meteor-cucumber#125]
Just a quick question. I'm trying to do some acceptance testing on my app, but most routes/operations require being logged in (I'd also like to test that requirement). How does cucumber handle this? All I want to do is trick Meteor into thinking that I'm authenticated so that my tests will succeed. I'm using Facebook login with the `accounts-facebook` package. 

It seems Cucumber works fine with a phony username and password style login, but I can't for the life of me find any resources on how to stub out the whole login process and just use a phony Facebook user. In Jasmine or other integration testing frameworks, I could use a 'spy' or a 'mock', but this isn't possible (and is discouraged) in acceptance tests like cucumber...is it?

I'm also using the `alanning:roles` package to do permissions checking; that may further complicate things...

Thank you for any help you can offer.

**Comment by samhatoum** [comment]
https://github.com/xolvio/meteor-twitter-stub

https://github.com/xolvio/meteor-github-stub

Google and Facebook stubs are on the list of things for us to do, and you should be able to modify one of the above in the meantime.

Does that help?

**Comment by cjsauer** [comment]
I took a quick look at those packages. Do those both run on the mirror as
well? Is any service configuration necessary?

I can look in to writing up a Facebook stub in this fashion. I'll report
back here if I get something worth sharing.

**Comment by samhatoum** [comment]
The Twitter stub already does the service configuration and yes you'll need that

https://github.com/xolvio/meteor-twitter-stub/blob/master/twitter-stub-server.js#L8

The packages will run in both the mirror and the main app. Might make sense to make that optional

Let me know if you need help

**Comment by cjsauer** [comment]
Ah ok great. Side note: it looks like the Twitter stub clears all
configuration...do these packages play nice together?

**Comment by samhatoum** [comment]
oops! it shouldn't

**Comment by cjsauer** [comment]
Hey @samhatoum, what is the reason behind your twitter-stub naming a dependency on the iron-router package? Is it required to do stubbing with the http-intercepter?

**Comment by samhatoum** [comment]
It used an early version of http-interceptor. With the new version you can create a recording session and then play that back. It works as is, and I'll update it (along with all the other provider stubs) when I get around to it. So much work to do in the testing world still!

**Comment by cjsauer** [comment]
You can say that again. I'm having a bit of trouble with the http-interceptor; somehow the redirects to facebook.com are still making it through...

As I'm trying to stub out Facebook, I can't help but think this is a huge workaround for something that should be very simple. Does Meteor really not have a simple "pretend-to-log-this-user-in-function"? This method of stubbing out login services seems awfully fragile. Every new service will need a new stub, or worse, every time Facebook or Twitter updates their login process, it will break everybody's acceptance tests... 

Shouldn't there just be a hook in the Accounts package that, on the development server, I can just "pretend" to log someone in? As of now, testing in Meteor is a huge pain compared to other frameworks I have used.

**Comment by samhatoum** [comment]
I've looked into this before and its possible to create your own stub. Might be a little easier if you create a fixture that overrides the default methods. 

The oauth stub is not as fragile as you might think because its a standard. For example the google and github flows are identical. I will look at the Facebook flow soon I'm just slammed at the moment!

**Comment by cjsauer** [comment]
What do you think of this solution @samhatoum ? [https://github.com/cjsauer/accounts-phony](https://github.com/cjsauer/accounts-phony)

I'm basically bypassing the entire login system and just forcing a login. The tests are passing and I can successfully get fake users to login. You can even pass in your own user object so that it works with things like `aladeen:roles` and other packages. 

One question though: inside of a cucumber step definition, how would I call `Meteor.loginWithPhony(Phony.user)`? I've read [this section of your docs](https://github.com/xolvio/meteor-cucumber#webdriverio), but the function I want to call is not a server function; it is defined on the client. Is this possible inside of a cucumber step definition?

**Comment by cjsauer** [comment]
I think it's working now! I changed my step definition to the following: 

```javascript
this.Given(/^I am logged in$/, function (callback) {

  var login = function(done) {
    var fakeUser = {
      _id: "phony-user-id",
      username: "phony-user",
      emails: [ { address: "phony@example.com", verified: true } ],
      createdAt: Date.now(),
      profile: {
        name: "Phony User"
      },
      roles: {
        __global_roles__: ['user']
      }
    };
    Meteor.loginWithPhony(fakeUser, function(err,res) {
      done(res);
    });
  };

  this.browser.
    timeoutsAsyncScript(5000).
    executeAsync(login, function(err, res) {
      callback();
    });
});
```

This seems to have done it! I'd still like to know your thoughts on this approach. I think it's much simpler than stubbing out all the login methods.

**Comment by samhatoum** [comment]
Nice work! It's a simple solution and works. The time it may not work for you is when you want to test how your app should behave when a particular provider behaves in a given way. For example, you might wants to test how you handle a user declining to authorize access to google contacts. If you don't need that, then you're good.

Here's how you can use CI with CircleCI:
https://github.com/xolvio/Letterpress/blob/master/circle.yml

**Comment by cjsauer** [comment]
I see your point, but I feel those cases would only pop up when you're using a provider's SDK, for example the npm package for the facebook SDK would come back with a permissions error if the user revoked a permission. So those tests would be much better suited to an integration runner like Jasmine, where you're able to mock or stub the SDK directly and test for those edge cases that way. 

I'm still learning the difference honestly; where end-to-end testing ends and integration testing begins. Testing is most definitely an art form. 

Thanks for the help @samhatoum . I'll be watching velocity closely!

**Comment by samhatoum** [comment]
The best thing is that you are doing testing! I'm glad you like Velocity. The art is making something that works long term.

For the bonus question: The stub responses can be made to mimick the real service so the answer is yes. The new HTTPInterceptor supports a bunch of useful features for cases like this, such as record and playback for external services. I'm hoping to make it a more user-friendly package at some point. Currently is made for us (Xolv.io) only! 

Stay tuned :)
