### ISSUE TITLE
A "step" is interpreted as one test, I would expect a "scenario" to one test

### ISSUE THREAD

**Issue by bjarketrux** [xolvio/meteor-cucumber#127]
Consider this test:

Given I'm a new user,
When I navigate to "/",
Then the title should be "page title".

The output of running this "test" is 3 tests passed. I would have expected it to say 1 test passed as a don't see the setup as test in it self.

I can understand if the reason for this is to indicate if a setup step failed, but could that information not be added to the "message and callstack" property of a failed test?

**Comment by samhatoum** [comment]
I guess the reporter speaks the language of "tests" and you're right that the mapping is ambiguous. The right thing to do is to get the reporter to speak cucumber and use the proper hierarchy of features > scenarios > steps > details (screenshots / messages / callstacks). This way nothing lost in translation.

**Comment by bjarketrux** [comment]
Yes i guess you are right that velocity only stores one type of "test". But it's the mapping from cucumber to velocity tests, I would like to change:

I was thinking something like the "ancestors" array would store the Feature > Scenario titles. The "name" of the test would be: "Given I'm a new user, When I navigate to "/", Then the title should be \"page title\"."

Right now we have separate tests in mongo and no way (that I know of) to group them together. So if we have concurrent tests, then the steps would be mixed together. And also the "add a test says 3 passed" as I mentioned in the first comment.

Thanks for your time by the way.

**Comment by samhatoum** [comment]
Can you tell me your exact use case? I'm interested in what you're interested in getting out of mongo directly. 

Regarding the change, if you want to make the naming optional in open to a pull request. I'm reluctant to change what the current users are used to unless I have a complete reporting solution. Maybe we're working on something ;)

**Comment by samhatoum** [comment]
And you're welcome!

**Comment by bjarketrux** [comment]
I'm currently working on a valocity teamcity reporter. So I'm using the console reporter as an example. I just noticed that (what I call a) test is having 3 entries in the velocityTestReports collection.

But if you maybe working on something, then maybe I can wait ;)
It is not of importance, just wondering why and how.

**Comment by samhatoum** [comment]
We would love it if you could help us out and work on the xunit reporter for Velocity. 

This would then drop-in to all CI servers that can parse xunit. Velocity already has a structure similar to xunit. Here's a very early version of jasmine-unit (deprecated) that did the inverse xunit-> Velocity. 
https://github.com/xolvio/jasmine-unit/blob/master/main.js#L69

It shouldn't be too hard to reverse that.

Regarding cucumber > xunit. I found this:
https://github.com/stjohnjohnson/cucumber-junit
And he used a step == testcase as you can see here:
https://github.com/stjohnjohnson/cucumber-junit/blob/master/tests/mocks/output.xml

I'm not sure what the right answer is for xunit <> cucumber conversion is. But I know it's currently not 100% with Velocity :)

**Comment by bjarketrux** [comment]
I see your comment about @stjohnjohnson implementation, but I would dare say he is wrong ;)

I'm working on a TeamCity reporter related to the work I'm doing at my company. I think it should be fairly easy to take that reporter (when it's done) and retrofit it with xUnit xml output instead. TeamCity parses stdout for special ##teamcity tags, but xUnit could output an xml file instead.

But I'm not completely ready to publish the TeamCity reporter yet. Mainly because currently it does not output tests on the fly (probably won't matter if xUnit outputs a file) but also because I do not totally get the way to read the reports from mongodb.

I want to ask the Velocity team how to do it and/or if they would consider having a subscribe method on the framework instead of me poking around in their raw data.

P.S. TeamCity does have support for xUnit, but as far as I can se only through a MSRunner thingy, so I cannot directly use it for our Meteor setup.

**Comment by samhatoum** [comment]
I'm open to the challenge :) Like I said, I'm not fully decided

I'll answer the velocity question for you
