### ISSUE TITLE
[CircleCI] An unknown server-side error occurred while processing the command. Problem: POST /session//url

### ISSUE THREAD

**Issue by smoll** [xolvio/meteor-cucumber#128]
Apologies if this bug originates from velocity directly (I'm not entirely sure how to make that determination), but I would be happy to help debug further if anyone can provide some direction here.

I started creating a new app with almost entirely boilerplate cucumber code: https://github.com/smoll/linklog when I started seeing this issue. Here is the result of a CircleCI build: https://circleci.com/gh/smoll/linklog/2 and the corresponding chrome log: https://circle-artifacts.com/gh/smoll/linklog/2/artifacts/0/tmp/circle-artifacts.xfrjsmL/chrome/cucumber.log

I copied the circle.yml from Letterpress almost verbatim so I'm not sure what I could be doing wrong here. I also tried various solutions/workarounds e.g. https://github.com/meteor-velocity/velocity/issues/258#issuecomment-76586140, but I'm not sure how to kill the `meteor` process after starting it (I tried starting it as a background process, then issuing a curl call against localhost:3000, but I'm not sure how to kill the backgrounded process thereafter)

Seemingly, what appears to happen is:
1) Velocity creates the mirror on http://localhost:1234
2) Chrome attempts to visit the site running at the above address before the server is ready
3) Cucumber tests error out
4) Velocity creates another mirror on a different port, http://localhost:2345
5) Firefox tests run successfully because the server is ready much faster this time around (I think?)

If this helps, I don't see this issue on my Mac laptop at all. However on my dev machine I start my meteor app simply using `meteor`, so I wonder if this is related to running the tests via `meteor --test` on CircleCI.

**Comment by smoll** [comment]
So I did some more digging, generated a [brand new example project](https://github.com/smoll/circleci-cucumber-example), and this time it passed on the initial chrome run but failed on the secondary firefox run, https://circleci.com/gh/smoll/circleci-cucumber-example/2

with the exact same exception

```
    [31mWhen I navigate to "/"[0m                                  [2m[37m# features/sample.feature:21[0m
      RuntimeError: RuntimeError
           (UnknownError:13) An unknown server-side error occurred while processing the command.
           Problem: POST /session//url
      Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
      System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.14.28-031428-generic', java.version: '1.8.0_40'
      Driver info: driver.version: unknown[1;30m

           Callstack:
           -> url("http://localhost:33793/")
```

https://circle-artifacts.com/gh/smoll/circleci-cucumber-example/2/artifacts/0/tmp/circle-artifacts.6ntsmZz/firefox/cucumber.log

Any ideas?

**Comment by samhatoum** [comment]
try to set `VELOCITY_DEBUG=1` and retry the build. let's see what happens

**Comment by smoll** [comment]
I created a new branch with that flag set and all of a sudden the tests started passing again https://circleci.com/gh/smoll/circleci-cucumber-example/tree/debug

I just reran master (with no code changes) and it passes as well now https://circleci.com/gh/smoll/circleci-cucumber-example/tree/master

Not sure where to go from here. Should we go ahead and close this issue for now? Since I now have [a separate repo for this issue](https://github.com/smoll/circleci-cucumber-example), I can reopen it if/when the problem recurs.

**Comment by samhatoum** [comment]
Sure. It might be a race condition. All the extra logging can slow things down enough to make things pass sometimes!

Keep an eye on it and let us know

**Comment by rjakobsson** [comment]
I'm getting this error on my laptop. 
```
W20150807-11:20:05.979(2)? (STDERR) cucumber: 1 tests failed
W20150807-11:20:05.979(2)? (STDERR) RuntimeError
W20150807-11:20:05.979(2)? (STDERR) POST /session//url
W20150807-11:20:05.979(2)? (STDERR) Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
```
Cucumber.log: 
```
[chimp][cucumber] Closed with code 2
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
[chimp] Responding to /run request with:
{"name":"RuntimeError","message":"POST /session//url\nBuild info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'\nSystem info: host: 'Robins-MacBook-Air.local', ip: '10.103.3.21', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.6.0_65'\nDriver info: driver.version: unknown"}
[chimp] finished rerun
[xolvio:cucumber] Results from Chimp:
{ name: 'RuntimeError',
  message: 'POST /session//url\nBuild info: version: \'2.46.0\', revision: \'87c69e2\', time: \'2015-06-04 16:16:47\'\nSystem info: host: \'Robins-MacBook-Air.local\', ip: \'10.103.3.21\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.10.4\', java.version: \'1.6.0_65\'\nDriver info: driver.version: unknown' }
```

And i'm guessing that the weird thing here is: `Driver info: driver.version: unknown` ?
