### ISSUE TITLE
CI: Tests all pass but execution never ends (times out on Codeship)

### ISSUE THREAD

**Issue by ibussieres** [xolvio/meteor-cucumber#131]
I'm running `VELOCITY_CI=1 meteor --test` locally on latest version 0.8.9 of xolvio:cucumber. All my tests are marked as passed but the execution never stops. The same thing happens on Codeship. Am I doing something wrong ?

**Comment by samhatoum** [comment]
is there a missing callback somewhere perhaps?

**Comment by ibussieres** [comment]
Possibly. I can't see where... Also, my tests run correctly in the Velocity UI and when tailing the velocity log file. 

I found the problem though. It was a pending test. I opted for commenting it out for now, but that sort of beats the purpose of marking it as pending.

**Comment by samhatoum** [comment]
I'll test this case and see what I can do about it. Thanks for reporting

**Comment by orlade** [comment]
I'm getting this too on localhost (Windows) with `velocity:core@0.6.5` and `xolvio:cucumber@0.8.5`, trying to set up testing on Codeship as well.

```
$ meteor --test --release velocity:METEOR@1.1.0.2_3
=> Using velocity:METEOR@1.1.0.2_3 as requested (overriding Meteor 1.1.0.2)

I20150612-17:33:31.061(10)? [velocity] is in continuous integration mode
I20150612-17:33:44.404(10)? [velocity] cucumber is starting a mirror at http://localhost:57046/.
I20150612-17:33:44.503(10)? [velocity] You can see the mirror logs at: tail -f C:\dev\workspace\fabric\app\.meteor\local\log\cucumber.log
```

Then it just hangs while Cucumber runs. The Cucumber log output ends with `[chimp] Finished running async processes with errors`, but Velocity doesn't stop.

**Comment by samhatoum** [comment]
Thanks. FYI, I released 0.9.0 today so be sure to update :)

**Comment by samhatoum** [comment]
Can you try with 

`CUCUMBER_TAIL=1 VELOCITY_DEBUG=1 meteor --test --release velocity:METEOR@1.1.0.2_3`

**Comment by ibussieres** [comment]
FYI, my original problem seems resolved on 0.9.3. I will test it on Codeship later today.

**Comment by samhatoum** [comment]
Awesome, please close if it works out for you

**Comment by ibussieres** [comment]
Works now on 0.9.3 without any changes.

**Comment by samhatoum** [comment]
also for failing tests? I think I found a bug where failing tests hang

**Comment by ibussieres** [comment]
I can't confirm/deny that. My case was with pending...
