### ISSUE TITLE
going to root url but it re-renders to access-denied to login user

### ISSUE THREAD

**Issue by frankapimenta** [xolvio/meteor-cucumber#132]
I installed this gem first time.
So I have an application that when going to root url redirects to a access denied page if user is not logged in.

After adding "Add cucumber sample tests'"...

Then I have this problem:
Problem: Detected a page unload event; asynchronous script execution does not work across page loads

I'm a bit new into this. Would it be possible for anyone to help me on this?
thank you in advance!

**Comment by samhatoum** [comment]
how do you to the access denied page? Do you do an actual redirect?

**Comment by frankapimenta** [comment]
No. Actually is a render if no user is logged in.

var requireLogin = function() {
  if(!Meteor.user()) {
	  this.render('accessDenied');
	} else {
	  this.next();
	}
};

**Comment by frankapimenta** [comment]
im sorry for the confusion in here.
the other thing is solved. I put basic tests to run.

In cucumber step I cannot access this.client (it is undefined).

And:
  this.browser.getHTML('body') returns this -> expected '<body>\n\n\n\n\n\t\n\t\n\t\n\n\t\n\t</body>' to deeply equal '2s'

I actually have something in the body. which is the re-render access-denied page template.

@samhatoum  when will your book about testing ready? :)

**Comment by samhatoum** [comment]
Awesome, and soon :)
