### ISSUE TITLE
PhantomJS not working

### ISSUE THREAD

**Issue by tomitrescak** [xolvio/meteor-cucumber#133]
Out of the box PhantomJS renders only blank page (seen in screenshot).
Running `SELENIUM_BROWSER=firefox meteor` solves the issue, but it's somehow slower.

Do you know what can be the problem?

**Comment by samhatoum** [comment]
I can look into it :)

**Comment by rhyslbw** [comment]
@DominikGuzei and I also were experiencing problems with Phantom failing to find certain DOM elements with a project yesterday

**Comment by tomitrescak** [comment]
Sam, I already wrote several tests and all seems to work fine in Firefox. The PhantonJS still refuses to load a first page, I see only background image. It seems related to the router. I am using Flow Router. Do you think it can be it?

**Comment by samhatoum** [comment]
try to do:

```
this.browser.init().url('http://localhost:3000').pause(2000).capture('whatIsGoingOn');
```

See if that sheds any light

**Comment by tomitrescak** [comment]
I get this:

```bash
When I navigate to "/"                          # features/groupAdmin.feature:9
      ProtocolError: ProtocolError
           Problem: Cannot init a new session, please end your current session first

           Callstack:
           -> init()
```

**Comment by samhatoum** [comment]
try
```
this.browser.end().init().url('http://localhost:3000').pause(2000).capture('whatIsGoingOn');
```

**Comment by tomitrescak** [comment]
Now this:

```bash
RuntimeError: RuntimeError
           Problem: Variable Resource Not Found - {"headers":{"Accept":"application/json","Connection":"keep-alive","Content-Length":"284","Content-Type":"application/json; charset=UTF-8","User-Agent":"webdriverio/webdriverio/2.4.5","host":"localhost:61705"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"return (function () {\\n    return {\\n        screenWidth: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),\\n        screenHeight: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)\\n    };\\n}).apply(null, arguments);\",\"args\":[]}","url":"/session/7cc6a040-1161-11e5-8780-d3757281446c/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/session/7cc6a040-1161-11e5-8780-d3757281446c/","path":"/session/7cc6a040-1161-11e5-8780-d3757281446c/execute","relative":"/session/7cc6a040-1161-11e5-8780-d3757281446c/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session/7cc6a040-1161-11e5-8780-d3757281446c/execute","queryKey":{},"chunks":["session","7cc6a040-1161-11e5-8780-d3757281446c","execute"]}}

           Callstack:
           -> execute([Function])
           -> setViewportSize({"width":1280,"height":1024})
```

Tried pausing and unpausing and nothing happens.

**Comment by tomitrescak** [comment]
This is what I get as a screenshot from PhantomJS from mirror. Empty background. Like I said, seems like router does not work in there.

![0-step_failed_1434154748981](https://cloud.githubusercontent.com/assets/2682705/8142088/bf539432-11b5-11e5-92ee-53303b02071b.png)

**Comment by samhatoum** [comment]
interesting. I think the real issue is phantom + flow router then. I've previously had to shim phantom so support stuff
 
To find the error, I would try to use phantom by itself and use it to go to your application with full debugging on. See here for instructions
http://phantomjs.org/quick-start.html

Once you know the error, you may be able to do something about it I think

**Comment by tomitrescak** [comment]
Well, that was a good idea.
It is flow router's failure:

```
TypeError: 'undefined' is not a function (evaluating 'self._processTriggersExit.bind(self)')

  http://localhost:3000/packages/meteorhacks_flow-router.js?ee201122368210afe3ec0c1756d1e3627013e4de:1947
  http://localhost:3000/packages/meteorhacks_flow-router.js?ee201122368210afe3ec0c1756d1e3627013e4de:1476
  http://localhost:3000/packages/meteorhacks_flow-router.js?ee201122368210afe3ec0c1756d1e3627013e4de:2228
  http://localhost:3000/packages/meteorhacks_flow-router.js?ee201122368210afe3ec0c1756d1e3627013e4de:2239
  http://localhost:3000/packages/meteorhacks_flow-router.js?ee201122368210afe3ec0c1756d1e3627013e4de:2248
TypeError: 'undefined' is not an object (evaluating 'Package['meteorhacks:flow-router'].FlowRouter')
```

**Comment by samhatoum** [comment]
Could be due to URL support in phantom. I once did this:

https://github.com/xolvio/meteor-webdriver/tree/master/polyfills

See if including that file in your codebase helps

**Comment by samhatoum** [comment]
Here's how I applied polyfills

https://github.com/xolvio/meteor-webdriver/blob/master/server.js#L122

If this helps, I can reintroduce this into meteor-cucumber

**Comment by tomitrescak** [comment]
Sam, looks like PhantomJS 2.0 solves this issue with style, no extra work necessary. The question is now, how can I tell cucumber that it should use this new PhantomJS? ... and if it's gonna work ...

**Comment by tomitrescak** [comment]
OK, one step further ... I just replaced the binary in the phantomjs-bin nom package that comes with chip and got it working!!! The problem now is that it fails with "alerts". But I guess I'll point this one towards webdriverio people. Thanks for your help!

**Comment by samhatoum** [comment]
Oh great, looks like a updated phantom sorted it. Things to look for in the future: shimming phantomjs where it lacks.

Regarding phantom2.0, that doesn't have webdriver bindings (that I know of) yet so it's not possible to use it.

Whilst I love the speed of phantom, I've been working with chrome driver locally and on CI servers. Works a charm :)

**Comment by tomitrescak** [comment]
I've been using firefox. Will try chrome, was just lazy to set it up.

**Comment by rhyslbw** [comment]
Good detective work @tomitrescak
