### ISSUE TITLE
View syntax errors in tests

### ISSUE THREAD

**Issue by tomitrescak** [xolvio/meteor-cucumber#134]
Is it possible to view errors from test in the console?
I just spend an hour chasing the problem and found out that I had a syntax error in my test and cucumber was failing silently (don't mind the test, it makes no sense):

```javascript
// Steps definition file
    this.Given(/"([^"]*)" has logged in/, function(email, callback) {

      // 1. create a user
      var user = {
        email: email,
        password: '123456'
      };

      var login = function(done) {
        Meteor.loginWithPassword(userData.email, userData.password, function(err, res) { //!!! Here I was using userData and not user
          done();
        })
      };

      this.client
      .executeAsync(login, function (err, res) {
        //assert.equal(res.value, 'yes');
        callback();
      });
    });
```

**Comment by samhatoum** [comment]
are you tailing the `cucumber.log`?

**Comment by tomitrescak** [comment]
Yes I am. For some reason the syntax error is not appearing :/

**Comment by tomitrescak** [comment]
I guess this relates to this ... not even "console.log" is displayed here. 
Would be very useful.

**Comment by tomitrescak** [comment]
I correct my statement. Syntax errors are displayed in the console, but only those that are detected during compilation. Once a syntax error or null reference error happens during (e.g. async) execution, I am not able to see this. But I will close this issue.

**Comment by samhatoum** [comment]
Oh wait, of course! Those console logs happen in the browser, since you're executing async.

Could be a cool idea to capture console outputs from the browser back to the main process I guess as output.. hmmm!
