### ISSUE TITLE
Assertions in WebdriverIO callbacks

### ISSUE THREAD

**Issue by tomitrescak** [xolvio/meteor-cucumber#135]
Sam, I'm terribly sorry to spam your issues, but I cannot deal with a simple thing. I checked your book, the documentation but what is there does not work. Calling following will end with **assert is not defined** error

```javascript
this.client.elements('.item', function(error, result) {
  assert.equal(result.value.length, 1);
  callback();
});
```

How can I assert on elements in WebdriverIO callbacks?

**Comment by tomitrescak** [comment]
Would this be OK way?

```javascript
this.client.elements(className).then(
        function (result) {
          result.value.length.should.equal(1);
          callback();
        }
      )
```

**Comment by samhatoum** [comment]
have you tried:

`this.client.elements.should.eventually.have.length(1)` I've not tried this :)

**Comment by tomitrescak** [comment]
Sam, how do I get those asserts to work? Doing this does not work since assert does not exists.

var assert = chai.assert

**Comment by tomitrescak** [comment]
this one is closer to the solution:

`this.client.elements(className).should.eventually.have.property("value").length(1).and.notify(callback);`

but for some reason `value`, which is array is forgotten and only first element of array is taken.

**Comment by jwjames** [comment]
Just my 2 cents: In response to `var assert = chai.assert` not working, would the standard node.js `  var assert = require('assert');` work for you? I use it like:

```javascript
;
(function () {
  'use strict';

  var assert = require('assert');

  module.exports = function () {
```
In the beginning of step files and assertions work correctly.

**Comment by samhatoum** [comment]
Hey guys

You can use Chai's assert by doing:

`global.chai.assert'

chimp exposes the chai object on the global space. [See here](https://github.com/xolvio/chimp/blob/develop/lib/cucumberjs/world.js#L15)

**Comment by workflow** [comment]
@samhatoum Cool, however when I try to access it in a step definition, `global.chai` seems to be undefined:

```javascript
(function() {

    'use strict';

    var assert = global.chai.assert;
```

```
/tests/cucumber/features/step_definitions/contributing-content/commenting.js:5
    var assert = global.chai.assert;
                            ^
TypeError: Cannot read property 'assert' of undefined
```

**Comment by samhatoum** [comment]
you just needed to be inside `module.exports` I think. Thanks for reporting back
