### ISSUE TITLE
Adding global require() support files and variables for all step files

### ISSUE THREAD

**Issue by jwjames** [xolvio/meteor-cucumber#137]
With the absence of a world object, I'm having trouble finding in the docs how to add in multiple `require()` packages or global variables to run before all tests so that I don't have to write the same code snippet at the top of every step file. Is there a way to do this?

**Comment by samhatoum** [comment]
You can use the top secret undocumented hook like this:

```
global.UserDefinedBeforeFeatures = function (callback) {
    global.myThing = require('that-thing');
};
```

This will only get called once for your entire run.

I'm still trying to figure out the best way to allow custom worlds, it's tricky!

**Comment by workflow** [comment]
@samhatoum Is this still the best way to do it?

**Comment by samhatoum** [comment]
I'm about to release a new version of chimp that allows you to use a custom world object
