### ISSUE TITLE
Sample tests hang in the presence of reactjs:react package

### ISSUE THREAD

**Issue by colvint** [xolvio/meteor-cucumber#139]
Hey Sam -- thanks for your work in the meteor test space. Bought [your book](http://www.meteortesting.com/) and am looking forward to it's evolution. I have a number of passing `xolvio:cucumber` features. Just started a new feature which requires the use of the  `reactjs:react` package. I noticed that any feature containing a call to WebdriverIO's `url` method hangs. 

To ensure there wasn't some other conflating cause, I created a [test repo](https://github.com/colvint/react-cucumber-test) which also demonstrates the failure.

**Supporting info**
- [console.output](https://gist.github.com/colvint/718e1749ade685a44b56)
- [cucumber.log](https://gist.github.com/colvint/1296eb11edaf897e3900)
- [.meteor/versions](https://github.com/colvint/react-cucumber-test/blob/master/.meteor/versions)
- [.meteor/packages](https://github.com/colvint/react-cucumber-test/blob/master/.meteor/packages)

**Comment by samhatoum** [comment]
Interesting. can you try it with chrome?

`SELENIUM_BROWSER=chrome meteor`

I suspect Phantom does not support things in react. See this too:
https://github.com/xolvio/meteor-cucumber/issues/133

**Comment by colvint** [comment]
Wow! You replied before I even finished the bug -- thanks! Indeed features pass with `SELENIUM_BROWSER=chrome meteor`.

**Comment by samhatoum** [comment]
awesome! I think I might switch the default browser to be chrome since Phantom is not really able to test modern apps so well. 

If you want to get phantom working, you'll need to find the thing it's lacking and shim it

**Comment by colvint** [comment]
Chrome it is ;)
