### ISSUE TITLE
Running tags using "AND" logic

### ISSUE THREAD

**Issue by jwjames** [xolvio/meteor-cucumber#141]
Is there a way to run tests using "AND" logic, so test with Feature tag "A" can be further filtered by also adding their Scenario tag "C" without running all scenarios with tag "C"?
<b>Example:</b>
```javascript
@A 
Feature: a feature

@C 
Scenario: a scenario

//In a different feature file:

@D 
Feature: a feature

@C
Scenario: a scenario
```
I believe in the original cucumber one would run it like:
```cucumber --tags @A --tags @C    # Runs scenarios only with @A AND @C```

**Comment by samhatoum** [comment]
Interesting. Currently meteor-cucumber (which is a proxy to [chimp](https://github.com/xolvio/chimp)) only [passes one tag](https://github.com/xolvio/meteor-cucumber/blob/develop/src/mirror-server.js#L265).

However, you can pass in some raw commands to chimp using [CHIMP_OPTIONS](https://github.com/xolvio/meteor-cucumber/blob/develop/src/mirror-server.js#L251). I think if you do that, you can pass multiple tags, but also be mindful that meteor-cucumber will not pass any of [the other options](https://github.com/xolvio/meteor-cucumber/blob/develop/src/mirror-server.js#L259-L311). So if you need any of them, be sure to add them to CHIMP_OPTIONS.
