### ISSUE TITLE
Resetting browser state between runs

### ISSUE THREAD

**Issue by ndarilek** [xolvio/meteor-cucumber#145]
I have the following scenarios:

  @dev
  Scenario: Logging in
    Given I am a new user
    When I navigate to "/"
    And I submit valid credentials
    Then I should be logged in

  @dev
  Scenario: Logging in with invalid credentials
    Given I am a new user
    When I navigate to "/"
    And I submit invalid credentials
    Then I should be logged out

Unfortunately, the browser doesn't appear to reset between these scenarios. IOW, the first logs me in. When the second scenario navigates to /, the login form is not visible because the user appears to still be logged in. So the invalid credentials step fails because the elements of the login form aren't visible.

Is this expected behavior? If so, how do I reset browser state between scenarios? Is it not desirable to start every scenario as a blank slate so you can explicitly specify expectations and run the browser through the entire flow?

Thanks.

**Comment by ndarilek** [comment]
Ack, apologies for all the noise over these past few days. Was a silly oversight, failed to call my callback after my before hook. Doing that seems to have made everything work. Sorry, as someone new to all of this I don't know where your library begins and the underlying cucumber.js ends (I.e. wasn't sure if it was the source of the webdriver.io integration or if you were.) I now know. :)

Thanks.

**Comment by samhatoum** [comment]
The callback helps for sure, but you need to also be sure to logout yourself between steps. You can use the before hook to do that. 

Remember that you have an open webdriver session (just like a real browser) and a long running meteor app (the mirror). Any state you build you you'll need to clear. You should consider using [xolvio:cleaner](https://github.com/xolvio/cleaner)
