### ISSUE TITLE
Issue with hot code reload: clearing db on mirror-server refresh

### ISSUE THREAD

**Issue by jwjames** [xolvio/meteor-cucumber#151]
I've been having issues lately with the same scenario reloading while making edits, and the results of the tests being inconsistently different.

All tests in a scenario will pass, then I'll make an edit to a test further down in the bottom of the scenario, and when the server refreshes itself, a different test up the chain in the beginning of the scenario will start to fail.

Or there will be a step that doesn't pass:
```javascript
this.When(/^I click on "([^"]*)"$/, function (selector, callback) {
      this.browser
        .waitForExist(selector, 3000)
        .isExisting(selector, function (err, isExisting) {
          assert(isExisting);
        })
        .waitForVisible(selector, 3000)
        .isVisible(selector, function (err, isVisible) {
          assert(isVisible);
        })
        .click(selector)
        .call(callback);
    });
```
If more time is added to the .waitFor tests and I save the step file, it will refresh the server and this will pass. 

Then I'll do a full restart of the mirror-server, running ```CUCUMBER_TAGS='@randomscenario' meteor``` again with the added .waitFor time and it will fail at the .isExisting assertion.

**Comment by samhatoum** [comment]
hmm, I can't quite track what's happening there. Could you recreate the error in n isolated repo? That exercise will either show an error in the implementation or a bug in the framework. Both ways will lead to a fix!

**Comment by jwjames** [comment]
Okay here's the repo: https://github.com/jwjames/cucumber-issue

Most of the time it works perfectly. 

Sometimes I'll get this on startup: 
```
@dev
  Scenario: Creating new todo items                       # features/sample.feature:12
    Given I have landed on the website for the first time # features/sample.feature:4
    And I navigate to "/join"                             # features/sample.feature:5
    And I type "user@user.com" in the email input         # features/sample.feature:6
      AssertionError: false == true
        at WebdriverIO.<anonymous> (/Users/jeffjames/Projects/todos/tests/cucumber/features/step_definitions/sample_steps.js:70:11)
```

Or when I change something minor in the file like:

```
@dev
  Scenario: Creating new todo items
    When I see ".btns-group-vertical"
    When I see ".js-user-menu"
```
to
```
@dev
  Scenario: Creating new todo items
    When I see ".btns-group-vertical"
    And I see ".js-user-menu"
```
or vice versa, I'll get the error above. Sometimes it shows up when I restart the server.

**Comment by jwjames** [comment]
I shortened the waitFor times from 3000ms to 1000ms and it's happening a lot more frequently now. Pushed to the repo.

**Comment by samhatoum** [comment]
Perfect. Thanks for this, I'll investigate and get back to you

**Comment by samhatoum** [comment]
the issue looks looks like it was due to multiple chimp servers starting.

Can you try again with v0.11.0 - I scenarios to work at all locally
