### ISSUE TITLE
Failure output in CI not working

### ISSUE THREAD

**Issue by Sanjo** [xolvio/meteor-cucumber#152]
Instead of the error you see `[TypeError: Cannot call method 'join' of undefined]`.

That's because the Velocity code in Meteor expects the result to have the ancestors property. It is missing here: https://github.com/xolvio/meteor-cucumber/blob/f9bfed0bc146e70cf8cd35f0f8156a7fc166bab3/src/mirror-server.js#L163-L167. Not sure if this should be fixed in Cucumber, velocity:core or Meteor Velocity code.

**Comment by Sanjo** [comment]
I will fix this in meteor core, because ancestors is an optional property.

**Comment by Sanjo** [comment]
Fixed with: https://github.com/meteor-velocity/meteor/commit/8febd30

**Comment by jakobloekke** [comment]
I'm getting this error still. Is this bug fix released yet, and if so how can I check if I have it?
