### ISSUE TITLE
How to handle user logins

### ISSUE THREAD

**Issue by jeroenpeeters** [xolvio/meteor-cucumber#153]
My application requires a user to always be logged in. My question is how to implement that, without always going through the login screen. On the Meteor forums I've found this answer: https://forums.meteor.com/t/the-right-way-to-handle-authentication-and-authorization-in-cucumber-for-meteor/2926/6. But this solution uses the Meteor object to log a user in automatically.

As I understand, this is currently not possible anymore. What would be the preferred way now?

**Comment by workflow** [comment]
@jeroenpeeters Why not possible anymore?

Not sure if it's useful or best practice, but here's how I do it.

In every Feature (or Scenario) where its needed, I add as a `Background`

```cucumber
Background: 

  Given I am a <type of user>

```
Step Definition:
```gherkin
this.Given(/^I am a (?:user|supporter)$/, function(callback) {
  this.server.call('createRegularUserAndLogin').then(function() {
    browser.executeAsync(function(done) {
      Meteor.loginWithPassword('madam@apple.com', '123', done);
    }).should.eventually.not.have.deep.property('value.message').and.notify(callback);
  });
});
```

Fixture function (under `tests/cucumber/fixtures`):

```js
/**
 * User related fixtures
 */
(function() {

    'use strict';

    Meteor.methods({
        'createRegularUserAndLogin': function() {
            var user = Factory.create('user', {});
            this.setUserId(user._id);
        },

```

Factory method for users, using `dburles:factory ` package, will depend on the specifics of your schema:

```js
Factory.define('user', Meteor.users, {
    profile: {
        firstName: 'Madam',
        lastName: 'Apple',
        name: 'Madam Apple',
        email: 'madam@apple.com'
    },
    emails: [
        {
            address: 'madam@apple.com',
            verified: true
        }
    ],
    hasRegistered: true
}).after(function(user) {
    Accounts.setPassword(user._id, '123');
});
```

**Comment by jeroenpeeters** [comment]
I get an error saying 'Meteor' is undefined.

**Comment by samhatoum** [comment]
you need to navigate to the page first using `this.url`

This is the most common gotcha!

**Comment by samhatoum** [comment]
@jeroenpeeters did this work for you?

**Comment by jamiecollinson** [comment]
@workflow / @samhatoum could you explain the `value.message` part of the following?

```
browser.executeAsync(function(done) {
  Meteor.loginWithPassword('madam@apple.com', '123', done);
}).should.eventually.not.have.deep.property('value.message').and.notify(callback);
```

I'm trying to debug a problem I'm having with creating some background feature steps which provide either a logged in or logged out user for scenarios. I find the following steps work with the firefox webdriver locally, fail with the chrome webdriver locally and intermittently fail on circleci with firefox webdriver. 

I assume I'm making some obvious mistake with the `executeAsync` promises, and in looking through the various bits of documentation on github, webdriver.io and http://chimp.readme.io/docs/meteor-cucumber came across this and wondered if the bit of code mentioned above might be the answer.

If not, any pointers would be very welcome! Here are my current steps:
```
module.exports = function () {

  var logout = function(done) {
    Meteor.logout(done);
  };

  var login = function(email, password, done) {
    Meteor.loginWithPassword(email, password, done);
  };

  this.Given(/^I am a logged out user$/, function (callback) {
    this.client
      .url(process.env.ROOT_URL)
      .executeAsync(logout)
      .call(callback);
  });

  this.Given(/^I am a logged in user$/, function (callback) {
    this.client
      .url(process.env.ROOT_URL)
      .executeAsync(logout)
      .executeAsync(login, 'test@domain.com', 'goodpassword')
      .call(callback);
  });
};
```

**Comment by workflow** [comment]
@jamiecollinson 

This part

```
.should.eventually.not.have.deep.property('value.message').and.notify(callback);
```

...is just a somewhat convoluted way of checking that `Meteor.loginWithPassword()` does not return an error. Could probably be done in a more readable way!

I just tried running your steps exactly as provided, and for me they pass on both firefox and chrome (v43.x) locally.
Where do they fail exactly for you on chrome? Do you have a recent chromedriver version installed?

Perhaps try

*  providing us with a bit more error output (create a separate issue)
* inserting WebDriver's `.debug()` before your first `executeAsync()`, go to the browser and try to logout/login manually via console. Does that work?

**Comment by jamiecollinson** [comment]
@workflow - thanks for taking a look. I was confused at where the `value.message` comes from as I have been doing checks on the returned value by checking the `value` property of the result of an `executeAsync`, e.g.

```
this.Then(/^I am logged in$/, function(callback) {
    this.client
      .executeAsync(function(done) {
        // browser context
        done(Meteor.userId());
      }).then(function(ret) {
        // in node.js context
        ret.value.should.exist; // chai should syntax
        expect(ret.value).to.exist; // chai expect syntax
      })
      .call(callback);
});
```

I've actually resolved the issue we were having - I believe it was down to our attempt to logout other sessions on each login:

```
Accounts.onLogin(function(cb) {
  if (!Roles.userIsInRole(Meteor.user(), ['superadmin'])) {
   // Meteor.logoutOtherClients();
  }
});
```

Commenting out the above line stopped the issue, so presumably because `Meteor.logoutOtherClients()` is async it sometimes completed after we'd already logged in in another scenario and caused the issue.

**Comment by jamiecollinson** [comment]
@workflow - also thanks for pointing me at http://webdriver.io/api/utility/debug.html - wasn't aware of that!

**Comment by samhatoum** [comment]
May I close this?

**Comment by jamiecollinson** [comment]
Okay by me.
