### ISSUE TITLE
Annotations don't seem to be working

### ISSUE THREAD

**Issue by jeroenpeeters** [xolvio/meteor-cucumber#154]
I just noticed that all tests are always being executed, also when run in development mode. Trying to specify specific annotations using the CUCUMBER_TAGS environment var does not have any effect. Also tried using CHIMP_OPTIONS='--tags=@dev'

This is how i run meteor: CUCUMBER_TAGS=@dev SELENIUM_BROWSER=firefox meteor --settings settings.json

Am I missing something?

**Comment by samhatoum** [comment]
I think you have to put the tags inside single quotes. 

Also, that is default behavior so you shouldn't have to specific the @dev tag. What happens when you don't specify it?

**Comment by jeroenpeeters** [comment]
It runs all the tests always, that's why I started to specify the cucumber tags but that also didn't work. Using single quotes does not matter. Anyway, I also ran into another issue which prevents me from using meteor-cucumber. After playing and developing tests for an hour my system became unresponsive. I found out that a lot of java processes where spawned from meteor-cucumber which kept on running. They consumed all memory and swap space. Maybe you want to look into that as well....

**Comment by samhatoum** [comment]
This is odd. Would you please do the following so I can debug:

Run `VELOCITY_DEBUG=1 meteor`

And paste the output of cucumber.log here. Also can you paste your `.meteor/versions` content.

Thanks

**Comment by samhatoum** [comment]
@jeroenpeeters any luck with this? do you have a debug for me?

**Comment by samhatoum** [comment]
The latest version 0.11.1 has fixed the multiple process problem. Can you try again please?
