### ISSUE TITLE
TypeError: Object #<World> has no method 'capture'  ...

### ISSUE THREAD

**Issue by JohanTh** [xolvio/meteor-cucumber#156]
I am getting this error when trying to use `this.capture('name')` as described here on point 3:
https://forums.meteor.com/t/cant-get-test-to-pass-with-xolvio-cucumber/6148/2?u=johan_t

> TypeError: Object #<World> has no method 'capture'  ...

My step is defined like this:

```javascript
this.When(/^I click "([^"]*)"$/, function (arg1, callback) {
  this.capture('name');
  this.client.click('.createUser').call(callback);
});
```

**Comment by samhatoum** [comment]
hey, you need to use `this.browser.capture`

**Comment by samhatoum** [comment]
please close this issue if it fixes it for you
