### ISSUE TITLE
Update webdriver IO to 3.0

### ISSUE THREAD

**Issue by cwohlman** [xolvio/meteor-cucumber#157]
Specifically I'm interested in using the new selectors: http://webdriver.io/guide/usage/selectors.html, but I'm sure there are other features that would be nice to have.

**Comment by samhatoum** [comment]
coming up! We already have it on a branch for chimp

**Comment by cwohlman** [comment]
Awesome!

**Comment by samhatoum** [comment]
Released in v0.11.0
