### ISSUE TITLE
No dev tags shows infinite pulsating blob

### ISSUE THREAD

**Issue by samhatoum** [xolvio/meteor-cucumber#159]
It should show green when there are 0 tests to run

**Comment by colvint** [comment]
@samhatoum I get the infinite pulsating blob even *with* `@dev` tagged scenarios. Revving back with `meteor add xolvio:cucumber@0.10.0` solves it.

**Comment by samhatoum** [comment]
could you please post your full log here from both the main process and the mirror and set `VELOCITY_DEBUG=1` please?

**Comment by colvint** [comment]
Well now that's weird. Revved back to the latest and it works now. I suspect there must have been an earlier version hanging around. Sorry about the false alarm :alarm_clock: !

**Comment by samhatoum** [comment]
no worries. version 0.10 had a serious bug! it kept a lot of chimp processes hanging... all of which reported back to the main process! let me know if you see it again

**Comment by samhatoum** [comment]
fixed in 0.11.1
