### ISSUE TITLE
Exception while invoking method 'velocity/reset'

### ISSUE THREAD

**Issue by philipobrien** [xolvio/meteor-cucumber#164]
I just created a new Meteor project 

```
meteor create velocity-expedition
cd velocity-expedition
meteor add xolvio:cucumber
meteor
```

and in the console I'm noticing the following error being reported

![image](https://cloud.githubusercontent.com/assets/1763813/8675421/ba7c5b76-2a3b-11e5-97e1-4bcd122d5847.png)

The reporter is working correctly, and I can make tests pass/fail, so maybe I can just ignore it, but thought I better flag it here.

Here is the content of `.meteor/versions`

```
amplify@1.0.0
autopublish@1.0.3
autoupdate@1.2.1
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
coffeescript@1.0.6
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
insecure@1.0.3
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
less@1.0.14
livedata@1.0.13
logging@1.0.7
meteor@1.1.6
meteor-platform@1.2.2
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
mongo@1.1.0
observe-sequence@1.0.6
ordered-dict@1.0.3
package-version-parser@3.0.3
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
sanjo:long-running-child-process@1.1.1
sanjo:meteor-files-helpers@1.1.0_6
sanjo:meteor-version@1.0.0
session@1.1.0
spacebars@1.0.6
spacebars-compiler@1.0.6
templating@1.1.1
tracker@1.0.7
ui@1.0.6
underscore@1.0.3
url@1.0.4
velocity:chokidar@1.0.3_1
velocity:core@0.7.1
velocity:html-reporter@0.6.2
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
webapp@1.2.0
webapp-hashing@1.0.3
xolvio:cucumber@0.11.1
```

Here is the content of `.meteor/packages`

```
meteor-platform
autopublish
insecure
xolvio:cucumber
```

**Comment by samhatoum** [comment]
Thanks I'll check it out

**Comment by groeneveld** [comment]
I've gotten that same error in a clean Meteor todos example project. The html reporter in my app is stuck on 'loading' even after rebooting meteor. It happened when I clicked add example tests.

**Comment by ramijarrar** [comment]
In the definition of the 'velocity/reset' method [here](https://github.com/meteor-velocity/velocity/blob/7d654303b3bd8bf19035d0bf2bd890ff3f9c7087/src/core.js#L273-276) there is a required 'name' parameter which seems to be missing from calls in velocity packages (I have experienced this in meteor-jasmine too), so perhaps there was an API change?

**Comment by ramijarrar** [comment]
@groeneveld I don't think the hanging 'loading' screen has much to do with this, I think your best bet is to look into the cucumber log file as that has helped me debug similar errors in the past

**Comment by samhatoum** [comment]
there was an API change indeed and I can see this error. I'll get back to it soon. Thanks for reporting.

By the way v0.12 now has a run-all button in the html reporter!

**Comment by samhatoum** [comment]
turns out the reset error is from the html reporter. fixed in the latest release
