### ISSUE TITLE
Using Cucumber to define logging into Google as a step

### ISSUE THREAD

**Issue by lscordilis** [xolvio/meteor-cucumber#166]
So I'm using accounts-google for my app's login functionality, and I've created a hook in the tests/cucumber/features/support folder defining the service configuration of the Google app client registration. Then I go on to define the steps as such:

```Javascript
        this.Given(/^I am logged in$/, function(callback) {
            this.client
            .url(process.env.ROOT_URL)
            .waitForExist('body *')
            .waitForVisible('body *')
            .click('#login-buttons')
            .setValue('#Email', 'example@example.com')
            .waitForVisible('#Passwd')
            .setValue('#Passwd', 'a passwd')
            .click('#signIn')
            .call(callback);
        });
```

![image](https://cloud.githubusercontent.com/assets/12753650/8680808/c8a3d652-2a31-11e5-8f05-ffa499c58a7e.png)
![image](https://cloud.githubusercontent.com/assets/12753650/8680812/db161656-2a31-11e5-8306-5027044c7fa8.png)

I could just add the localhost at whatever port to the Google developer console for now, but obviously that's not very reasonable. I understand Velocity is built with making multiple mirrors at randomly available ports in mind, but I feel like there's a real need to let people specify the port(s) because of these sorts of issues with external services and APIs. In the meantime, do you have any suggestions for a a workaround or other techniques to test my app? I'm pretty new to Cucumber and end-to-end testing so any advice would be welcome.

**Comment by samhatoum** [comment]
you can use the google fake package:
https://github.com/dusual/meteor-google-fake

it's a good practice to stub external dependencies when doing e2e testing

**Comment by lscordilis** [comment]
Thank you, this is very helpful. I wasn't sure how to practically and securely test my login system with Cucumber before.
