### ISSUE TITLE
TypeError: Object #<WebdriverIO> has no method 'debug'

### ISSUE THREAD

**Issue by fulv** [xolvio/meteor-cucumber#168]
I'm new at this, so please pardon me for opening this issue if it's obvious.  But the overview of xolvio:cucumber says that it features *Auto-configured WebdriverIO with PhantomJS*.  So in an attempt to find out what else I can put in my step definitions other than what is shown in the examples, I went to the webdriver api documentation, and tried this:  http://webdriver.io/api/utility/debug.html.  It doesn't work, and neither do other Webdriver commands I've tried.  The error is in the issue title.

My question is:  is this because I'm looking at too new a version of the Webdriver docs, or because of the custom way Webdriver is integrated, or some other reason?

This is my code:

```
    this.When(/^I click the News Item menu item$/, function (callback) {
      this.client.debug().
      click('#news-item').
      call(callback);
    });
```

Here are my .meteor/versions:

```
accounts-base@1.2.0
accounts-github@1.0.4
accounts-oauth@1.1.5
accounts-password@1.1.1
accounts-ui@1.1.5
accounts-ui-unstyled@1.1.7
amplify@1.0.0
autoupdate@1.2.1
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
coffeescript@1.0.6
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
github@1.1.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
less@1.0.14
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
meteor@1.1.6
meteor-platform@1.2.2
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
momentjs:moment@2.10.2
mongo@1.1.0
npm-bcrypt@0.7.8_2
oauth@1.1.4
oauth2@1.1.3
observe-sequence@1.0.6
ordered-dict@1.0.3
package-version-parser@3.0.3
peerlibrary:dimsum@0.1.8_6
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
sacha:spin@2.0.4
sanjo:long-running-child-process@1.1.1
sanjo:meteor-files-helpers@1.1.0_6
sanjo:meteor-version@1.0.0
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
spacebars@1.0.6
spacebars-compiler@1.0.6
srp@1.0.3
templating@1.1.1
tmeasday:publish-counts@0.3.6
tracker@1.0.7
ui@1.0.6
underscore@1.0.3
url@1.0.4
velocity:chokidar@1.0.3_1
velocity:core@0.7.1
velocity:html-reporter@0.6.2
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
webapp@1.2.0
webapp-hashing@1.0.3
xolvio:cucumber@0.10.0
```

And my .meteor/packages:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
momentjs:moment
peerlibrary:dimsum
iron:router
sacha:spin
tmeasday:publish-counts
accounts-password
accounts-ui
accounts-github
email
reactive-dict
reactive-var
xolvio:cucumber
```

**Comment by samhatoum** [comment]
Hey

1. Upgrade xolvio:cucumber to 0.11.x as it includes Webdriver3.0
2. The debug feature may not work with meteor cucumber, but please try it! I think it relies on Webdriver3.0's new runner feature which we don't use

**Comment by fulv** [comment]
Wow, thanks for the quick reply!
I didn't realize this was such a fast moving target -- I started playing with cucumber only in the last few weeks, and I'm already behind several versions!
Yeah, upgrading to 0.11.1 resolves this error.  I'm not exactly sure yet whether debug is working, but that's a different issue.  At least now I know I can use other webdriver features.

**Comment by workflow** [comment]
Webdriver's `debug()` successfully halts the scenario and thereby gives me the opportunity to inspect the current browser state - what doesn't seem to work is the resuming.
