### ISSUE TITLE
JRE error on OSX Yosemite

### ISSUE THREAD

**Issue by ramijarrar** [xolvio/meteor-cucumber#169]
![screen shot 2015-07-16 at 12 58 22 pm](https://cloud.githubusercontent.com/assets/9661116/8714606/673ee5de-2bba-11e5-86e7-909e7544cb10.png)

EDIT: See this article http://fredericiana.com/2014/10/21/osx-yosemite-java-runtime-environment/

**Comment by samhatoum** [comment]
Do you have chrome installed?

Try going to `http://localhost:8866/run` it might reveal the error

**Comment by ramijarrar** [comment]
I definitely have Chrome installed, and going to ```http://localhost:8866/run``` gives me the same dialog from before.

**Comment by samhatoum** [comment]
Awesome, thanks for reporting back
