### ISSUE TITLE
Java 6 dependency

### ISSUE THREAD

**Issue by ramijarrar** [xolvio/meteor-cucumber#170]
The error message in #169 which asks the user to install Java 8 is actually caused by an app requiring Java 6 (see http://fredericiana.com/2014/10/21/osx-yosemite-java-runtime-environment/ for more). 

Do you know what component of the package might be creating this dependency?

**Comment by samhatoum** [comment]
selenium-standalone. I recently upgraded that in chimp

**Comment by ramijarrar** [comment]
Has that made its way into version 0.11.1?

**Comment by samhatoum** [comment]
Yes

**Comment by Sanjo** [comment]
I only have Java 8 on my Ubuntu and it still works. Maybe java wasn't in the PATH? Try `which java`. This should return the path to java.

**Comment by jamiecollinson** [comment]
I've run it with Sun Java 8 on Windows and OpenJDK 7 on Ubuntu and both worked fine, so it doesn't seem too dependent on exactly which version you have.

**Comment by ramijarrar** [comment]
Guess the issue must be specific to Yosemite then

**Comment by ramijarrar** [comment]
Going to close this issue for now as it isn't really a huge deal, but @samhatoum perhaps a warning in the docs about this might be helpful for other users?
