### ISSUE TITLE
TravisCI/SauceLabs integration problem

### ISSUE THREAD

**Issue by frosario** [xolvio/meteor-cucumber#171]
Using documentation from here:
http://chimp.readme.io/docs/meteor-cucumber#section-saucelabs-selenium-grid

I expect to be able to run cucumber tests in saucelabs like so:
<pre><code>HUB_OPTS="HUB_HOST=ondemand.saucelabs.com \
HUB_PORT=4444 \
HUB_USER=$SAUCE_USERNAME \
HUB_KEY=$SAUCE_ACCESS_KEY \
HUB_PLATFORM='Windows 7' \
HUB_VERSION=35"

VELOCITY_CI=1 CHIMP_OPTIONS=$HUB_OPTS meteor --test</code></pre>

It seems as though the CHIMP_OPTIONS are not being passed through correctly:
https://travis-ci.org/ecohealthalliance/mantle/builds/71805419#L670

Output from velocity run starts here:
https://travis-ci.org/ecohealthalliance/mantle/builds/71805419#L233

meteor versions here:
https://github.com/ecohealthalliance/mantle/blob/saucelabs/.meteor/versions

meteor packages here:
https://github.com/ecohealthalliance/mantle/blob/saucelabs/.meteor/packages

**Comment by samhatoum** [comment]
try

```
export HUB_HOST=ondemand.saucelabs.com \
export HUB_PORT=4444 \
export HUB_USER=$SAUCE_USERNAME \
export HUB_KEY=$SAUCE_ACCESS_KEY \
export HUB_PLATFORM='Windows 7' \
export HUB_VERSION=35"
export VELOCITY_CI=1
meteor --test
```

**Comment by frosario** [comment]
Updated the shell script:
https://github.com/ecohealthalliance/mantle/blob/saucelabs/travis.sh#L15

Still fails:
https://travis-ci.org/ecohealthalliance/mantle/builds/71932985#L323

**Comment by samhatoum** [comment]
could you also run with `export VELOCITY_DEBUG=1` please

**Comment by frosario** [comment]
Updated script:
https://github.com/ecohealthalliance/mantle/blob/saucelabs/travis.sh

Job output is at:
https://travis-ci.org/ecohealthalliance/mantle/builds/72017424

**Comment by samhatoum** [comment]
Could you also upgrade meteor-cucumber? you're running a few versions behind I see. Not sure it'll fix this issue, but will fix something else I just saw :)

**Comment by frosario** [comment]
No worries :)

I upgraded to version 0.12.0 with this commit: https://github.com/ecohealthalliance/mantle/commit/250d6d4363ac2a20079452c9f8c1859dfc25547f

Build is rerunning at:
https://travis-ci.org/ecohealthalliance/mantle/builds/72019363

**Comment by bjarketrux** [comment]
I got the same error when trying to use selenium grid.
Command line:
```
java -jar selenium-server-standalone-2.47.1.jar -role hub
java -jar selenium-server-standalone-2.47.1.jar -role node -hub http://localhost:4444/grid/register
HUB_HOST=localhost HUB_PORT=4444 VELOCITY_DEBUG=1 meteor --test
```

That gives me the following console output (out of the ordinary):
```
[TypeError: Cannot call method 'join' of undefined]
FAILURE
```

And the log file:
```
[xolvio:cucumber] Cucumber is running
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:4444/wd/hub
[chimp] Finished running async processes with errors
[chimp] finished rerun
[xolvio:cucumber] Bad response from Chimp server. [TypeError: Cannot read property 'message' of null]
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] no child to interrupt
[chimp][selenium] interrupt called
[chimp][selenium] interrupt is not killing selenium because clean-selenium-server not set
[chimp] Finished interrupting processes
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
Parent process ( 6353 ) is dead! Exiting cucumber
```

Don't know if this helps...

**Comment by sircharleswatson** [comment]
@samhatoum @Sanjo I'm getting the same error as @bjarketrux on CodeShip after updating cucumber from v0.10.0 to v 0.12.3

```
[TypeError: Cannot call method 'join' of undefined]
FAILURE
```

Although, looking at the cucumber logs, it seems my tests pass but usually I see this
```
1 scenario (1 passed)
3 steps (3 passed)
```

But right before it prints that, that's when I get the `join` error.

**Comment by sircharleswatson** [comment]
Another thing about this...

If I ssh into the server running the build, when I run the tests the first time it fails but then I run it again and it passes. But obviously on CodeShip, I can't run it twice without the build failing.

**Comment by samhatoum** [comment]
@frosario can you please remove `export HUB_VERSION=35` and try again?

**Comment by samhatoum** [comment]
@frosario if you are here, come chat to me over at https://gitter.im/xolvio/chimp

**Comment by frosario** [comment]
@samhatoum I removed the HUB_VERSION var. Here's the result:
https://travis-ci.org/ecohealthalliance/mantle/builds/73885942#L566

**Comment by samhatoum** [comment]
@frosario I'm about to commit a branch to mantle to fix this

**Comment by frosario** [comment]
+1

**Comment by frosario** [comment]
+1
