### ISSUE TITLE
Promise syntax

### ISSUE THREAD

**Issue by jwjames** [xolvio/meteor-cucumber#172]
I'm getting this error message when I try to run my tests now:
```
[chimp] Detected an unhandledRejection.
[chimp] Did you forget to append a ".catch" to a promise that contains assertions?
[chimp][hooks] { [Error: javascript error: done is not a functionJavaScript stack:TypeError: done is not a function    at eval (eval at executeAsyncScript (unknown source), <anonymous>:8:13)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:12)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:38)    at executeAsyncScript (<anonymous>:321:26)    at <anonymous>:337:29    at callFunction (<anonymous>:229:33)    at <anonymous>:239:23    at <anonymous>:240:3    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)]
  message: 'javascript error: done is not a functionJavaScript stack:TypeError: done is not a function    at eval (eval at executeAsyncScript (unknown source), <anonymous>:8:13)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:12)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:38)    at executeAsyncScript (<anonymous>:321:26)    at <anonymous>:337:29    at callFunction (<anonymous>:229:33)    at <anonymous>:239:23    at <anonymous>:240:3    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)',
  type: 'RuntimeError' }
[chimp][hooks] Forcibly exiting Cucumber
[chimp] Finished running async processes with errors
```

I have written a lot of tests without promise syntax and it seems that with one of the new updates, meteor-cucumber is requiring I write all tests with a promise syntax. Unless I'm missing something, could you please continue to support the callback syntax? It would make my life much easier!  

Thanks,

Jeff

**Comment by Sanjo** [comment]
Maybe you forgot to call the callback in a step definition.

How you can find it out:
1. Find the step and the feature that was the last one that succeeded before you got this error.
2. The following step in the feature is the step that causes this error.
3. Go to the step definition of this step and make sure that you call the callback or return a promise.

If no steps succeed at all, maybe it is part of the before hooks.

**Comment by jwjames** [comment]
No steps succeed, but my before hook (which resets the test data and seeds it again) is running successfully as I can see in the console output. What I get is confirmation that the before hook succeeded, and then I immediately get the error above.

**Comment by samhatoum** [comment]
It's actually webdriver 3.0 that has changed syntax so we can't really support two versions of it :/

Can you isolate to one feature only and put one dump step in one scenario? this might help isolate the issue

**Comment by samhatoum** [comment]
also feel free to chat in the velocity slack channel

**Comment by Sanjo** [comment]
> It's actually webdriver 3.0 that has changed syntax so we can't really support two versions of it :/

Webdriver 3.0 also supports callbacks. So the problem must be somewhere else.

**Comment by samhatoum** [comment]
@jwjames did you get to the bottom of this?

**Comment by JohanTh** [comment]
I am getting this now and my first step looks like this:

    this.Given(/^I am not logged in$/, function (callback) {
      var self = this;

      self.client
        .url(url.resolve(process.env.ROOT_URL, '/login'))
        .executeAsync(function (done) {
          Meteor.call('userId', function (err, res) {
            done(res); // Don't pass `err` into this as the first argument!
          });
        }, function (err, res) {
          if (_.isNull(res.value)) {
            self.server.call('reset').then(callback);
          } else {
            self.client
              .executeAsync(function (done) {
                Meteor.call('logOutFromCucumber', function (err, res) {
                  done(res); // Don't pass `err` into this as the first argument!
                });
              }, function (err, res) {
                if (_.isNull(res.value)) {
                  self.server.call('reset').then(callback);
                } else {
                  callback.fail(new Error("You are logged in"));
                }
              });
          }
        });
    });

https://www.dropbox.com/s/6dkth5xn0us310i/step_catch_error.PNG?dl=0

**Comment by samhatoum** [comment]
I would break this step down part by part to see where the "leak" is

**Comment by samhatoum** [comment]
You may want to consider the approach I used in Letterpress where you do a full reset in the before step.

The step you have above looks like it's doing too much

**Comment by jwjames** [comment]
@samhatoum @Sanjo here's a repo that contains the meteor todos example with some basic tests I wrote: https://github.com/jwjames/cucumber-issue-2

When I run it with 
```
VELOCITY_CI=1 meteor --test
```

I get the exact errors shown in my first post: 
```
Feature: Cucumber tests


  @dev
  Scenario: Creating new todo items                       # features/sample.feature:12
[chimp] Detected an unhandledRejection.
[chimp] Did you forget to append a ".catch" to a promise that contains assertions?
[chimp][hooks] { [Error: javascript error: done is not a functionJavaScript stack:TypeError: done is not a function    at eval (eval at executeAsyncScript (unknown source), <anonymous>:8:13)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:12)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:38)    at executeAsyncScript (<anonymous>:321:26)    at <anonymous>:337:29    at callFunction (<anonymous>:229:33)    at <anonymous>:239:23    at <anonymous>:240:3    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)]
  message: 'javascript error: done is not a functionJavaScript stack:TypeError: done is not a function    at eval (eval at executeAsyncScript (unknown source), <anonymous>:8:13)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:12)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:10:38)    at executeAsyncScript (<anonymous>:321:26)    at <anonymous>:337:29    at callFunction (<anonymous>:229:33)    at <anonymous>:239:23    at <anonymous>:240:3    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)',
  type: 'RuntimeError' }
[chimp][hooks] Forcibly exiting Cucumber
[chimp] Finished running async processes with errors
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
Parent process ( 5424 ) is dead! Exiting cucumber
```

**Comment by ramijarrar** [comment]
Getting the same error with this code:
```
    this.Then(/^I should no longer see the dish$/, function (done) {
        this.client.isExisting(".qa-dish-item").then(function (exists) {
            expect(exists).to.be.false;
            done();
        });
    });
```

**Comment by samhatoum** [comment]
@jwjames I've managed to get your code working with this code:

```javascript
return this.browser
  .url(process.env.HOST)
  .waitForExist('body *')
  .executeAsync(function (done) {
    if (Meteor.userId() || Meteor.loggingIn()) {
      Meteor.logout(function (err) { done(!err); });
    } else { done(true); }
  }).then(function (res) {
    assert(res.value);
    // you can call callback() here if you want without returning the promise
  });
```

It looks like passing a callback as a second parameter to the `executeAsync` triggers the `done is not a function` error. If you use `then` instead, then you get the callback - and you also get the response as the first param. I'm assuming the err is implicit the promised-land (see what I did there?)

@ramijarrar I need the full context of your issue please, I think it's unrelated to this one. The error is a catch-all error so it's confusing. I'll change the message in a future release.

**Comment by ramijarrar** [comment]
Sure, I'll create a new issue

**Comment by JohanTh** [comment]
I use your method and I am getting this error:

> ←[31mError: javascript error: Meteor is not definedJavaScript stack:ReferenceError: Meteor is not d
efined    at eval (eval at executeAsyncScript (unknown source), <anonymous>:3:13)    at eval (eval
at executeAsyncScript (unknown source), <anonymous>:9:10)    at eval (eval at executeAsyncScript (u
nknown source), <anonymous>:9:36)    at executeAsyncScript (<anonymous>:321:26)    at <anonymous>:3
37:29    at callFunction (<anonymous>:229:33)    at <anonymous>:239:23    at <anonymous>:240:3    a
t Object.InjectedScript._evaluateOn (<anonymous>:905:140)    at Object.InjectedScript._evaluateAndW
rap (<anonymous>:838:34)
  at new ErrorHandler.RuntimeError (C:\Users\gatsu\AppData\Local\.meteor\packages\xolvio_cucumber\0
.12.3\npm\node_modules\chimp\node_modules\webdriverio\lib\utils\ErrorHandler.js:92:12)
  at RequestHandler.<anonymous> (C:\Users\gatsu\AppData\Local\.meteor\packages\xolvio_cucumber\0.12
.3\npm\node_modules\chimp\node_modules\webdriverio\lib\utils\RequestHandler.js:168:25)
  at Request.self.callback (C:\Users\gatsu\AppData\Local\.meteor\packages\xolvio_cucumber\0.12.3\np
m\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:373:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (C:\Users\gatsu\AppData\Local\.meteor\packages\xolvio_cucumber\0.12.3\npm\
node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:1318:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (C:\Users\gatsu\AppData\Local\.meteor\packages\xolvio_cucumber\0.1
2.3\npm\node_modules\chimp\node_modules\webdriverio\node_modules\request\request.js:1266:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:486:13)
←[39m

Sometimes the above error tells me "chrome is not reachable" instead of this. My step definition looks like this and where should I put the function `clientLogoutFunc`?

```javascript
(function () {
  'use strict';
  var _ = require('underscore');

  module.exports = function () {
    var url = require('url');

    this.Given(/^I am not logged in$/, function (callback) {
      var self = this;

      var clientLogoutFunc = function (done) {
        if (Meteor.userId() || Meteor.loggingIn()) {
          done(!Meteor.getUserId());
        } else {
          done(true);
        }
      };

      return self.browser
        .executeAsync(clientLogoutFunc)
        .then(function (res) {
          if (res.value) {
            self.server.call('reset').then(callback);
          } else { 
            callback.fail(new Error("You are logged in"));
          }
        });
    });
  };
})();
```

Sometimes I also get a message about Meteor not being defined.

**Comment by jwjames** [comment]
@samhatoum I have updated the code in the repo I posted with the changes you suggested.

## Step file: 
``` javascript
(function () {

    'use strict';

    var _ = require('underscore'),
      assert = require('assert'),
      url = require('url');

    var clientLogoutFunc = function (done) {
      if (Meteor.userId() || Meteor.loggingIn()) {
        Meteor.logout(function (err) { done(!err); });
      } else {
        done(true);
      }
    };

    module.exports = function () {

      this.Given(/^I have landed on the website for the first time$/, function (clientLogoutFunc, callback) {
        this.browser
          .url(process.env.HOST)
          .waitForExist('body *')
          .executeAsync(clientLogoutFunc)
          .then(function (res) {
            assert(!res.value);
            // you can call callback() here if you want without returning the promise
          });
      });
  };

})();
```

## Feature file: 
```
Feature: Cucumber tests

  @dev
    Scenario: Landing page for first time
      Given I have landed on the website for the first time
```
## In terminal: 
```
➜  cucumber-issue-2 git:(master) ✗ VELOCITY_CI=1 meteor --test
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
I20150730-15:39:48.983(-4)? [velocity] is in continuous integration mode
I20150730-15:39:49.951(-4)? [velocity] cucumber is starting a mirror at http://localhost:63462/.
I20150730-15:39:49.973(-4)? [velocity] You can see the mirror logs at: tail -f /Users/jeffjames/Projects/callback-issue/cucumber-issue-2/.meteor/local/log/cucumber.log
[TypeError: Cannot call method 'join' of undefined]
FAILURE
```

## The tail: 
```
@dev
  Scenario: Landing page for first time                   # features/sample.feature:17
[chimp] Detected an unhandledRejection.
[chimp] Did you forget to append a ".catch" to a promise that contains assertions?
[chimp][hooks] { [Error: javascript error: Cucumber is not definedJavaScript stack:ReferenceError: Cucumber is not defined    at eval (eval at executeAsyncScript (unknown source), <anonymous>:3:9)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:12:10)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:12:36)    at executeAsyncScript (<anonymous>:321:26)    at <anonymous>:337:29    at callFunction (<anonymous>:229:33)    at <anonymous>:239:23    at <anonymous>:240:3    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)]
  message: 'javascript error: Cucumber is not definedJavaScript stack:ReferenceError: Cucumber is not defined    at eval (eval at executeAsyncScript (unknown source), <anonymous>:3:9)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:12:10)    at eval (eval at executeAsyncScript (unknown source), <anonymous>:12:36)    at executeAsyncScript (<anonymous>:321:26)    at <anonymous>:337:29    at callFunction (<anonymous>:229:33)    at <anonymous>:239:23    at <anonymous>:240:3    at Object.InjectedScript._evaluateOn (<anonymous>:905:140)    at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)',
  type: 'RuntimeError' }
[chimp][hooks] Forcibly exiting Cucumber
[chimp] Finished running async processes with errors
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
Parent process ( 6394 ) is dead! Exiting cucumber
```

Did I implement the changes correctly?

**Comment by samhatoum** [comment]
change this from:

```
      this.Given(/^I have landed on the website for the first time$/, function (clientLogoutFunc, callback) {
```

to

```
      this.Given(/^I have landed on the website for the first time$/, function () {
```

you're overriding the `clientLogoutFunc` with a non-existent parameter and it looks like you b0rked cucumber doing that :boom:

**Comment by jwjames** [comment]
It works! Thank you.

**Comment by jwjames** [comment]
I created a new branch in the repo because I realized that the code was passing with false positives from `assert`. Here's a link directly to the assertion: 

https://github.com/jwjames/cucumber-issue-2/blob/false-positive/tests/cucumber/features/step_definitions/sample_steps.js#L33

**Comment by Sanjo** [comment]
@jwjames You don't return the promise (`return this.browser`). I think because of this, the exception (rejected promise chain) is not handled by the step definition result handler in Cucumber.
