### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by frankapimenta** [xolvio/meteor-cucumber#174]
1. New project created.
2. Your Package added.
3. Cucumber samples added.
4. Run raises error with log:

[velocity] Established connection with Velocity.
[xolvio:cucumber] Cucumber is running
[chimp] Finished running async processes with errors
[xolvio:cucumber] Bad response from Chimp server. [TypeError: Cannot read property 'message' of null]

I have all pre-requesites installed.

**Comment by samhatoum** [comment]
Hi @frankapimenta 

Could you please follow these instructions:

https://github.com/xolvio/meteor-cucumber/blob/develop/CONTRIBUTING.md

It would help me catch the bug

**Comment by ramijarrar** [comment]
@frankapimenta What OS are you on?

**Comment by frankapimenta** [comment]
Hi.

Im on mac 10.10.4 Yosemite. Later will get back to you regarding the rest.

**Comment by frankapimenta** [comment]
@samhatoum as requested:

--- meteor server output ---
I20150728-21:49:36.715(2)? ** You've set up some data subscriptions with Meteor.publish(), but
I20150728-21:49:36.716(2)? ** you still have autopublish turned on. Because autopublish is still
I20150728-21:49:36.717(2)? ** on, your Meteor.publish() calls won't have much effect. All data
I20150728-21:49:36.717(2)? ** will still be sent to all clients.
I20150728-21:49:36.717(2)? **
I20150728-21:49:36.717(2)? ** Turn off autopublish by removing the autopublish package:
I20150728-21:49:36.717(2)? **
I20150728-21:49:36.717(2)? **   $ meteor remove autopublish
I20150728-21:49:36.717(2)? **
I20150728-21:49:36.717(2)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150728-21:49:36.718(2)? ** for each collection that you want clients to see.
I20150728-21:49:36.718(2)?
I20150728-21:49:36.719(2)? [velocity] adding velocity core
I20150728-21:49:36.719(2)? [xolvio:cucumber] Cucumber hub is loading
I20150728-21:49:36.719(2)? [velocity] Register framework cucumber with regex ^tests/cucumber/((?!node_modules/).)+\.(feature|js|coffee|litcoffee|coffee\.md)$
I20150728-21:49:38.066(2)? [velocity] Server startup
I20150728-21:49:38.069(2)? [velocity] app dir /Users/frankpimenta/Programming/my-projects/superman
I20150728-21:49:38.069(2)? [velocity] config = {
I20150728-21:49:38.069(2)?   "cucumber": {
I20150728-21:49:38.070(2)?     "regex": "^tests/cucumber/((?!node_modules/).)+\\.(feature|js|coffee|litcoffee|coffee\\.md)$",
I20150728-21:49:38.070(2)?     "name": "cucumber",
I20150728-21:49:38.070(2)?     "_regexp": {}
I20150728-21:49:38.070(2)?   }
I20150728-21:49:38.070(2)? }
I20150728-21:49:38.070(2)? [velocity] resetting the world
I20150728-21:49:38.072(2)? [velocity] frameworks with disable auto reset: []
I20150728-21:49:38.083(2)? [velocity] Add paths to watcher [ '/Users/frankpimenta/Programming/my-projects/superman/tests' ]
I20150728-21:49:38.085(2)? [velocity] 1 mirror(s) requested
I20150728-21:49:38.123(2)? [velocity] Mirror process forked with pid 72431
I20150728-21:49:38.123(2)? [velocity] cucumber is starting a mirror at http://localhost:53010/.
=> Started your app.

=> App running at: http://localhost:3000/
I20150728-21:49:38.142(2)? [velocity] You can see the mirror logs at: tail -f /Users/frankpimenta/Programming/my-projects/superman/.meteor/local/log/cucumber.log
I20150728-21:49:38.153(2)? [velocity] Search framework for path tests/cucumber/package.json
I20150728-21:49:38.153(2)? [velocity] No framework registered for tests/cucumber/package.json
I20150728-21:49:38.159(2)? [velocity] Search framework for path tests/cucumber/fixtures/my_fixture.js
I20150728-21:49:38.160(2)? [velocity] Target framework for tests/cucumber/fixtures/my_fixture.js is cucumber
I20150728-21:49:38.160(2)? [velocity] Search framework for path tests/cucumber/features/sample.feature
I20150728-21:49:38.161(2)? [velocity] Target framework for tests/cucumber/features/sample.feature is cucumber
I20150728-21:49:38.165(2)? [velocity] Search framework for path tests/cucumber/features/step_definitions/sample_steps.js
I20150728-21:49:38.166(2)? [velocity] Target framework for tests/cucumber/features/step_definitions/sample_steps.js is cucumber
I20150728-21:49:38.169(2)? [velocity] File scan complete, now watching /tests
I20150728-21:49:38.169(2)? [velocity] Triggering queued startup functions
I20150728-21:49:57.703(2)? [velocity] Mirror registered. Handshaking with mirror...
I20150728-21:49:57.732(2)? [velocity] Connected to mirror, setting state to ready { framework: 'cucumber',
I20150728-21:49:57.733(2)?   host: 'http://localhost:53010/',
I20150728-21:49:57.733(2)?   port: '53010' }

---

cucumber log:

all
[chimp] stdout:
[chimp] stderr:
[chimp] Chimp server is running on port 8866 http://localhost:53010/
[chimp] Handshaking with DDP server
[xolvio:cucumber] Received handshake from Chimp.
[xolvio:cucumber] Connecting to hub
[chimp] Handshake complete, closing DDP connection
[xolvio:cucumber] Connected to hub.
[xolvio:cucumber] Find and run triggered { '0':
   { name: 'sample_steps.js',
     absolutePath: '/Users/frankpimenta/Programming/my-projects/superman/tests/cucumber/features/step_definitions/sample_steps.js',
     relativePath: 'tests/cucumber/features/step_definitions/sample_steps.js',
     targetFramework: 'cucumber',
     lastModified: 1438112978165,
     _id: '/Users/frankpimenta/Programming/my-projects/superman/tests/cucumber/features/step_definitions/sample_steps.js' } }
[xolvio:cucumber] Running in batch-features mode.
^[[33m[xolvio:cucumber] Cucumber is running^[[39m
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:53040/wd/hub
[chimp] Finished running async processes with errors
[chimp] finished rerun
^[[31m[xolvio:cucumber] Bad response from Chimp server.^[[39m [TypeError: Cannot read property 'message' of null]
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] no child to interrupt
[chimp][selenium] interrupt called
[chimp][selenium] interrupt is not killing selenium because clean-selenium-server not set
[chimp] Finished interrupting processes

--- 
packages:

# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-platform
autopublish
insecure
xolvio:cucumber
velocity:html-reporter

--versions

amplify@1.0.0
autopublish@1.0.3
autoupdate@1.2.1
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
coffeescript@1.0.6
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
insecure@1.0.3
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
less@1.0.14
livedata@1.0.13
logging@1.0.7
meteor@1.1.6
meteor-platform@1.2.2
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
mongo@1.1.0
observe-sequence@1.0.6
ordered-dict@1.0.3
package-version-parser@3.0.3
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
sanjo:long-running-child-process@1.1.1
sanjo:meteor-files-helpers@1.1.0_7
sanjo:meteor-version@1.0.0
session@1.1.0
spacebars@1.0.6
spacebars-compiler@1.0.6
templating@1.1.1
tracker@1.0.7
ui@1.0.6
underscore@1.0.3
url@1.0.4
velocity:chokidar@1.0.3_1
velocity:core@0.7.1
velocity:html-reporter@0.7.3
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
webapp@1.2.0
webapp-hashing@1.0.3
xolvio:cucumber@0.12.3

**Comment by frankapimenta** [comment]
just created a new project, added the velocity reporter and xolvio:cucumber packages. Samples tests do that error above.

**Comment by samhatoum** [comment]
Fixed in 0.13.3

**Comment by frankapimenta** [comment]
[xolvio:cucumber] Cucumber is running
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:62228/wd/hub
[chimp] Finished running async processes with errors
[chimp] run complete with errors [Error: Another Selenium process is already running]
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined ] ]
[chimp] Responding to /run request with:
undefined
[chimp] finished rerun
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers:
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Tue, 04 Aug 2015 16:49:29 GMT',
     connection: 'keep-alive' },
  data: null }
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] no child to interrupt
[chimp][selenium] interrupt called
[chimp][selenium] interrupt is not killing selenium because clean-selenium-server not set
[chimp] Finished interrupting processes

-- 

just repeated the process: create new app, add xolvio:cucumber and velocity. add samples tests. run.
