### ISSUE TITLE
Can I somehow see phantomjs console output?

### ISSUE THREAD

**Issue by bjarketrux** [xolvio/meteor-cucumber#178]
I have a bug in my code that is only shown in PhantomJS (test failing). Is there a way to see phanomjs' console output?

I tried VELOCITY_DEBUG=1 but I cannot see console.log() or throw "Error" in the meteor ourput or the cucumber.log file.

To clarify, I want output that normally would be output to the browsers console, i.e. if i use chrome instead of phantomjs i can see the error in the browser (with preserve log enabled).

Thanks

**Comment by samhatoum** [comment]
Try setting `WD_LOG=debug`

**Comment by bjarketrux** [comment]
Thanks Sam
I can now see exceptions, but not any `console.log()`, `console.error()` or `alert()` output, though.

For anyone interested, this is the command I ran:
```
CHIMP_OPTIONS='--browser=phantomjs' WD_LOG=debug VELOCITY_DEBUG=1 meteor --test
```

Exceptions are shown as:
```
[chimp][phantom.stdout] [ERROR - 2015-07-29T03:51:18.632Z] Session [10f955c0-35a5-11e5-bf79-93ab163cb51e] - page.onError - msg: <message>
```

Could this stackoverflow question be related?: http://stackoverflow.com/questions/18115888/phantomjs-not-returning-results/18131369#18131369

**Comment by samhatoum** [comment]
I think this might also help you:

http://webdriver.io/api/protocol/log.html

**Comment by bjarketrux** [comment]
Aaah of cause. It makes so much sense now that it works ;)
The testing framework is capturing the console output, so that you can test if the application outputs the correct logs (if you have such behavior). Therefore I need to make a test that asserts on (or just logs) any `console.log()` in the application.

In my application code:
```
if (Meteor.isClient) {
    console.log("message");
}
```

In my test:
```
this.client.log("browser").then(function(log) {
    console.log(JSON.stringify(log));
});
```

`log` here is an object, which has a `value` attribute. Looks like this:
```
{
    "sessionId":"3d04ad50-35a9-11e5-b1dc-c5b303a8ebf6",
    "status":0,
    "value":[{
        "level":"INFO",
        "message":"message (undefined:undefined)",
        "timestamp":1438143671317
    }]
}
```

A bit of work to do debugging, but it works.

**Comment by samhatoum** [comment]
awesome, definitely something I'll look into auto-delegating sometime
