### ISSUE TITLE
[feature-request] Raise errors when step def callbacks are called twice

### ISSUE THREAD

**Issue by nathanathan** [xolvio/meteor-cucumber#179]
When a step definition's callback is called twice strange things will happen and it can be very difficult to track down the problem. Detecting this type of error and throwing exceptions would be very helpful.

**Comment by samhatoum** [comment]
have you looked at using the promise syntax? should help here as it will tell you a promise has already been resolved (I think)

**Comment by samhatoum** [comment]
This is actually too hard! It's better to wait for our synchronous version of chimp (coming very soon) and you won't need callbacks or promises or returns.
