### ISSUE TITLE
Cheat Sheet

### ISSUE THREAD

**Issue by bjarketrux** [xolvio/meteor-cucumber#182]
I had some trouble combining all the technologies into tests. Seems that other people also has some difficulties, so I created a small cheat sheet we can reference until the full documentation is ready.

Please comment if something is wrong, or otherwise can be improved, changed, or added.
Cheers

Note: I'm using AngularJS with Meteor

# Cucumber Chimp Chai Webdriver Cheat Sheet
The following is a list of examples of how to do common tasks and assertions.

###### Assert that element exists in dom
```javascript
return this.client
    .waitForExist("selector")
    .should.eventually.be.true;
```

###### Assert that element is not in dom (removed)
Use `undefined` for second parameter to keep default wait timeout.

Third parameter negates the check.

```javascript
return this.client
    .waitForExist("selector", undefined, true)
    .should.eventually.be.true;
```

###### Assert on number of elements in dom
```javascript
return this.client
    .waitForExist("selector")
    .elements("selector")
    .should.eventually.have.property("value")
    .with.length.above(2);
    // or .with.length(2);
```

###### Assert that element has text value
```javascript
return this.client
    .waitForExist("selector")
    .getText("selector")
    .should.eventually.equal(message);
```

###### Assert that element has class
```javascript
return this.client
    .waitForExist("selector")
    .getAttribute("selector", "class")
    .should.eventually.contain("my-custom-class");
```

###### Click an element
```javascript
return this.client
    .waitForExist("selector")
    .click("selector");
```

###### Move to an element
```javascript
return this.client
    .waitForExist("selector")
    .moveToObject("selector");
```

###### Drag an element
```javascript
return this.client
    .waitForExist("selector")
    .moveToObject("selector", 0, 0)
    .buttonDown()
    .moveToObject("selector", 50, 5)
    .buttonUp();
```

###### Assert on an elements x position
```javascript
return this.client
    .waitForExist("selector")
    .getLocation("selector", "x") // Get x or y, if not specified, an object {x, y} is returned.
    .should.eventually.be.equal(50);
```

###### Two operations (on server and client):
Arguable this could be split into one Given (testData) and one When (navigating to "/").

```javascript
var testData = { value: 3 };
return Promise.all([
    this.server.call("setupData", testData),
    this.client.url(urlHelper.resolve(process.env.ROOT_URL, "/"));
]);
```

###### Execute custom action (in this case trigger mouseenter on an element
```javascript
return this.client
    .waitForExist("selector")
    .selectorExecute("selector", function(element) {
        $(element).trigger("mouseenter");
    });
```

#### Common errors:
If you get this...

> AssertionError: expected { state: 'pending' } to...

Then try to add .eventually, e.g. `.should.eventually.be...`

> Test is green even if the code under test is commented out/changed

Then make sure the test RETURNS the promise, e.g. `return this.client...`

**Comment by Sanjo** [comment]
Big thanks for this nice content. I've added it to our new https://velocity.readme.io website.

* https://velocity.readme.io/docs/cheat-sheet
* https://velocity.readme.io/docs/common-errors

**Comment by Sanjo** [comment]
If you want to add more content in the future, let me know. I can give you write access to readme.io directly.

**Comment by bjarketrux** [comment]
Thanks, I'll batch it together if I find more.
