### ISSUE TITLE
Rename label illusive -> elusive?

### ISSUE THREAD

**Issue by dandv** [xolvio/meteor-cucumber#185]
il·lu·sive
iˈlo͞osiv/
adjective/literary
deceptive; illusory.
"that illusive haven"

e·lu·sive
ēˈlo͞osiv/
adjective
difficult to find, catch, or achieve.
"success will become ever more elusive"

**Comment by samhatoum** [comment]
haha, made me laugh! Thanks :)

**Comment by dandv** [comment]
And now we have the most... unique label ever :)
