### ISSUE TITLE
Receiving a POST /session//url runtime error

### ISSUE THREAD

**Issue by rjakobsson** [xolvio/meteor-cucumber#187]
I'm getting this error on my laptop when running `meteor --test`.

```
W20150807-11:20:05.979(2)? (STDERR) cucumber: 1 tests failed
W20150807-11:20:05.979(2)? (STDERR) RuntimeError
W20150807-11:20:05.979(2)? (STDERR) POST /session//url
W20150807-11:20:05.979(2)? (STDERR) Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
```

Cucumber.log:

```
[chimp][cucumber] Closed with code 2
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
[chimp] Responding to /run request with:
{"name":"RuntimeError","message":"POST /session//url\nBuild info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'\nSystem info: host: 'Robins-MacBook-Air.local', ip: '10.103.3.21', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.6.0_65'\nDriver info: driver.version: unknown"}
[chimp] finished rerun
[xolvio:cucumber] Results from Chimp:
{ name: 'RuntimeError',
  message: 'POST /session//url\nBuild info: version: \'2.46.0\', revision: \'87c69e2\', time: \'2015-06-04 16:16:47\'\nSystem info: host: \'Robins-MacBook-Air.local\', ip: \'10.103.3.21\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.10.4\', java.version: \'1.6.0_65\'\nDriver info: driver.version: unknown' }
```

And I'm guessing that the weird thing here is: `Driver info: driver.version: unknown` ?

Here is my .versions: https://gist.github.com/rjakobsson/4a137317b88ada5879d3
It might be related to https://github.com/xolvio/meteor-cucumber/issues/128
It seems to be related to WebdriverIO and not xolvio:cucumber: https://groups.google.com/forum/#!topic/webdriverio/b7cFK-4Qwo4

**Comment by christian-bromann** [comment]
Your session wasn't initialised fully when calling the url command. How did you initialise the Selenium session?

**Comment by Sanjo** [comment]
> Your session wasn't initialised fully when calling the url command. How did you initialise the Selenium session?

This is done by chimp: https://github.com/xolvio/chimp/blob/v0.12.9/lib/cucumberjs/hooks.js#L71-L103

**Comment by rjakobsson** [comment]
Thanks for looking at this.
It seems to be something that is related to my machine (OS X), as my teammate is not having the same issue (Win 7) .

**Comment by Sanjo** [comment]
Have you tried to restart you machine? Maybe that gets rid of some floating processes.

**Comment by rjakobsson** [comment]
@Sanjo yes I have, unfortunately. I installed Velocity + dependencies in early 2015, could there be some weird conflict between that and now?

**Comment by rjakobsson** [comment]
Or permissions or something like that?

**Comment by Sanjo** [comment]
Very very unlikely.

**Comment by Sanjo** [comment]
You could also try the latest release candidate.

1. `meteor add xolvio:cucumber@0.14.0-rc.1`
2. `CHIMP_OPTIONS="--sync=false" meteor` to start your app (= set CHIMP_OPTIONS)

**Comment by rjakobsson** [comment]
Thank you @Sanjo ! The output was much more informative. Through that I could read that the process couldn't start Google Chrome. I've got Google Chrome on another hard drive (not under /Applications) which caused it to not find it. Now that I've moved it, it works. Thanks a lot!
