### ISSUE TITLE
How can you run tests without opening a second browser window?

### ISSUE THREAD

**Issue by Lepozepo** [xolvio/meteor-cucumber#189]
Hi, I bought your book! I can't wait for it to be complete. Is there any way to make tests run without opening a browser window for the mirror?

Thanks in advance

**Comment by mmazur122** [comment]
Try running meteor with variable SELENIUM_BROWSER=phantomjs. You could also export it with export SELENIUM_BROWSER=phantomjs so that you don't have to use this variable every time you run meteor in current shell.

**Comment by Lepozepo** [comment]
Sweet, thanks!

**Comment by aaronholla** [comment]
Thank you! This was very helpful. :+1:
