### ISSUE TITLE
Bad Chimp Response

### ISSUE THREAD

**Issue by charue808** [xolvio/meteor-cucumber#200]
Has this error been encountered yet?

Ran the very basic test from meteor testing manual and got this error in the log.
```
[xolvio:cucumber] Cucumber is running
Debug: internal, implementation, error 
    Error: Uncaught error: not found: java
    at Function.whichSync [as sync] (/home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/which/which.js:136:9)
    at Object.start (/home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/lib/start.js:45:27)
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/lib/selenium.js:138:14
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:708:13
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:49:16
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:263:32
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:40:16
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:705:17
    at Object._onImmediate (/home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:211:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
[xolvio:cucumber] Bad response from Chimp server. { [Error: failed [500] {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}] stack: [Getter] }
```

**Comment by charue808** [comment]
Ran VELOCITY_DEBUG

[velocity] adding velocity core
[xolvio:cucumber] Mirror server is initializing
[xolvio:cucumber] Starting Chimp
[xolvio:cucumber] Screenshots dir is /home/cgum/Projects/Personal/letterPress/tests/cucumber/.screenshots
[xolvio:cucumber] Starting Chimp with /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp [ '/home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp',
  '-r',
  '/home/cgum/Projects/Personal/letterPress/tests/cucumber/features',
  '--snippets',
  '--ddp=http://localhost:60391/',
  '--log=error',
  '--debug',
  '--screenshotsPath=/home/cgum/Projects/Personal/letterPress/tests/cucumber/.screenshots',
  '--tags=@dev',
  '--server',
  '--serverPort=8866' ] { cwd: '/home/cgum/Projects/Personal/letterPress/tests/cucumber',
  stdio: 'inherit',
  env: 
   { XDG_VTNR: '7',
     ORBIT_SOCKETDIR: '/tmp/orbit-cgum',
     XDG_SESSION_ID: 'c2',
     METEOR_SHELL_DIR: '/tmp/meteor-test-run16dcfwg/.meteor/local/shell',
     XDG_GREETER_DATA_DIR: '/var/lib/lightdm-data/cgum',
     SELINUX_INIT: 'YES',
     TERMINATOR_UUID: 'urn:uuid:9f0f5f2e-33d9-4f6d-bf7c-3a229fa08848',
     CLUTTER_IM_MODULE: 'xim',
     SAL_USE_VCLPLUGIN: 'gtk',
     SESSION: 'Lubuntu',
     GPG_AGENT_INFO: '/run/user/1000/keyring-pyMhry/gpg:0:1',
     MIRROR_PORT: '60391',
     XDG_MENU_PREFIX: 'lxde-',
     SHELL: '/bin/bash',
     TERM: 'xterm',
     IS_MIRROR: 'true',
     HOST: 'http://localhost:60391/',
     WINDOWID: '33554435',
     HANDSHAKE: 'true',
     GNOME_KEYRING_CONTROL: '/run/user/1000/keyring-pyMhry',
     UPSTART_SESSION: 'unix:abstract=/com/ubuntu/upstart-session/1000/1275',
     OLDPWD: '/home/cgum/.meteor/packages/velocity_meteor-tool/1.1.4_2/mt-os.linux.x86_32',
     MOBILE_DDP_URL: 'http://localhost:60391',
     USER: 'cgum',
     LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:',
     XDG_SESSION_PATH: '/org/freedesktop/DisplayManager/Session0',
     XDG_SEAT_PATH: '/org/freedesktop/DisplayManager/Seat0',
     SSH_AUTH_SOCK: '/run/user/1000/keyring-pyMhry/ssh',
     DEFAULTS_PATH: '/usr/share/gconf/Lubuntu.default.path',
     XDG_CONFIG_DIRS: '/etc/xdg/lubuntu:/etc/xdg/xdg-Lubuntu:/usr/share/upstart/xdg:/etc/xdg',
     DESKTOP_SESSION: 'Lubuntu',
     PATH: '/home/cgum/.meteor/packages/velocity_meteor-tool/.1.1.4_2.kotcfb++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin:/home/cgum/.meteor/packages/meteor-tool/.1.1.4.1krofzx++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games',
     QT_IM_MODULE: 'xim',
     METEOR_SETTINGS: '{}',
     PWD: '/home/cgum/Projects/Personal/letterPress',
     JOB: 'dbus',
     XMODIFIERS: '@im=ibus',
     PARENT_URL: 'http://localhost:3000/',
     MONGO_URL: 'mongodb://127.0.0.1:3001/meteor-cucumber',
     LANG: 'en_US.UTF-8',
     GNOME_KEYRING_PID: '1382',
     MANDATORY_PATH: '/usr/share/gconf/Lubuntu.mandatory.path',
     GDM_LANG: 'en_US',
     NODE_PATH: '',
     IM_CONFIG_PHASE: '1',
     NODE_ENV: 'development',
     GDMSESSION: 'Lubuntu',
     ROOT_URL: 'http://localhost:60391/',
     APP_ID: '17qemh715n7ivh1ejagnh',
     _LXSESSION_PID: '1410',
     SESSIONTYPE: 'lxsession',
     METEOR_PARENT_PID: '1889',
     SHLVL: '1',
     HOME: '/home/cgum',
     XDG_SEAT: 'seat0',
     LANGUAGE: 'en_US',
     XDG_CONFIG_HOME: '/home/cgum/.config',
     UPSTART_INSTANCE: '',
     VELOCITY_DEBUG: '1',
     METEOR_PRINT_ON_LISTEN: 'true',
     LOGNAME: 'cgum',
     UPSTART_EVENTS: 'started xsession',
     DBUS_SESSION_BUS_ADDRESS: 'unix:abstract=/tmp/dbus-Km8RqKUVK4',
     QT4_IM_MODULE: 'xim',
     XDG_DATA_DIRS: '/etc/xdg/lubuntu:/usr/local/share:/usr/share:/usr/share/gdm:/var/lib/menu-xdg:/usr/share/Lubuntu:/usr/local/share/:/usr/share/',
     LESSOPEN: '| /usr/bin/lesspipe %s',
     FRAMEWORK: 'cucumber',
     HTTP_FORWARDED_COUNT: '2',
     TEXTDOMAIN: 'im-config',
     UPSTART_JOB: 'lxsession',
     INSTANCE: '',
     PORT: '24771',
     MONGO_OPLOG_URL: 'mongodb://127.0.0.1:3001/local',
     DISPLAY: ':0',
     XDG_RUNTIME_DIR: '/run/user/1000',
     VELOCITY_MAIN_APP_PATH: '/home/cgum/Projects/Personal/letterPress',
     GTK_IM_MODULE: 'xim',
     XDG_CURRENT_DESKTOP: 'LXDE',
     ROOT_URL_PATH: '',
     LESSCLOSE: '/usr/bin/lesspipe %s %s',
     TEXTDOMAINDIR: '/usr/share/locale/',
     MOBILE_ROOT_URL: 'http://localhost:60391',
     XAUTHORITY: '/home/cgum/.Xauthority',
     COLORTERM: 'gnome-terminal' } }
[xolvio:cucumber] Chimp process forked with pid 1949
=> Started your app.

=> App running at: http://localhost:60391/
[velocity] Mirror started. Connecting via DDP to parent
[velocity] Mirror connected to parent. Registering mirror...
[velocity] Established connection with Velocity.
[chimp] Did not find package.json, not running npm install
[chimp] Chimp server is running on port 8866 http://localhost:60391/
[chimp] Handshaking with DDP server
[xolvio:cucumber] Received handshake from Chimp.
[xolvio:cucumber] Connecting to hub
[chimp] Handshake complete, closing DDP connection
[xolvio:cucumber] Connected to hub.
[xolvio:cucumber] Find and run triggered { '0': 
   { name: 'curate_a_landing_page.feature',
     absolutePath: '/home/cgum/Projects/Personal/letterPress/tests/cucumber/features/landing-page/curate_a_landing_page.feature',
     relativePath: 'tests/cucumber/features/landing-page/curate_a_landing_page.feature',
     targetFramework: 'cucumber',
     lastModified: 1440583360884,
     _id: '/home/cgum/Projects/Personal/letterPress/tests/cucumber/features/landing-page/curate_a_landing_page.feature' } }
[xolvio:cucumber] Running in batch-features mode.
[xolvio:cucumber] Cucumber is running
[chimp] interrupting
[chimp] no processes to interrupt
[chimp] rerunning
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed

[chimp][selenium] hub can be seen at http://localhost:36663/wd/hub
Debug: internal, implementation, error 
    Error: Uncaught error: not found: java
    at Function.whichSync [as sync] (/home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/which/which.js:136:9)
    at Object.start (/home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/lib/start.js:45:27)
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/lib/selenium.js:138:14
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:708:13
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:49:16
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:263:32
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:40:16
    at /home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:705:17
    at Object._onImmediate (/home/cgum/.meteor/packages/xolvio_cucumber/.0.13.8.1c7bvc++os+web.browser+web.cordova/npm/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:211:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
[xolvio:cucumber] Bad response from Chimp server. { [Error: failed [500] {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}] stack: [Getter] }
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] no child to interrupt
[chimp][selenium] interrupt called
[chimp][selenium] interrupt is not killing selenium because clean-selenium-server not set
[chimp] Finished interrupting processes

**Comment by samhatoum** [comment]
You need to install java
https://chimp.readme.io/docs/getting-started
