### ISSUE TITLE
Is "fsevents" required? It sometimes breaks my build on Modulus, not sure if it relates

### ISSUE THREAD

**Issue by rjakobsson** [xolvio/meteor-cucumber#202]
Hi, I'm sometimes getting broken builds on Modulus, which complains about "fsevents" not being supported by Linux (OS X specific package). I've found that fsevents is a dependency of this project and wonders if it's really required, or if there is some way to make it an optional/non requirement when on Linux?

**Comment by samhatoum** [comment]
Chimpjs uss Chokidar to do file-watching when chimp is used standalone. Chokidar has an [optional dep on fsevents](https://github.com/paulmillr/chokidar/blob/master/package.json#L41)

Chimp does work on linux though so this is odd. What flavor of linux is it?

**Comment by rjakobsson** [comment]
Modulus run applications on Ubuntu 14.04. Which makes this weird, right?

**Comment by rjakobsson** [comment]
I haven't seen this in a while. Closing it.
