### ISSUE TITLE
Cucumber failure but Jenkins still reports Success

### ISSUE THREAD

**Issue by philipobrien** [xolvio/meteor-cucumber#204]
I have noticed that despite Cucumber failing with errors [like this](https://github.com/meteor-velocity/velocity/issues/371#issue-103698954), Jenkins just carries on and reports the build was a success. 

![image](https://cloud.githubusercontent.com/assets/1763813/9550108/594d2f68-4da1-11e5-8efc-8dd0e9766662.png)

This is obviously a concern when aiming for continuous deployment. Any ideas?

**Comment by samhatoum** [comment]
could you check the exit code right after the FAILURE maybe?

**Comment by samhatoum** [comment]
Hi, I'm closing this due to lack of response. Please get in touch again and I'll reopen
