### ISSUE TITLE
unable to load google map

### ISSUE THREAD

**Issue by nicolsondsouza** [xolvio/meteor-cucumber#205]
Hi, I am unable to load google map, because google map loads another gmap file which is "https://maps.googleapis.com/maps-api-v3/api/js/22/2/main.js" but velocity tries to load this file himself and thus generates this error.

XMLHttpRequest cannot load https://maps.gstatic.com/maps-api-v3/api/js/22/2/main.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

browser-source-map-support.js:82

http://localhost:3000/packages/velocity:source-map-support/.npm/package/node_modules/source-map-support/browser-source-map-support.js

http://devdiggadog.meteor.com
This is the app without velocity,

If I don't have velocity test, gmap loads fine.
Any suggestion or help?
Thanks

**Comment by BradRyan** [comment]
I'm having the same issue.  Any luck?

**Comment by nicolsondsouza** [comment]
Nope there is no luck here, you need to stimulate the app without gmap.
That's how I solved the test.

**Comment by samhatoum** [comment]
are you only using meteor cucumber or also using mocha/jasmine?

**Comment by nicolsondsouza** [comment]
Mainly meteor cucumber, and a little bit of Jasmine test.

**Comment by BradRyan** [comment]
Just cucumber for me.

**Comment by BradRyan** [comment]
Just confirmed.  If I remove xolvio:cucumber then the error goes away.

**Comment by nicolsondsouza** [comment]
What I suspected was, it was browser- support. js which was loading gmap
file instead of gmap itself, that lead to cors error and doesn't load the
map.

**Comment by samhatoum** [comment]
Thanks @BradRyan and @nicolsondsouza 

If you could create a simple repro somewhere it would help me focus some time on it.

**Comment by BradRyan** [comment]
@samhatoum Yep I just reproduced it on the leaderboard app.  I'll share in a minute.

**Comment by BradRyan** [comment]
https://github.com/BradRyan/issue-205-meteor-cucumber-reproduction

**Comment by samhatoum** [comment]
Thank you much, that's useful. I'll test it with the next release and see if I can get you a solution

**Comment by BradRyan** [comment]
Thanks!

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#98
