### ISSUE TITLE
Cucumber integration still runs even when VELOCITY=='0'

### ISSUE THREAD

**Issue by cramhead** [xolvio/meteor-cucumber#21]
When I set the environment variable VELOCITY to 0 or '0' 
I get the `TypeError: Object #<Object> has no method 'getTestsPath'` from the xolvio_cumber package. 

Although, I think that it may be better to have meteor-velocity control the plugins via a standard interface, the work around for removing this specific error is to have meteor-cucumber check for the environment variable. I did a quick check and it does remove the error. 
Unfortunately, other parts of the testing framework do continue to function, i.e. the velocityOverlay still shows and other testing plugins, specifically mike:mocha, run.

I would be happy to contribute a PR, for the quick fix, but if the standard interface approach is preferred it seems like a more controlled roll out would be in order.

**Comment by samhatoum** [comment]
Thanks for reporting.

A PR would be very welcome. I'm a little slammed these days catching up from the holidays!
