### ISSUE TITLE
Errors with all webdriver.io parameters after new version Cucumber 0.14 and Meteor 1.2

### ISSUE THREAD

**Issue by mstamos** [xolvio/meteor-cucumber#211]
I wrote my test with cucumber before Meteor 1.2 and cucumber 0.14 and all was ok. My code looks like 

    (function () {
    'use strict';

    module.exports = function () {
        // Npm modules
        var url = require("url");

        this.Given(/^I am signed out$/, function () {
            return this.client.
                url(process.env.ROOT_URL).
                waitForExist(".container").
                waitForVisible(".container").
                waitForVisible("#login-sign-in-link").
                getText("#login-sign-in-link", function (error, text) {
                    return chai.expect(text).to.contain(signIn);
                });
        });
    })();

After I run the command meteor update and now have Meteor 1.2.1 and Cucumber 0.14 I receive from all my tests this error

    TypeError: Object #<Object> has no method 'waitForExist'
        at World.<anonymous> (features/authentication/authentication.js:27:17)

This happens with all webdreinve.io api parameters such as (setValue, getText etc).
My question is why does this happen? We have new way to read promises for client and server now?

**Comment by samhatoum** [comment]
Hi

There are breaking changes in 0.14.0. Webdriver is now synchronous! No more need for promises or callbacks. 

We already have a guide for chimp here https://chimp.readme.io/docs/migrate-to-synchronous-style

Also, the chai assertions are not default now, we are using Jasmine expect.

You can still use the old modes if you want, I will write a guide/migration doc today.

**Comment by mstamos** [comment]
Ok I got it @samhatoum ! Thank you for your help!
I rebuilt my open source [Microreact](https://github.com/mstamos/microreact) to the new changes if someone want to have an example for Meteor 1.2 and Cucumber 0.14
