### ISSUE TITLE
Is this project using Git Flow workflow like Velocity core?

### ISSUE THREAD

**Issue by rhyslbw** [xolvio/meteor-cucumber#212]
Currently there's no `develop` branch so I can only submit a PR against `master`. I want to patch the security issue where in debug mode [all env](https://github.com/xolvio/meteor-cucumber/blob/master/src/mirror-server.js#L257) vars are [logged](https://github.com/xolvio/meteor-cucumber/blob/master/src/mirror-server.js#L264).

**Comment by rhyslbw** [comment]
I've submitted #213 against `master`, but would be good to see a `develop` branch as the foundation for the next release

**Comment by samhatoum** [comment]
We were in the process of setting up continuous deployment - but that's not happened yet so I'll add gitflow until then

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#96
