### ISSUE TITLE
Show downloading progress for first time install

### ISSUE THREAD

**Issue by samhatoum** [xolvio/meteor-cucumber#215]
Currently the user does not see any output when cucumber is installed first time / upgraded and there is a long delay for installing dependencies

**Comment by bjarketrux** [comment]
+1 for some indication of progress. I just spend some time restarting stuff because I thought that there was something wrong with my setup. Turned out that there was a problem with the company network - really slow - so the test seemed to hang forever.

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#95
