### ISSUE TITLE
Automatically add missing steps reported in the console into a temporary steps file

### ISSUE THREAD

**Issue by samhatoum** [xolvio/meteor-cucumber#22]

**Comment by philipbeadle** [comment]
For the last few projects Ive been putting one step per file and naming the file the step name and it has made finding steps and organising all my steps much easier.  Fits in nicely with this enhancement.

**Comment by samhatoum** [comment]
Interesting. Are you sharing code/state between the steps? if so, how?

**Comment by philipbeadle** [comment]
Haven't had any need to share state between steps so far. I've done this on the last 3 AngularJS projects and it seems to work nicely.  Also make merging in Git much simpler.  There are 5 automation engineers on my current project, so merging can be an issue.

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#128
