### ISSUE TITLE
TypeError: Object true has no method 'getTitle'  at World (OSX)

### ISSUE THREAD

**Issue by whasting** [xolvio/meteor-cucumber#222]
Hi! I'm just getting started with automation. I've been messing around with cucumber the past few weeks, moved from a windows machine to a mac, and now I can't even get the cucumber sample tests to work. I've ran `npm install` within the cucumber directory as well. I keep getting the error: 

    W20151005-11:12:16.898(-7)? (STDERR) Then I should see the title "intentional failure"
    W20151005-11:12:16.899(-7)? (STDERR) undefined
    W20151005-11:12:16.899(-7)? (STDERR) TypeError: Object true has no method 'getTitle'  at World.<anonymous> (/tests/cucumber/features/step_definitions/sample_steps.js:28:9) 

Here is the code causing the issue:

    this.Then(/^I should see the title "([^"]*)"$/, function (expectedTitle) {
          // you can use chai-as-promised in step definitions also
          return this.client.
            waitForExist('title'). // WebdriverIO chain-able promise magic
            getTitle().should.become(expectedTitle);
        });

The debug log:

    => Started proxy.                             
    => Started MongoDB.                           
    I20151005-11:43:18.318(-7)? [velocity] adding velocity core
    I20151005-11:43:18.381(-7)? [velocity] Register framework jasmine-server-integration with regex ^tests/jasmine/server/integration/.+\.(js|es6|jsx|coffee|litcoffee|coffee\.md)$
    I20151005-11:43:18.381(-7)? [velocity] Velocity not started. Queueing func
    I20151005-11:43:18.381(-7)? [velocity] Register framework jasmine-client-integration with regex ^tests/jasmine/client/integration/.+\.(js|es6|jsx|coffee|litcoffee|coffee\.md)$
    I20151005-11:43:18.381(-7)? [velocity] Velocity not started. Queueing func
    I20151005-11:43:18.381(-7)? [velocity] Register framework jasmine-client-unit with regex ^tests/jasmine/client/unit/.+\.(js|coffee|litcoffee|coffee\.md)$
    I20151005-11:43:18.381(-7)? [velocity] Velocity not started. Queueing func
    I20151005-11:43:18.382(-7)? [velocity] Register framework jasmine-server-unit with regex ^tests/jasmine/server/unit/.+\.(js|coffee|litcoffee|coffee\.md)$
    I20151005-11:43:18.382(-7)? [velocity] Velocity not started. Queueing func
    I20151005-11:43:18.382(-7)? [xolvio:cucumber] Cucumber hub is loading
    I20151005-11:43:18.382(-7)? [velocity] Register framework cucumber with regex ^tests/cucumber/((?!node_modules/).)+\.(feature|js|coffee|litcoffee|coffee\.md)$
    I20151005-11:43:19.609(-7)? [velocity] 1 mirror(s) requested
    I20151005-11:43:19.614(-7)? [velocity] Server startup
    I20151005-11:43:19.634(-7)? [velocity] app dir /Users/xxxxxx/Documents/repositories/xxx-xxx/xxx
    I20151005-11:43:19.634(-7)? [velocity] config = {
    I20151005-11:43:19.634(-7)?   "jasmine-server-integration": {
    I20151005-11:43:19.634(-7)?     "regex": "^tests/jasmine/server/integration/.+\\.(js|es6|jsx|coffee|litcoffee|coffee\\.md)$",
    I20151005-11:43:19.634(-7)?     "name": "jasmine-server-integration",
    I20151005-11:43:19.634(-7)?     "_regexp": {}
    I20151005-11:43:19.634(-7)?   },
    I20151005-11:43:19.635(-7)?   "jasmine-client-integration": {
    I20151005-11:43:19.635(-7)?     "regex": "^tests/jasmine/client/integration/.+\\.(js|es6|jsx|coffee|litcoffee|coffee\\.md)$",
    I20151005-11:43:19.635(-7)?     "name": "jasmine-client-integration",
    I20151005-11:43:19.635(-7)?     "_regexp": {}
    I20151005-11:43:19.635(-7)?   },
    I20151005-11:43:19.635(-7)?   "jasmine-client-unit": {
    I20151005-11:43:19.635(-7)?     "regex": "^tests/jasmine/client/unit/.+\\.(js|coffee|litcoffee|coffee\\.md)$",
    I20151005-11:43:19.635(-7)?     "name": "jasmine-client-unit",
    I20151005-11:43:19.636(-7)?     "_regexp": {}
    I20151005-11:43:19.636(-7)?   },
    I20151005-11:43:19.636(-7)?   "jasmine-server-unit": {
    I20151005-11:43:19.636(-7)?     "regex": "^tests/jasmine/server/unit/.+\\.(js|coffee|litcoffee|coffee\\.md)$",
    I20151005-11:43:19.636(-7)?     "name": "jasmine-server-unit",
    I20151005-11:43:19.637(-7)?     "_regexp": {}
    I20151005-11:43:19.637(-7)?   },
    I20151005-11:43:19.637(-7)?   "cucumber": {
    I20151005-11:43:19.637(-7)?     "regex": "^tests/cucumber/((?!node_modules/).)+\\.(feature|js|coffee|litcoffee|coffee\\.md)$",
    I20151005-11:43:19.637(-7)?     "name": "cucumber",
    I20151005-11:43:19.637(-7)?     "_regexp": {}
    I20151005-11:43:19.638(-7)?   }
    I20151005-11:43:19.638(-7)? }
    I20151005-11:43:19.638(-7)? [velocity] resetting the world
    I20151005-11:43:19.638(-7)? [velocity] frameworks with disable auto reset: []
    I20151005-11:43:19.649(-7)? [velocity] Mirror process forked with pid 3423
    I20151005-11:43:19.649(-7)? [velocity] cucumber is starting a mirror at http://localhost:54785/.
    I20151005-11:43:19.660(-7)? [velocity] You can see the mirror logs at: tail -f /Users/xxxxxx/Documents/repositories/xxx-xxx/xxx/.meteor/local/log/cucumber.log
    I20151005-11:43:19.693(-7)? Kadira: completed instrumenting the app
    I20151005-11:43:19.729(-7)? Not migrating, already at version 7
    I20151005-11:43:19.731(-7)? [velocity] Add paths to watcher [ '/Users/xxxxxx/Documents/repositories/xxx-xxx/xxx/tests' ]
    W20151005-11:43:19.755(-7)? (STDERR) WARNING: Push APN is using development key and certificate
    I20151005-11:43:19.885(-7)? [velocity] Search framework for path tests/README.md
    I20151005-11:43:19.885(-7)? [velocity] No framework registered for tests/README.md
    => Started your app.

    => App running at: http://localhost:3000/
    I20151005-11:43:19.897(-7)? [velocity] Search framework for path tests/cucumber/package.json
    I20151005-11:43:19.897(-7)? [velocity] No framework registered for tests/cucumber/package.json
    I20151005-11:43:19.903(-7)? [velocity] Search framework for path tests/cucumber/features/sample.feature
    I20151005-11:43:19.903(-7)? [velocity] Target framework for tests/cucumber/features/sample.feature is cucumber
    I20151005-11:43:19.905(-7)? [velocity] Search framework for path tests/cucumber/fixtures/my_fixture.js
    I20151005-11:43:19.905(-7)? [velocity] Target framework for tests/cucumber/fixtures/my_fixture.js is cucumber
    I20151005-11:43:19.911(-7)? [velocity] Search framework for path tests/jasmine/client/integration/loginSpec.js
    I20151005-11:43:19.911(-7)? [velocity] Target framework for tests/jasmine/client/integration/loginSpec.js is jasmine-client-integration
    I20151005-11:43:19.914(-7)? [velocity] Search framework for path tests/jasmine/server/integration/userSpec.js
    I20151005-11:43:19.915(-7)? [velocity] Target framework for tests/jasmine/server/integration/userSpec.js is jasmine-server-integration
    I20151005-11:43:19.916(-7)? [velocity] Search framework for path tests/cucumber/features/step_definitions/sample_steps.js
    I20151005-11:43:19.916(-7)? [velocity] Target framework for tests/cucumber/features/step_definitions/sample_steps.js is cucumber
    I20151005-11:43:19.923(-7)? [velocity] Search framework for path tests/jasmine/client/unit/collection-helpers/collectionHelpersSpec.js
    I20151005-11:43:19.924(-7)? [velocity] Target framework for tests/jasmine/client/unit/collection-helpers/collectionHelpersSpec.js is jasmine-client-unit
    I20151005-11:43:19.925(-7)? [velocity] Search framework for path tests/jasmine/client/unit/models/xxxbotSpec.js
    I20151005-11:43:19.925(-7)? [velocity] Target framework for tests/jasmine/client/unit/models/xxxbotSpec.js is jasmine-client-unit
    I20151005-11:43:19.925(-7)? [velocity] Search framework for path tests/jasmine/client/unit/models/userSpec.js
    I20151005-11:43:19.926(-7)? [velocity] Target framework for tests/jasmine/client/unit/models/userSpec.js is jasmine-client-unit
    I20151005-11:43:19.927(-7)? [velocity] Search framework for path tests/jasmine/client/unit/subrouter/subrouterSpec.js
    I20151005-11:43:19.928(-7)? [velocity] Target framework for tests/jasmine/client/unit/subrouter/subrouterSpec.js is jasmine-client-unit
    I20151005-11:43:19.928(-7)? [velocity] Search framework for path tests/jasmine/client/unit/t/accountsSpec.js
    I20151005-11:43:19.928(-7)? [velocity] Target framework for tests/jasmine/client/unit/t/accountsSpec.js is jasmine-client-unit
    I20151005-11:43:19.931(-7)? [velocity] Search framework for path tests/jasmine/client/unit/t/commonHelpersSpec.js
    I20151005-11:43:19.931(-7)? [velocity] Target framework for tests/jasmine/client/unit/t/commonHelpersSpec.js is jasmine-client-unit
    I20151005-11:43:19.931(-7)? [velocity] Search framework for path tests/jasmine/client/unit/t/tSpec.js
    I20151005-11:43:19.931(-7)? [velocity] Target framework for tests/jasmine/client/unit/t/tSpec.js is jasmine-client-unit
    I20151005-11:43:19.940(-7)? [velocity] Search framework for path tests/jasmine/client/unit/xxx-inspector/notes/inspectorNotesSpec.js
    I20151005-11:43:19.940(-7)? [velocity] Target framework for tests/jasmine/client/unit/xxx-inspector/notes/inspectorNotesSpec.js is jasmine-client-unit
    I20151005-11:43:19.940(-7)? [velocity] File scan complete, now watching /tests
    I20151005-11:43:19.940(-7)? [velocity] Triggering queued startup functions
    I20151005-11:43:19.947(-7)? [sanjo:jasmine]: Starting mirror for jasmine-client-integration
    I20151005-11:43:19.948(-7)? [sanjo:jasmine]: Starting mirror for jasmine-server-integration
    I20151005-11:43:20.052(-7)? [velocity] 1 mirror(s) requested
    I20151005-11:43:20.064(-7)? [velocity] Mirror process forked with pid 3441
    I20151005-11:43:20.064(-7)? [velocity] jasmine-client-integration is starting a mirror at http://localhost:54786/.
    I20151005-11:43:20.067(-7)? [velocity] 1 mirror(s) requested
    I20151005-11:43:20.071(-7)? [velocity] Mirror process forked with pid 3442
    I20151005-11:43:20.071(-7)? [velocity] jasmine-server-integration is starting a mirror at http://localhost:54787/.
    I20151005-11:43:20.077(-7)? [velocity] You can see the mirror logs at: tail -f /Users/xxxxxx/Documents/repositories/xxx-xxx/xxx/.meteor/local/log/jasmine-client-integration.log
    I20151005-11:43:20.077(-7)? [velocity] You can see the mirror logs at: tail -f /Users/xxxxxx/Documents/repositories/xxx-xxx/xxx/.meteor/local/log/jasmine-server-integration.log
    I20151005-11:43:20.294(-7)? Kadira: successfully authenticated
    I20151005-11:44:41.463(-7)? jasmine-client-unit: 19 tests passed (135ms)
    I20151005-11:45:37.510(-7)? [velocity] Mirror registered. Handshaking with mirror... { framework: 'jasmine-server-integration',
    I20151005-11:45:37.510(-7)?   host: 'http://localhost:54787/',
    I20151005-11:45:37.510(-7)?   port: '54787' }
    I20151005-11:45:37.603(-7)? [velocity] Connected to mirror, setting state to ready { framework: 'jasmine-server-integration',
    I20151005-11:45:37.604(-7)?   host: 'http://localhost:54787/',
    I20151005-11:45:37.604(-7)?   port: '54787' }
    I20151005-11:45:37.617(-7)? [velocity] Parent Handshake response undefined undefined
    I20151005-11:45:38.169(-7)? jasmine-server-integration: 5 tests passed (553ms)
    I20151005-11:45:38.595(-7)? [velocity] Mirror registered. Handshaking with mirror... { framework: 'cucumber',
    I20151005-11:45:38.595(-7)?   host: 'http://localhost:54785/',
    I20151005-11:45:38.595(-7)?   port: '54785' }
    I20151005-11:45:38.629(-7)? [velocity] Connected to mirror, setting state to ready { framework: 'cucumber',
    I20151005-11:45:38.629(-7)?   host: 'http://localhost:54785/',
    I20151005-11:45:38.629(-7)?   port: '54785' }
    I20151005-11:45:38.665(-7)? [velocity] Parent Handshake response undefined undefined
    I20151005-11:45:39.804(-7)? [velocity] Mirror registered. Handshaking with mirror... { framework: 'jasmine-client-integration',
    I20151005-11:45:39.805(-7)?   host: 'http://localhost:54786/',
    I20151005-11:45:39.805(-7)?   port: '54786' }
    I20151005-11:45:39.827(-7)? [velocity] Connected to mirror, setting state to ready { framework: 'jasmine-client-integration',
    I20151005-11:45:39.828(-7)?   host: 'http://localhost:54786/',
    I20151005-11:45:39.828(-7)?   port: '54786' }
    I20151005-11:45:39.835(-7)? [velocity] Parent Handshake response undefined undefined
    I20151005-11:45:57.557(-7)? cucumber: 2 tests passed (4s)
    W20151005-11:45:57.557(-7)? (STDERR) cucumber: 1 tests failed
    W20151005-11:45:57.557(-7)? (STDERR) Then I should see the title "intentional failure"
    W20151005-11:45:57.557(-7)? (STDERR) undefined
    W20151005-11:45:57.557(-7)? (STDERR) TypeError: Object true has no method 'getTitle'
    W20151005-11:45:57.558(-7)? (STDERR)   at World.<anonymous> (/Users/xxxxxx/Documents/repositories/xxx-xxx/xxx/tests/cucumber/features/step_definitions/sample_steps.js:28:9)
    W20151005-11:45:57.558(-7)? (STDERR)   at /Users/xxxxxx/.meteor/packages/xolvio_cucumber/.0.14.6.10c35r7++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumber-wrapper.js:116:43
    W20151005-11:45:57.558(-7)? (STDERR) 
    I20151005-12:03:59.104(-7)? jasmine-client-integration: 5 tests passed (843ms)riggering queued startup functions

.meteor/local/log/cucumber.log

    => Using velocity:METEOR@1.2.0.2_1 as requested (overriding Meteor 1.2.0.2)

    => Started proxy.
    Kadira: completed instrumenting the app
    Kadira: successfully authenticated
    Migrating from version 0 -> 7
    Running up() on version 1

    => Started your app.

    => App running at: http://localhost:52750/
    [velocity] Established connection with Velocity.
    [xolvio:cucumber] Cucumber is running

    Feature: One-liner description of this feature

      As a [role]
      I want [feature]
      So that [benefit]

      The story above is to set context for the reader. It doesn't actually have any impact on the test itself. The phrases inside the scenarios are ties to test code using regex, which you can see in /tests/features/step_definitions/steps.js

      In this textual part of the file, you can include context about this feature, you can add links to external documents and whatever is needed to create the full specification.

    [36m@dev[0m
    Scenario: This scenario will run on both dev and CI   [2m[37m# features/sample.feature:20[0m
    [32mGiven I am a new user[0m                               [2m[37m# features/sample.feature:16[0m
    [32mWhen I navigate to "/"[0m                              [2m[37m# features/sample.feature:21[0m
    [31mThen I should see the title "intentional failure"[0m   [2m[37m# features/sample.feature:22[0m
    TypeError: Object true has no method 'getTitle'
    at World.<anonymous> (features/step_definitions/sample_steps.js:28:9)

    (::) failed steps (::)

    TypeError: Object true has no method 'getTitle'
      at World.<anonymous> (features/step_definitions/sample_steps.js:28:9)

    Failing scenarios:
    features/sample.feature:20 # Scenario: This scenario will run on both dev and CI

    1 scenario ([31m1 failed[0m)
    3 steps ([31m1 failed[0m, [32m2 passed[0m)

    [chimp] Finished running async processes with errors
    [chimp] run complete with errors Cucumber steps failed

.meteor/versions

    accounts-base@1.2.1
    accounts-google@1.0.6
    accounts-oauth@1.1.7
    accounts-password@1.1.3
    accounts-ui@1.1.6
    accounts-ui-unstyled@1.1.8
    aldeed:autoform@5.5.1
    aldeed:simple-schema@1.3.3
    amplify@1.0.0
    anti:i18n@0.4.3
    anti:modals@0.4.0
    arillo:flow-router-helpers@0.4.5
    aslagle:reactive-table@0.8.12
    autoupdate@1.2.3
    babel-compiler@5.8.24_1
    babel-runtime@0.1.4
    base64@1.0.4
    binary-heap@1.0.4
    blaze@2.1.3
    blaze-html-templates@1.0.1
    blaze-tools@1.0.4
    boilerplate-generator@1.0.4
    caching-compiler@1.0.0
    caching-html-compiler@1.0.2
    callback-hook@1.0.4
    check@1.0.6
    coffeescript@1.0.10
    cosmos:browserify@0.5.1
    crosswalk@1.3.1
    dburles:google-maps@1.1.4
    ddp@1.2.2
    ddp-client@1.2.1
    ddp-common@1.2.1
    ddp-rate-limiter@1.0.0
    ddp-server@1.2.1
    deps@1.0.9
    diff-sequence@1.0.1
    dispatch:kernel@0.0.6
    dispatch:request-animation-frame@0.0.1
    ecmascript@0.1.5
    ecmascript-collections@0.1.6
    edgee:slingshot@0.7.1
    ejson@1.0.7
    email@1.0.7
    fastclick@1.0.7
    fourseven:scss@3.2.0
    geojson-utils@1.0.4
    google@1.1.6
    ground:db@0.3.12
    ground:dictionary@0.2.1
    ground:localstorage@0.1.8
    ground:minimax@1.1.3
    ground:servertime@0.0.3
    ground:store@0.1.1
    ground:util@0.1.16
    hot-code-push@1.0.0
    html-tools@1.0.5
    htmljs@1.0.5
    http@1.1.1
    id-map@1.0.4
    jeremy:geocomplete@1.6.5_7
    jquery@1.11.4
    kadira:blaze-layout@2.1.0
    kadira:flow-router@2.3.0
    konecty:user-presence@1.2.6
    launch-screen@1.0.4
    lbee:moment-helpers@1.2.0
    less@2.5.0_3
    livedata@1.0.15
    localstorage@1.0.5
    logging@1.0.8
    markdown@1.0.5
    matteodem:easy-search@1.6.4
    mdg:camera@1.2.0
    meteor@1.1.9
    meteor-base@1.0.1
    meteor-platform@1.2.3
    meteorhacks:aggregate@1.2.1
    meteorhacks:collection-utils@1.2.0
    meteorhacks:kadira@2.23.4
    meteorhacks:kadira-debug@1.0.1
    meteorhacks:meteorx@1.3.1
    meteorhacks:ssr@2.1.2
    minifiers@1.1.7
    minimongo@1.0.10
    mizzao:timesync@0.3.3
    mizzao:user-status@0.6.5
    mobile-experience@1.0.1
    mobile-status-bar@1.0.6
    momentjs:moment@2.10.6
    mongo@1.1.2
    mongo-id@1.0.1
    mongo-livedata@1.0.9
    mrt:q@1.0.1
    natestrauser:animate-css@3.2.6
    nooitaf:colors@0.0.2
    npm-bcrypt@0.7.8_2
    npm-mongo@1.4.39_1
    oauth@1.1.6
    oauth2@1.1.5
    observe-sequence@1.0.7
    ordered-dict@1.0.4
    package-version-parser@3.0.4
    perak:markdown@1.0.5
    percolate:google-api@1.0.2
    percolate:migrations@0.8.6
    percolate:synced-cron@1.3.0
    practicalmeteor:chai@2.1.0_1
    practicalmeteor:loglevel@1.2.0_2
    promise@0.5.0
    qnub:emojione@0.0.3
    raix:eventemitter@0.1.3
    raix:eventstate@0.0.4
    raix:onetimeout@1.0.3
    raix:push@2.6.12
    raix:stubfence@1.0.2
    random@1.0.4
    rate-limit@1.0.0
    reactive-dict@1.1.2
    reactive-var@1.0.6
    reload@1.1.4
    retry@1.0.4
    reywood:publish-composite@1.4.2
    routepolicy@1.0.6
    ryanswapp:datetime-picker@0.0.1
    sanjo:jasmine@0.19.1
    sanjo:karma@1.7.0
    sanjo:long-running-child-process@1.1.3
    sanjo:meteor-files-helpers@1.1.0_7
    sanjo:meteor-version@1.0.0
    service-configuration@1.0.5
    session@1.1.1
    sha@1.0.4
    simple:json-routes@1.0.4
    spacebars@1.0.7
    spacebars-compiler@1.0.7
    splendido:accounts-emails-field@1.2.0
    splendido:accounts-meld@1.3.1
    srp@1.0.4
    standard-minifiers@1.0.1
    stevezhu:lodash@3.10.1
    templating@1.1.4
    templating-tools@1.0.0
    tmeasday:publish-counts@0.7.2
    tracker@1.0.9
    ui@1.0.8
    underscore@1.0.4
    url@1.0.5
    velocity:chokidar@1.2.0_1
    velocity:console-reporter@0.1.3
    velocity:core@0.10.2
    velocity:helpers@0.4.0
    velocity:html-reporter@0.9.0
    velocity:meteor-internals@1.1.0_7
    velocity:meteor-stubs@1.1.0
    velocity:shim@0.1.0
    velocity:source-map-support@0.3.2_1
    webapp@1.2.2
    webapp-hashing@1.0.5
    xolvio:cucumber@0.14.6
    zimme:active-route@2.3.2

.meteor/packages

    # Meteor packages used by this project, one per line.
    # Check this file (and the other files in this directory) into your repository.
    #
    # 'meteor add' and 'meteor remove' will edit this file for you,
    # but you can also edit it by hand.

    accounts-ui
    accounts-password
    reactive-var
    reywood:publish-composite
    stevezhu:lodash
    konecty:user-presence
    xxx:xxxbots
    reactive-dict
    fourseven:scss
    lbee:moment-helpers
    email
    zimme:active-route
    edgee:slingshot
    tmeasday:publish-counts
    xxx:subrouter
    mdg:camera
    natestrauser:animate-css
    ryanswapp:datetime-picker
    xxx:accounts-core
    raix:push
    mizzao:user-status
    percolate:migrations
    accounts-google
    service-configuration
    percolate:google-api
    splendido:accounts-meld
    momentjs:moment
    xxx:notifications
    jeremy:geocomplete
    qnub:emojione
    anti:modals
    xxx:common-helpers
    matteodem:easy-search
    aldeed:autoform
    aslagle:reactive-table
    fastclick
    meteorhacks:kadira
    percolate:synced-cron
    standard-minifiers
    meteor-base
    mobile-experience
    mongo
    blaze-html-templates
    session
    jquery
    tracker
    logging
    reload
    random
    ejson
    spacebars
    check
    xxx:core
    aldeed:simple-schema
    ground:db
    perak:markdown
    crosswalk
    velocity:console-reporter
    sanjo:jasmine@0.19.1
    velocity:html-reporter
    velocity:helpers
    xolvio:cucumber

**Comment by samhatoum** [comment]
Hi. I'm releasing an update for the sample tests shortly to fix that. In the meantime, please try:

```
client.waitForExist('title');
expect(client.getTitle()).toEqual(expectedTitle);
```

Basically the code is now synchronous!

**Comment by whasting** [comment]
Excellent, it's all cleared up. Thank you for your super quick response!

**Comment by samhatoum** [comment]
awesome!
