### ISSUE TITLE
tail -f logs giving a standard-minifiers version error

### ISSUE THREAD

**Issue by jpmoyn** [xolvio/meteor-cucumber#224]
I am trying to get cucumber to spit out some of the step definitions for a .feature file I made. My app is building fine in the regular logs, but in the tail -f cucumber logs I am getting a versions error. Here is the error:

```
=> Errors prevented startup:

   While selecting package versions:
   error: unknown package: isobuild:minifier-plugin
   Required by: standard-minifiers 1.0.0-rc.3

=> Your application has errors. Waiting for file change.
```

I have tried removing the version so it renews on build, but i still get this error once it builds. I have tried going back to Meteor 1.2, and 1.2.0.2. This error is not preventing my app from working, just the cucumber logs.

**Comment by mikepaszkiewicz** [comment]
Ran into this, seems like it was a package versioning issue, you should have no problem running on 1.2.0.2 after doing this...

I deleted the following from my .meteor/versions file AND did a meteor reset to remove any package version references.:
```
logging@1.0.8
minifiers@1.1.7
rate-limit@1.0.0
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
xolvio:cucumber@0.13.8
xolvio:cucumber@0.13.8
velocity:chokidar@1.0.3_1
velocity:core@0.9.3
velocity:html-reporter@0.9.0-rc.2
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
velocity:source-map-support@0.3.2_1
velocityjs:velocityjs@1.2.1
```

Got this back, seemed to be something with a few version patches and the version of Cucumber.
```
minifiers                    added, version 1.1.7
practicalmeteor:chai         added, version 1.9.2_3
practicalmeteor:loglevel     added, version 1.1.0_3
rate-limit                   added, version 1.0.0
velocity:chokidar            added, version 1.2.0_1
velocity:core                added, version 0.10.4
velocity:html-reporter       added, version 0.9.0
velocity:meteor-internals    added, version 1.1.0_7
velocity:shim                added, version 0.1.0
velocity:source-map-support  added, version 0.3.2_1
velocityjs:velocityjs        added, version 1.2.1
xolvio:cucumber              added, version 0.14.10
```
When logs start:
```
=> Using velocity:METEOR@1.2.0.2_1 as requested (overriding Meteor 1.2.0.2)
```
