### ISSUE TITLE
after upgrading screenshots are saved and in wrong location

### ISSUE THREAD

**Issue by SierraGolf** [xolvio/meteor-cucumber#226]
previous version: 0.8.9
new version: 0.14.6

after upgrading running ```meteor --test``` now saves screenshots in tests/cucumber. previously this did not save screenshots, only when running in "ci-mode".

currently I have to set SAVE_SCREENSHOTS=1 so that the screenshots are actually saved in the correct location (tests/cucumber/.screenshots) and regular .gitignore rules kick in.

**Comment by samhatoum** [comment]
We recently updated --test to also set VELOCITY_CI for Cucumber, it was a bug that it wasn't doing it before. Are you saying that the `.screenshots` dir is no longer being created in --test?

**Comment by SierraGolf** [comment]
I am saying that the screenshots are not saved in ```tests/cucumber/.screenshot``` dir if I do not set ```SAVE_SCREENSHOTS=1```. instead they are saved in ```tests/cucumber```

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#87
