### ISSUE TITLE
Feature Request: ES2015 for Step Definitions

### ISSUE THREAD

**Issue by workflow** [xolvio/meteor-cucumber#227]
Could you (perhaps optionally) include the `ecmascript` package?

**Comment by samhatoum** [comment]
Hey. The package won't work because chimp (and therefore cucumbers) run outside the meteor context in a separate node process.

I think it's a trivial add though, I will see about getting in the next version. Hopefully a week or so

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#86
