### ISSUE TITLE
Error process.env['chimp.ddp'] null

### ISSUE THREAD

**Issue by haunguyen90** [xolvio/meteor-cucumber#228]
![screen shot 2015-10-13 at 9 57 37 am](https://cloud.githubusercontent.com/assets/8245883/10444465/2030e634-7191-11e5-885c-3a03ddf92f09.png)
Can you please tell me how to fix it ? I cannot run cucumber in my project right now :(

**Comment by haunguyen90** [comment]
Cucumber error if start meteor with settings file 
@samhatoum Do you have any solution for that ?

**Comment by samhatoum** [comment]
Hi. Can you try this on a fresh project and just add xolvio:cucumber + a settings file?

**Comment by haunguyen90** [comment]
hm... so weird, it works with a fresh project but not works with my current project.
it missing process.env.HOST & process.env['chimp.db']

**Comment by samhatoum** [comment]
I would complicate your fresh project step by step with your current
project setup until you find the bug :)

**Comment by haunguyen90** [comment]
I removed everything from the setting file, and start the project with an empty setting file but it still error.

**Comment by samhatoum** [comment]
The fresh project with settings, did that work?

**Comment by haunguyen90** [comment]
The fresh project with settings, it works

**Comment by haunguyen90** [comment]
hm... i switched to version xolvio:cucumber@0.13.8 and remove the "public" in setting file, then it works for my current project. Do you have any idea ?

**Comment by samhatoum** [comment]
Are you saying that when you have `public` in the settings file that cucumber 0.14.x doesn't work? Let me know the steps to reproduce

**Comment by haunguyen90** [comment]
Yep, when i have `public` in the settings file then cucumber doesn't work

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#85
