### ISSUE TITLE
server logs do not appear in cucumber.log under certain conditions

### ISSUE THREAD

**Issue by SierraGolf** [xolvio/meteor-cucumber#229]
when a step causes a server side method to fail and that step or a following step fail, then the stack trace of the server error is not logged.

see this repo for a reproduction receipt: https://github.com/SierraGolf/velocity-log-bug. just run the sample.feature.

if you comment the second step the logs show the error, but if the step fails then they don't. this is actually quite common because usually something failing on the server will cause following steps to fail in most cases.

**Comment by SierraGolf** [comment]
the above repository does not reproduce the problem. so please ignore the repo for now. currently I can not reproduce the scenario. I will keep you updated when I manage to find a way how to reproduce.

**Comment by SierraGolf** [comment]
my fault, I had a before hook which was redirecting logs to in memory. doh!

**Comment by samhatoum** [comment]
Ha, thanks for posting. Hopefully it can help someone else
