### ISSUE TITLE
Parallel testing

### ISSUE THREAD

**Issue by alethes** [xolvio/meteor-cucumber#230]
I looked through the docs and older issues, but couldn't find any details regarding running test suites in parallel. I'm able to start multiple mirrors by setting the CUCUMBER_NODES environmental variable but, regardless of the value, only a single browser process is initiated.

**Comment by lgandecki** [comment]
I just tried and looks like it starts more for me.
Do you have multiple feature files? 
How do you know it starts only one browser?

This is how the log looks for me:

I20151020-13:01:34.857(-5)? [velocity] cucumber is starting a mirror at http://localhost:55187/.
I20151020-13:01:34.860(-5)? [velocity] cucumber is starting a mirror at http://localhost:55189/.
I20151020-13:01:34.862(-5)? [velocity] cucumber is starting a mirror at http://localhost:55188/.
I20151020-13:01:34.864(-5)? [velocity] You can see the mirror logs at: tail -f /Users/lukaszgandecki/webstorm/todos/.meteor/local/log/cucumber_55187.log
I20151020-13:01:34.868(-5)? [velocity] You can see the mirror logs at: tail -f /Users/lukaszgandecki/webstorm/todos/.meteor/local/log/cucumber_55189.log
I20151020-13:01:34.869(-5)? [velocity] You can see the mirror logs at: tail -f /Users/lukaszgandecki/webstorm/todos/.meteor/local/log/cucumber_55188.log


When I do CUCUMBER_NODES=3 meteor

**Comment by lgandecki** [comment]
Also, can you try with phantomjs?
export SELENIUM_BROWSER=phantomjs

Maybe it doesn't work properly for real browsers

**Comment by alethes** [comment]
Thank you for a prompt reply. I just tried with multiple feature files and it worked great. I use Chrome and it opened several windows. Previously, I thought the scenarios from a single file would be distributed between nodes.

**Comment by lgandecki** [comment]
Great to hear that! Thanks for checking.
We might make the scenarios run in parallel as well someday.. at this point, it's per feature :) This way you can also have one scenario depend on the state created by the previous one (although, Sam and Sanjo would probably tell you that you shouldn't.. but many people do it that way)

**Comment by samhatoum** [comment]
@lgandecki is right, don't do it! keep your scenarios independent :)
