### ISSUE TITLE
example code for meteor sign in?

### ISSUE THREAD

**Issue by ryw** [xolvio/meteor-cucumber#33]
Hi Sam — I'm ready to finally jump into velocity w/ cucumber — curious if you know of any sample meteor-cucumber code for an app with sign-in? I see https://github.com/meteor-velocity/velocity-examples/tree/master/leaderboard-cucumber/tests/cucumber/features and if that's the best starting point, I'll start there :)

**Comment by samhatoum** [comment]
Hey Ry!

Try https://github.com/xolvio/Letterpress/ for some examples

I also just created [fake-github](https://github.com/xolvio/meteor-github-fake) to allow login without an internet connection (for testing and local development).

Keep an eye on Letterpress over the next few hours/2 days. I'm writing tests as we speak to go in there that demonstrate the use of fixtures, auth and other things.

Glad to have you use this :)

**Comment by samhatoum** [comment]
Here you go

https://github.com/xolvio/Letterpress/blob/master/tests/cucumber/features/step_definitions/chapters.js#L23
