### ISSUE TITLE
Make velocity:html-reporter optional

### ISSUE THREAD

**Issue by djhi** [xolvio/meteor-cucumber#36]
One shouldn't be forced to use this as there are other options:
https://atmospherejs.com/pstuart2/velocity-notify

Thanks for this great package :)

**Comment by samhatoum** [comment]
Thanks for showing me that, I never knew it existed! 

The easiest solution is to create a new package called:

`xolvio:cucumber-core` which does not depend on the html-reporter, and the current `meteor-cucumber` will depend on both the core and the reporter. You can then install the core with the reporter of your choice.

Sound good?

**Comment by djhi** [comment]
Perfect :+1:

Thanks!

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#123
