### ISSUE TITLE
Error: Meteor code must always run within a Fiber in step definitions and hooks

### ISSUE THREAD

**Issue by jimmiebtlr** [xolvio/meteor-cucumber#40]
I've tried wrapping several parts such as

    var callback = Meteor.bindEnvironment(next);

By the stack trace it appears to be that line causing the error, but also it is Meteor.call if that get's called first.

and have checked https://github.com/meteor-velocity/velocity-examples as well as https://github.com/xolvio/Letterpress. 

The error it's giving me is 
    
    Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

Chasing my tail on this one, any help is appreciated.

**Comment by samhatoum** [comment]
Can you show me the code you're using?

**Comment by jimmiebtlr** [comment]
If I add the following to the before hook

      var boundCallback = function () {
        world.browser.
          init().
          setViewportSize({
            width: 1280,
            height: 1024
          }).
          timeoutsImplicitWait(1000).
          call( function(){} );//Meteor.bindEnvironment(next) );
      };
      var connection = DDP.connect(helper.world.mirrorUrl);
      connection.call('clearState', boundCallback);

then I get the error, specifically the last art of the code referenced in the stack trace is the `var connection = DDP.connect(helper.world.mirrorUrl);` line.

**Comment by samhatoum** [comment]
```javascript
    this.Before(function () {

      var world = helper.world;
      var next = arguments[arguments.length - 1];

      var boundCallback = function () {
        world.browser.
          init().
          setViewportSize({
            width: 1280,
            height: 1024
          }).
          timeoutsImplicitWait(1000).
          call(next);
      };

      var connection = DDP.connect(helper.world.mirrorUrl);
      connection.call('clearState', boundCallback);

    });
```

I just tested this code and it worked with the previous version of Meteor. Looks like the latest update to `1.0.3.1` has broken the bindings. I'll look at this and report back

**Comment by samhatoum** [comment]
I suggest downgrading temporarily to keep progressing

**Comment by samhatoum** [comment]
Ok, another workaround that will work in the latest Meteor is this:

```javascript
    this.Before(Meteor.bindEnvironment(function () {

      var world = helper.world;
      var next = arguments[arguments.length - 1];

      var boundCallback = function () {
        world.browser.
          init().
          setViewportSize({
            width: 1280,
            height: 1024
          }).
          timeoutsImplicitWait(1000).
          call(next);
      };

      var connection = DDP.connect(helper.world.mirrorUrl);
      connection.call('clearState', boundCallback);

    }));
```

Notice the bindEnvironment at the before callback. This is something that xolvio:cucumber does automatically (here) but that seems to be broken. You may need to apply the same fix for other places you see this error (like step definitions), until I fix this issue.

**Comment by jimmiebtlr** [comment]
Awesome, thanks for the great work.

**Comment by jimmiebtlr** [comment]
I'm not sure if it's the meteor version.  If I clone Letterpress, then upgrade only cucumber to `0.3.8` and webdriver to `0.2.2` I get the same error.  The meteor version stays at `METEOR@1.0.2.1`.  That being said I also tried downgrading cucumber all the way to `0.3.0` which also didn't seem to have an effect.

Using bindEnvironment before and the other functions does seem to work though.

**Comment by jimmiebtlr** [comment]
With the most recent version, I no longer get the last error mentioned.

Wrapping functions in bindEnvironment seems to work, thanks for everything.

**Comment by samhatoum** [comment]
Thanks for reporting back. I'm going to keep this open so I can fix the auto binds :)

**Comment by samhatoum** [comment]
You no longer need to this manually in 0.3.10

**Comment by sunkay** [comment]
0.3.10 throws this exception:
Exception in callback of async function: TypeError: object is not a function
 at /Users/sunil/meteor/meteor-boiler/tests/cucumber/features/support/hooks.js:45:7
 at runWithEnvironment (/Users/sunil/meteor/meteor-boiler/.meteor/local/build/programs/server/packages/meteor.js:1052:24)

My before hook is fairly simple. This exception happens at callback().

My before hook:

    this.Before("@beforeHookLogin", function(callback){
      console.log("start @beforeHookLogin");
      //always signout before sigingin in
      helper.world.browser.
        url(helper.world.cucumber.mirror.rootUrl).
        waitForExist('#at-nav-button').
        waitForVisible('#at-nav-button').
        click('#at-nav-button');


      // make sure the user is Authenticated
      helper.world.browser.
        url(helper.world.cucumber.mirror.rootUrl+"sign-in").
        waitForExist('.at-pwd-form').
        waitForVisible('.at-pwd-form').
        setValue('#at-field-email', 'sunil@y.com').
        setValue('#at-field-password', 'sunil123').
        click('#at-btn');
        
      console.log("End @beforeHookLogin");

      callback();
    });
