### ISSUE TITLE
show line in feature that failed

### ISSUE THREAD

**Issue by hexsprite** [xolvio/meteor-cucumber#41]
Right now it appears to be showing only which scenario failed rather than which specific line in the feature file.

Unless I am missing something?

**Comment by hexsprite** [comment]
```
I20150218-18:11:54.153(-8)? AssertionError: 0 is not equal to 1 (expected)
I20150218-18:11:54.154(-8)?   at WebdriverIO.<anonymous> (/Users/jbb/co/myproject/tests/cucumber/features/steps.coffee:53:7)
I20150218-18:11:54.154(-8)?   at WebdriverIO.<anonymous> (/Users/jbb/.meteor/packages/xolvio_webdriver/.0.2.1.1pcjgg6++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/utils/PromiseHandler.js:146:26)
```

What I'm expecting is to see the line in my .feature file where the failure occured.

Right now at the end of the run I see:

```
Failing scenarios:
I20150218-18:11:54.155(-8)? /Users/jbb/co/myproject/tests/cucumber/features/login.feature:6 # Scenario: Login & Logout
I20150218-18:11:54.155(-8)? /Users/jbb/co/myproject/tests/cucumber/features/usercount.feature:6 # Scenario: Open homepage
```

But that only tells me what line the scenario starts on not which specific line of the feature it died on...

**Comment by samhatoum** [comment]
I'll try!

**Comment by hexsprite** [comment]
I've figured out that I can see the line of the feature that failed if I change the output mode to 'pretty' from 'progress'

Having some way to specify that would be great.  Also I found out there's a flag in cucumber-js to output the snippets at coffee.

So some kind of way of specifying these preferences would be awesome.  not sure if it should be an env variable or a preferences file somewhere....

**Comment by samhatoum** [comment]
we've been talking about a VelocityConfig collection for this sorta stuff. I'd be happy for you to make this check an env var as a solution if you fancy doing a PR!

**Comment by samhatoum** [comment]
I have a way to do this. Will be in the rewrite coming up this week

**Comment by samhatoum** [comment]
Can you please try with `meteor add xolvio:cucumber@0.6.0-rc.7` please? Please be sure to see the [breaking changes](https://github.com/xolvio/meteor-cucumber#breaking-changes) section.

**Comment by samhatoum** [comment]
this now works
