### ISSUE TITLE
Helper functions in world

### ISSUE THREAD

**Issue by wackazong** [xolvio/meteor-cucumber#42]
How would I define a helper function in world, e.g. to go to "/"? I tried 

```
      helper.world.visitHome = function () {
        helper.world.browser.url(helper.world.cucumber.mirror.rootUrl);
      };
```

in this.World = function (next) {} but that would not work.

**Comment by Sanjo** [comment]
It's `Package['xolvio:cucumber'].cucumber.mirror.rootUrl`.

**Comment by wackazong** [comment]
Great, thanks.
