### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mltucker** [xolvio/meteor-cucumber#43]
Hi.  I installed via:

```
meteor add xolvio:cucumber
```

But I always see:

```
I20150219-18:47:51.639(1)? [xolvio:cucumber] Cucumber is running
I20150219-18:47:52.043(1)? F---.
I20150219-18:47:52.044(1)? 
I20150219-18:47:52.044(1)? (::) failed steps (::)
I20150219-18:47:52.044(1)? 
I20150219-18:47:52.044(1)? RuntimeError: RuntimeError
I20150219-18:47:52.044(1)?      (ECONNREFUSED:-1) Couldn't connect to selenium server
I20150219-18:47:52.044(1)?      Problem: Couldn't connect to selenium server
I20150219-18:47:52.045(1)? 
I20150219-18:47:52.045(1)?      Callstack:
I20150219-18:47:52.045(1)?      -> init()
```

I'm on Linux.  Is there anything else I need to install?  I tried installing phantomjs and selenium-webdriver, but it didn't help.

Thanks!

**Comment by samhatoum** [comment]
Hey

There's currently an issue with phantomjs on linux machines. Could you try this:

```
PHANTOM_PATH=`which phantomjs` meteor
```

**Comment by Sanjo** [comment]
For some reason Meteor treats the phantomjs NPM package not as architecture dependant. :-/

**Comment by mltucker** [comment]
@samhatoum Thanks for the suggestion.  No luck, unfortunately!

**Comment by samhatoum** [comment]
can you try to start phantom manually with:

`phantomjs --webdriver 4444` and then start meteor. This is not a long term solution, I'm trying to debug the issue so I'm interested in the output

**Comment by samhatoum** [comment]
any luck?

**Comment by mltucker** [comment]
@samhatoum Thanks a lot for following up.  The weird thing is that regardless of whether phantomjs is running, velocity just "hangs".  It says 0 tests passed in 0ms, and then in the cucumber section it shows a blue dot and says Loading.  There's nothing in the Logs section, and there are 4 files in the Test files section with cucumber as the Target Framework (I added the sample tests).  I can't reproduce the error message from 5 days ago.

![2015-02-24-214704_672x735_scrot](https://cloud.githubusercontent.com/assets/312430/6358824/c01754ae-bc6e-11e4-8cb3-3275f084ceab.png)

![2015-02-24-214838_585x210_scrot](https://cloud.githubusercontent.com/assets/312430/6358850/e7b6073a-bc6e-11e4-8531-c7e322305b62.png)

**Comment by mltucker** [comment]
Today I could reproduce the error from my first post.  As far as I know, nothing changed other than killing meteor, developing on another app, and then returning.  Running phantom manually as you suggested fixed the issue!

This is all the output:

```
$ phantomjs --webdriver 4444
PhantomJS is launching GhostDriver...
[INFO  - 2015-02-25T19:52:26.042Z] GhostDriver - Main - running on port 4444
[INFO  - 2015-02-25T19:53:15.388Z] Session [efe14690-bd27-11e4-be2a-cddc5cead9a8] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2015-02-25T19:53:15.389Z] Session [efe14690-bd27-11e4-be2a-cddc5cead9a8] - page.customHeaders:  - {}
[INFO  - 2015-02-25T19:53:15.389Z] Session [efe14690-bd27-11e4-be2a-cddc5cead9a8] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-02-25T19:53:15.389Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: efe14690-bd27-11e4-be2a-cddc5cead9a8
```

The intentional failure test fails as expected.

**Comment by samhatoum** [comment]
This error should be fixed. Please reopen if there are still issues
