### ISSUE TITLE
Additional files in support not reloaded

### ISSUE THREAD

**Issue by wackazong** [xolvio/meteor-cucumber#45]
I have a factory.js in my support folder for generating test data. This file is not reloaded when it changes, it seems. Cucumber is rerun, but the new version of the file is not loaded.

**Comment by samhatoum** [comment]
does it get picked up if you restart meteor?

**Comment by wackazong** [comment]
Yes.

**Comment by samhatoum** [comment]
Noted! Thanks, I'll look into it

**Comment by samhatoum** [comment]
Can you please retest this, should be fixed

**Comment by wackazong** [comment]
Works for me as well. Thanks.
