### ISSUE TITLE
How do i check for logged in status?

### ISSUE THREAD

**Issue by jakobloekke** [xolvio/meteor-cucumber#49]
How do I check for user's log in status?
I can only find examples that check for side effects of the user being logged in (i.e. menu or certain buttons being visible).
That seems wrong to me, since the Meteor object is available in the browser and exposes a method to give me the precise information.
I've tried this:

    this.Given(/^I am not logged in$/, function (callback) {
        assert(Meteor.user() === null);
        callback();
    });

It yields an error:

    Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

Then I try:

    this.Given(/^I am not logged in$/, Meteor.bindEnvironment(function (callback) {
        assert(Meteor.user() === null);
        callback();
    }));

Which gives me:

    Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.

I know my approach is rather naïve and it obviously doesn't work. 
I'm just not sure I understand why?

**Comment by djhi** [comment]
The way I do it in coffeescript:

Register a [command](http://webdriver.io/guide/usage/customcommands.html) in your world file (check [meteortesting](http://www.meteortesting.com/chapter/letterpress1) for this if you don't know what it is yet):
```
world.wdio.getGhostDriver options, (browser) ->
  world.browser = browser

  browser.addCommand "getMeteorUser", ->
    callback = arguments[arguments.length - 1]
    @execute Meteor.user, callback
```

Then in your tests:
```
helper.world.browser
  .getMeteorUser (error, result) ->
    assert !error, error
    assert.equal result.value
```

Here, `result.value` should be the user object so you can test for emails, etc.

**Comment by samhatoum** [comment]
Thank you @djhi  for answering this! 

@jakobloekke The approach used here is the correct one as it executes a command in the browser. You can read more about execute here:

http://webdriver.io/api/protocol/execute.html

The reason your code didn't work is because the cucumber code runs on the server and not in the client.

**Comment by djhi** [comment]
My pleasure, I struggled with this too :)

Le Tue Feb 24 2015 at 8:24:50 PM, Sam Hatoum <notifications@github.com> a
écrit :

**Comment by djhi** [comment]
With better formatting...
Haven't been able to pass arguments correctly, so I used this dirty string

```
  browser.addCommand "authenticateUser", (email, password) ->
    callback = arguments[arguments.length - 1]
    @execute "Meteor.loginWithPassword('#{email}', '#{password}')", callback
```

**Comment by samhatoum** [comment]
Try this for passing params:

```javascript
browser.addCommand('authenticateUser', function (email, password) {
  this.execute(function (eml, pwd) {
    Meteor.loginWithPassword(eml, pwd);
  }, email, password);
});
```

```coffee
browser.addCommand 'authenticateUser', (email, password) ->
  @execute ((eml, pwd) ->
    Meteor.loginWithPassword eml, pwd
  ), email, password
```

You should also be aware that `Meteor.loginWithPassword` is async and you ought to use this instead:

```javascript
browser.addCommand('authenticateUser', function (email, password) {
  this.executeAsync(function (eml, pwd, done) {
    Meteor.loginWithPassword(eml, pwd, done);
  }, email, password, callback);
}, callback);
```

```coffee
browser.addCommand 'authenticateUser', ((email, password) ->
  @executeAsync ((eml, pwd, done) ->
    Meteor.loginWithPassword eml, pwd, done
  ), email, password, callback
), callback
```

All of the above code is untested so let me know!

**Comment by jakobloekke** [comment]
Marvellous!
Thank you so much!

**Comment by djhi** [comment]
Yes Sam, that's how I did it at first without success. But that was with
phantom driver which causes many prbs: chrome driver works better, I'll
retry with it.

**Comment by samhatoum** [comment]
Check how I do it here:

https://github.com/xolvio/meteor-webdriver/blob/master/server.js#L80

**Comment by coniel** [comment]
Hello, I tried something like this (based on the world file from meteortesting):
```javascript
module.exports = function () {

    var helper = this;

    this.World = function (callback) {
        var world = helper.world = this;
        // set the app URL
        world.mirrorUrl = Package['xolvio:cucumber'].cucumber.mirror.rootUrl;

        Package['xolvio:webdriver'].wdio.getGhostDriver(function (browser) {
            world.browser = browser;

            browser.addCommand('authenticateUser', function (email, password) {
                this.executeAsync(function (eml, pwd, done) {
                    Meteor.loginWithPassword(eml, pwd, done);
                }, email, password, callback);

            }, callback);

            browser.call(callback);
        });
    };
};
```

but I'm getting the following error (which for some reason is repeated in an infinite loop):

```
I20150324-18:58:10.706(2)? Saved screenshot to /Users/oscarconiel1/Sites/coniel/webdriver_error.png
I20150324-18:58:10.756(2)? .[18:58:10]:  ERROR	UnknownError	An unknown server-side error occurred while processing the command.
I20150324-18:58:10.756(2)? 			{"errorMessage":"Can't find variable: Meteor","request":{"headers":{"Accept":"application/json","Connection":"keep-alive","Content-Length":"191","Content-Type":"application/json; charset=UTF-8","User-Agent":"webdriverio/webdriverio/2.4.5","host":"127.0.0.1:4444"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"return (function (eml, pwd, done) {\\n                    Meteor.loginWithPassword(eml, pwd, done);\\n                }).apply(null, arguments);\",\"args\":[\"test@test.com\",\"password\"]}","url":"/execute_async","urlParsed":{"anchor":"","query":"","file":"execute_async","directory":"/","path":"/execute_async","relative":"/execute_async","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute_async","queryKey":{},"chunks":["execute_async"]},"urlOriginal":"/session/f1624350-d246-11e4-91da-efbfc0cb90cb/execute_async"}}
W20150324-18:58:10.756(2)? (STDERR) Can't find variable: Meteor
```

Am I doing something wrong?

**Comment by samhatoum** [comment]
Are you calling the command before navigating to a page?

**Comment by djhi** [comment]
I made a gist with a few commands I use. Hope it helps !

https://gist.github.com/34954aea71e9596909fd.git

**Comment by trance4mation** [comment]
Thanks for commands @djhi , they would be really helpful, but using them always ended with this error:
```
RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: Can't find variable: Meteor
     Callstack:
     -> executeAsync([Function])
     -> logout()
```

**Comment by djhi** [comment]
Same prb here @trance4mation. It was working before

**Comment by samhatoum** [comment]
Hey @djhi, are you navigating to the right place first?

Could you please share some code

**Comment by ndarilek** [comment]
Stumped by this too. As of now I'm doing all logging in/out via interactions with my app, so I'm trying to forgo the complexity of creating commands. I just want to check if Meteor.userId() isn't null, at which point I assume I'm logged in. This fails for me, not sure if I'm doing it wrong or if there's an error in my fixtures, though I don't think there should be:

  this.Then("I should be logged in", function(callback) {
    this.client.
      pause(300).
      execute("Meteor.userId()", function(err, res) {
        assert(res.value).should.not.be(null).and.notify(callback)
      })      
  })

Assertion fails because userId() is null. I am able to connect to the mirror server and log in, and I think my steps that fill out the form should be correct. If nothing appears wrong with my code then I'll investigate my own steps a bit closer. Seems like there might be room for a few helper functions in this package to perform basic logged-in checks and such.

Thanks!

**Comment by lgandecki** [comment]
just a thought, I never tried to do execute with a string instead of a function, but - could you try

 execute("return Meteor.userId()" ?

**Comment by ndarilek** [comment]
Still no luck. :(

**Comment by lgandecki** [comment]
could you check if anything comes back in the err argument? Also, as Sam asked before - Do you navigate to right place first? 

Another thing - it might be a good practice to do as little execute calls as possible - for example, if login in adds the name of the logged in user in the top bar, you might wanna waitFor that element with your name/email, the same way your user would interact with the page (and checked if he is logged in).

**Comment by ndarilek** [comment]
err is null. I suppose I could do that, but I'd really rather test
authentication separate from the UI. I tend to use the same basic auth
code across apps, so if I can keep the same auth features and steps
defined separately from the UI then I'd very much rather do that.

Also, yes, the whole scenario is:

  @dev
  Scenario: Logging in
    Given I am a new user
    When I navigate to "/"
    And I fill in "#at-field-email" with "user@user.com"
    And I fill in "#at-field-password" with "password"
    And I click "#at-btn"
    Then I should be logged in

**Comment by ndarilek** [comment]
OK, this gets a bit more interesting. I now have something like:

  Scenario: Logging in
    Given I am a new user
    When I navigate to "/"
    And I submit valid credentials
    Then I should be logged in

  this.When(/^I navigate to "([^"]*)"$/, function (relativePath, callback) {
    this.client.
      url(url.resolve(process.env.ROOT_URL, relativePath)).
      waitForVisible("body *").
      call(callback)
  })

  this.Then("I submit valid credentials", function(callback) {
    this.client.
      setValue("#at-field-email", "user@user.com").
      setValue("#at-field-password", "password").
      submitForm("#at-pwd-form").
      waitForVisible("\#at-pwd-form", 100000, true).
      call(callback)
  })

The waitForVisible times out.

When I access the mirror and log in with the credentials I set up in my
fixture, I.e.:

Meteor.methods({
  reset: function() {
    Meteor.users.remove({})
    Accounts.createUser({email: "user@user.com", password: "password"})
  }
})

I can log in, and don't even see at-pwd-form in the DOM at all.

Thoughts on how to debug this further? Since I'm basically following
these steps manually and getting different results, I'm not sure what to
try next.

**Comment by samhatoum** [comment]
try to take a screenshot before the timeout, or you can try to use `SELENIUM_BROWSER=chrome meteor`

This may be that phantomjs is not compatible with your page

**Comment by samhatoum** [comment]
also, can we keep this issue closed please and open a new one? Thanks :)

**Comment by ndarilek** [comment]
I hope you don't mind me replying once more to state that I've fixed
this. This issue was the first Google result when I searched for my
problem, so maybe leaving this here will help someone else who is
struggling. Not heavily tested but I think it's a start.

The key was waitForExist, not waitForVisible. Here is my current step
definition:

  this.Then("I submit valid credentials", function(callback) {
    this.client.
      setValue("#at-field-email", "user@user.com").
      setValue("#at-field-password", "password").
      submitForm("#at-pwd-form").
      waitForExist("#at-pwd-form", 1000, true).
      call(callback)
  })

  this.Then("I should be logged in", function(callback) {
    this.client.
      execute("return Meteor.userId()", function(err, res) {
        assert.notEqual(res.value, null)
        callback()
      })     
  })

There may be a timing issue still, and a few other problems to work out,
but this finally gets my tests passing.

Thanks, will stop adding more to this issue, just wanted to help
potential Googlers. :)

**Comment by samhatoum** [comment]
Thank you much for reporting back!

**Comment by abecks** [comment]
I got here via Google too, and the above example does not work for me.

This is working however:
```
  this.Then(/^I should be logged in$/, function(callback) {
    this.client.
      execute("return Meteor.userId()")
      .then(function(res){
        assert.notEqual(res.value, null);
        callback();
      });
  });
```

However, if the assert fails it does not trigger a failure properly. See #192
