### ISSUE TITLE
Cucumber disrupting Jasmine server integration coffeescript specs

### ISSUE THREAD

**Issue by adeubank** [xolvio/meteor-cucumber#52]
Disclaimer: This is a strange one. Not sure if this is the right repo. 

https://dl.dropboxusercontent.com/u/29394761/leaderboard-jasmine.zip

Above is a link to the jasmine leaderboard example with the coffeescript package added and the sample jasmine server integration spec in coffeescript. The server fails to start with the `xolvio:cucumber` package included before `sanjo:jasmine` package in the .packages file.

```
W20150225-16:55:09.304(-8)? (STDERR) 
W20150225-16:55:09.304(-8)? (STDERR) /Users/aeubank/.meteor/packages/meteor-tool/.1.0.41.1gmbcof++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150225-16:55:09.304(-8)? (STDERR) 						throw(ex);
W20150225-16:55:09.304(-8)? (STDERR) 						      ^
W20150225-16:55:09.305(-8)? (STDERR) ReferenceError: Jasmine is not defined
W20150225-16:55:09.305(-8)? (STDERR)     at Jasmine.onTest.jasmine.addMatchers.toBePlaying.compare.player (packages/velocity:test-proxy/tests/jasmine/server/integration/sample/spec/PlayerSpec.coffee:1:1)
W20150225-16:55:09.305(-8)? (STDERR)     at packages/velocity:test-proxy/tests/jasmine/server/integration/sample/spec/PlayerSpec.coffee:1:1
W20150225-16:55:09.305(-8)? (STDERR)     at /Users/aeubank/Downloads/leaderboard-jasmine/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:164:3
W20150225-16:55:09.305(-8)? (STDERR)     at /Users/aeubank/Downloads/leaderboard-jasmine/.meteor/local/build/programs/server/boot.js:205:10
W20150225-16:55:09.305(-8)? (STDERR)     at Array.forEach (native)
W20150225-16:55:09.305(-8)? (STDERR)     at Function._.each._.forEach (/Users/aeubank/.meteor/packages/meteor-tool/.1.0.41.1gmbcof++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150225-16:55:09.305(-8)? (STDERR)     at /Users/aeubank/Downloads/leaderboard-jasmine/.meteor/local/build/programs/server/boot.js:116:5
```

The strange part is if `sanjo:jasmine` is included before `xolvio:cucumber` or the `xolvio:cucumber` is removed, the server starts up as normal. Any ideas?

**Comment by samhatoum** [comment]
I think so actually.

I recently added Chai and Chai as promised, they may be messing with things.

I'm rewriting meteor-cucumber this week as there are some fundamentally wrong things with it. I'll be sure to look at this case also

**Comment by samhatoum** [comment]
the rewrite is still in progress, just thought I'd update you

**Comment by samhatoum** [comment]
Can you please try with `meteor add xolvio:cucumber@0.6.0-rc.7` please? Please be sure to see the [breaking changes](https://github.com/xolvio/meteor-cucumber#breaking-changes) section.

**Comment by adeubank** [comment]
I ran into other issues with velocity and jasmine. The jasmine server integration test that I rewrote in Coffescript is not running at this time. 

These are the versions I used to at least get the meteor server started with cucumber. The cucumber sample tests work as expected.

From the `.meteor/packages` file
``` 
standard-app-packages
autopublish
insecure
mrt:moment@2.8.1
sanjo:jasmine@0.13.0-rc.4
velocity:html-reporter
xolvio:cucumber@0.6.0-rc.7
```

Velocity version from `.meteor/versions`
```
velocity:chokidar@0.12.6_1
velocity:core@0.6.0-rc.5
velocity:html-reporter@0.5.0
velocity:meteor-internals@1.1.0_5
velocity:meteor-stubs@1.0.3
velocity:shim@0.1.0
```
I'll try it again when I have more time to see what's going on with my leaderboard example.

**Comment by samhatoum** [comment]
Awesome. Would you mind tracking this in the Jasmine repo? Sanjo is more likely to respond there :)
