### ISSUE TITLE
Second assertion throws as error

### ISSUE THREAD

**Issue by wackazong** [xolvio/meteor-cucumber#54]
For an assertion like here 

```
      helper.world.browser.
          waitForExist('input[name="' + property + '"]').
          isExisting('input[name="' + property + '"]', function (err, result) {
            assert.equal(result, show, 'expected ' + property + ' existing to be ' + show)
          }).
          call(callback);
```

If the assertion fails for the second time, it throws as an error and the Meteor server is restarted.

**Comment by wackazong** [comment]
This has virtually disappeared with https://github.com/xolvio/meteor-cucumber/commit/8b2a2da89f14e2cd581b2c19158aa0c32777fd59

**Comment by samhatoum** [comment]
Great to hear, though I'm still having some infinite error loop issues. Most likely due to error bubbling in the child_processes.
