### ISSUE TITLE
Need a way to run a single scenario

### ISSUE THREAD

**Issue by samhatoum** [xolvio/meteor-cucumber#55]
Without having to comment out everything

**Comment by hexsprite** [comment]
How about a @solo tag (as in solo/mute in audio software) ?

**Comment by samhatoum** [comment]
I've been using this pattern nicely. I would like a way for meteor-cucumber to detect this and set the tag automagically.

**Comment by samhatoum** [comment]
no longer needed with the new @dev tag by default
