### ISSUE TITLE
meteor restarts on test failure

### ISSUE THREAD

**Issue by hexsprite** [xolvio/meteor-cucumber#56]
It's exiting with the following error causing meteor restart

```
W20150302-18:18:01.349(-8)? (STDERR) 
W20150302-18:18:01.349(-8)? (STDERR) node.js:463
W20150302-18:18:01.349(-8)? (STDERR)             callback();
W20150302-18:18:01.350(-8)? (STDERR)             ^
W20150302-18:18:01.351(-8)? (STDERR) TypeError: undefined is not a function
W20150302-18:18:01.351(-8)? (STDERR)   at process._tickDomainCallback (node.js:463:13)
W20150302-18:18:01.351(-8)? (STDERR) 
=> Exited with code: 8
=> Meteor server restarted
```

I manually audited things and can't find missing callback.  How can I debug this?  The error message is pretty obscure.

**Comment by samhatoum** [comment]
hmm, looks like the context in `this` has disappeared. Scope issue? Some rogue curly brace somewhere perhaps?

**Comment by hexsprite** [comment]
Yeah not really sure how to go about debugging that?  I'll start with reviewing my git commits and trying to see where it went south.

**Comment by hexsprite** [comment]
As a user of the framework I would like to see a better error message that helps me debug something like this more easily....

**Comment by samhatoum** [comment]
you and me both :)

This might shed some light:

https://github.com/cucumber/cucumber-js/issues/269

I'll see how I can hook into those stack traces a little more

**Comment by hexsprite** [comment]
Fair enough.  I have been able to isolate it to a particular steps file.   I am deleting step definitions one by one until I find the offender ;)

**Comment by hexsprite** [comment]
Ok I found the problem:

```
  @When /^I set the timer to "[\d:]*"$/, (duration, callback) ->
    helper.world.browser.setValue('.timer-duration', duration).call(callback)
```

Was missing the () around the argument so the callback was undefined I guess.

This issue should address how to make this easier to debug.  Perhaps provide a call wrapper that detects undefined or incorrect callback parameters?

**Comment by samhatoum** [comment]
I'm not really sure how to do that yet. Once things go into `tick` land, I start to get lost. Perhaps I should take a course in low-level node :)

**Comment by samhatoum** [comment]
This is incredibly annoying, and I'm going to fix it!!

**Comment by samhatoum** [comment]
the rewrite is still in progress, just thought I'd update you

**Comment by samhatoum** [comment]
Can you please try with `meteor add xolvio:cucumber@0.6.0-rc.7` please? Please be sure to see the [breaking changes](https://github.com/xolvio/meteor-cucumber#breaking-changes) section.

**Comment by samhatoum** [comment]
Fixed!
