### ISSUE TITLE
(ECONNREFUSED:-1) Couldn't connect to selenium server on some tests

### ISSUE THREAD

**Issue by djhi** [xolvio/meteor-cucumber#58]
I'm getting this error a lot since today, haven't been updating the xolvio or velocity package.
What's strange is that it only occurs on somes tests, randomly.

You will probably notice a path to node version 0.12.0 installed with nvm but its not. I made sure by running `nvm uninstall 0.12.0` and `nvm alias default 0.10.33`. Anyway it shouldn't be a prb as Meteor use its own packaged node.
 
I ran the tests with VELOCITY_DEBUG flag. The output is [here](https://www.dropbox.com/s/cot2gmy781j1ca4/log.txt?dl=0)

My packages:

```
meteor-platform
coffeescript
less
reactive-var
reactive-dict
email

practicalmeteor:chai
practicalmeteor:sinon
xolvio:webdriver@0.5.2
xolvio:cucumber@0.5.3
xolvio:inbox-stub

mquandalle:jade

meteorhacks:flow-router
meteorhacks:flow-components
meteorhacks:flow-layout
meteorhacks:subs-manager
meteorhacks:fast-render

tmeasday:publish-counts

amplify
anti:i18n
tap:i18n
tap:i18n-ui

fortawesome:fontawesome@4.2.0
#materialize:materialize
gildaspk:autoform-materialize

wizonesolutions:underscore-string
raix:handlebar-helpers@0.2.4

numeral:numeral
momentjs:moment
lbee:moment-helpers

gildaspk:moment-languages@2.9.0
gildaspk:numeral-languages@1.5.4
gildaspk:simpleschema-tapi18n-labels@0.0.1

dburles:collection-helpers
aldeed:simple-schema@1.3.1
aldeed:collection2@2.3.2
aldeed:autoform@5.0.2
aldeed:template-extension
cfs:standard-packages
cfs:gridfs
cfs:ejson-file
cfs:ui
gildaspk:autoform-file-materialize
gildaspk:autoform-medium

service-configuration
accounts-ui
accounts-password
accounts-google
accounts-facebook
accounts-twitter
bozhao:accounts-instagram
mikael:accounts-merge
mondora:connect-with

joshowens:shareit

bengott:avatar
datariot:ganalytics
yogiben:pretty-email@0.0.4
3stack:match-library

digilord:faker
```

Let me know if you need more infos

**Comment by samhatoum** [comment]
Hey, I can't see dropbox files (I don't use it!) Could you please post to a Gist or similar?

Also, regarding the error, can you try to run with chromeDriver instead of ghostDriver and see if that helps? You'll need to modify your world.js file. [See here](https://github.com/xolvio/meteor-webdriver#usage)

**Comment by djhi** [comment]
Using chromedriver now, tests running again. 
Made it work on CodeShip using the trick:
```
node /home/gildas/.meteor/packages/xolvio_webdriver/.0.5.2.1c9pccx++os+web.browser+web.cordova/npm/node_modules/chromedriver/install.js
```

:)

**Comment by samhatoum** [comment]
chromedriver worked on codeship?! I though those servers were headless

**Comment by djhi** [comment]
I confirm, it works very well

Le lun. 16 mars 2015 à 14:29, Sam Hatoum <notifications@github.com> a
écrit :

**Comment by djhi** [comment]
I'd very much like to make the webdriver version work in order to use it on Nitrous Pro.

I tried again with `getGhostDriver` and had the same problem. 

[Here](https://gist.github.com/djhi/2db1ca4698c4a196eb0b.js) is a gist with the logs.

Let me know if you need more

**Comment by samhatoum** [comment]
If it works with chromeDriver and not ghostDriver, I suspect it's due to something in your app that is not compatible with Phantom. 

I currently do [some poly-filling](https://github.com/xolvio/meteor-webdriver/blob/master/polyfills/url.js). I suspect if you look at the exact errors in phantom you might find you need some polyfills.

You can always try with phantom2.0 too :)

**Comment by djhi** [comment]
I've been able to run my tests with ghostDriver by using selenium-standalone and `getGhostDriverRemote`

**Comment by djhi** [comment]
> chromedriver worked on codeship?! I though those servers were headless

For reference:
https://codeship.com/documentation/continuous-integration/browser-testing/

**Comment by samhatoum** [comment]
can you please try again with 0.5.4?

**Comment by samhatoum** [comment]
This should no longer be an issue with 0.6.0. Please reopen if it is
