### ISSUE TITLE
Cucumber runs in non-cucumber mirrors

### ISSUE THREAD

**Issue by samhatoum** [xolvio/meteor-cucumber#69]
I can see cucumber running inside the jasmine mirror

**Comment by Sanjo** [comment]
You need to check `process.env.FRAMEWORK === 'cucumber` instead of `process.env.IS_MIRROR`.

**Comment by samhatoum** [comment]
That'll work.

From an architecture point of view, would be awesome if a mirror can have it's own packages file. This will create the cleanest isolation.

**Comment by Sanjo** [comment]
What would be doable is that you have a separate package for the mirror (like the test driver for test-packages). But that's not very practical I think.

The next for me is the inversion of control. You can tell velocity:core that a code block should run in the cucumber mirror and velocity:core will execute it for you in the correct mirror. The check would be the same, just in velocity:core.

**Comment by samhatoum** [comment]
fixed in rc7
