### ISSUE TITLE
unknown server-side error "POST /session//timeouts/async_script" when using Firefox

### ISSUE THREAD

**Issue by martinhbramwell** [xolvio/meteor-cucumber#72]
Trying to use Firefox I get this error : 

      Scenario: Author using the Meteor settings file           # features/author_a_website.feature:7
        Before 
          RuntimeError: RuntimeError
               (UnknownError:13) An unknown server-side error occurred while processing the command.
               Problem: POST /session//timeouts/async_script
          Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
          System info: host: 'velocuke', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-49-generic', java.version: '1.7.0_75'
          Driver info: driver.version: unknown

               Callstack:
               -> timeoutsAsyncScript(10000)

The command used is 

    SELENIUM_BROWSER=firefox meteor

I begin with a more or less virgin installation of Xubuntu in a KVM virtual machine with 2 CPUs,  2048 of memory and 12Gb disk with 3.5Gb free space.

	yourself@velocuke:~$ lsb_release -a
	No LSB modules are available.
	Distributor ID:	Ubuntu
	Description:	Ubuntu 14.04.2 LTS
	Release:	14.04
	Codename:	trusty

I run all the *apt-get* updates and then install the default jre : 

	yourself@velocuke:~$ java -version
	java version "1.7.0_75"
	OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
	OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

Then install Meteor : `curl https://install.meteor.com/ | sh`, clone Meteor Cucumber and test it without firefox : 

        yourself@velocuke:~/projects/meteor-cucumber/test-app$ meteor
        [[[[[ ~/projects/meteor-cucumber/test-app ]]]]]                                    

        => Started proxy.                             
                                                      
        => Meteor 1.1.0.1: fixes a client-side Blaze crash regression in 1.1.

        This release is being downloaded in the background. Update your app to
        Meteor 1.1.0.1 by running 'meteor update'.
                                                      
        => Started MongoDB.                           
        xolvio:cucumber: updating npm dependencies -- cuke-monkey, colors, fs-extra...
        => Started your app.                          

        => App running at: http://localhost:3000/
        I20150413-07:41:16.304(-4)? [velocity] cucumber is starting a mirror at http://localhost:44045/.
        I20150413-07:41:16.306(-4)? [velocity] This takes a few minutes the first time.
        I20150413-07:41:16.308(-4)? [velocity] You can see the mirror logs at: tail -f /home/yourself/projects/meteor-cucumber/test-app/.meteor/local/log/cucumber.log

Running with firefox looks like this . . .

        yourself@velocuke:~/projects/meteor-cucumber/test-app$ SELENIUM_BROWSER=firefox meteor
        [[[[[ ~/projects/meteor-cucumber/test-app ]]]]]

        => Started proxy.                             
                                                      
        => Meteor 1.1.0.2: fixes a client-side Blaze crash regression in 1.1.

        This release is being downloaded in the background. Update your app to
        Meteor 1.1.0.1 by running 'meteor update'.
                                                      
        => Started MongoDB.                           
        => Started your app.                          

        => App running at: http://localhost:3000/
        I20150413-07:54:06.770(-4)? [velocity] cucumber is starting a mirror at http://localhost:34187/.
        I20150413-07:54:06.773(-4)? [velocity] You can see the mirror logs at: tail -f /home/yourself/projects/meteor-cucumber/test-app/.meteor/local/log/cucumber.log

. . . and the log file looks this : 

            yourself@velocuke:~/projects/meteor-cucumber/test-app$ cat .meteor/local/log/cucumber.log
            Spawn script arguments:
            parentPid: 8766
            command: meteor
            commandArguments: [ 'run',
              '--test-app',
              '--port',
              '34187',
              '--include-tests',
              'cucumber/fixtures',
              '--settings',
              '/tmp/tmp-8853JjJ8CuRgfCzt.tmp',
              '--raw-logs',
              '--release',
              'velocity:METEOR@1.1.0.2' ]
            pid: 8877
            child.pid: 8879
            => Using velocity:METEOR@1.1.0.2 as requested (overriding Meteor 1.1)

            [[[[[ ~/projects/meteor-cucumber/test-app ]]]]]

            => Started proxy.
            [sanjo:long-running-child-process]: Exposing imports for testing purposes
            [velocity] Starting mirror on port 34187
            => Started your app.

            => App running at: http://localhost:34187/
            [xolvio:cucumber] Cucumber is running
            [velocity] Established connection with Velocity.
            Downloading Selenium 2.44.0
            From: http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
            ..............................................
            Starting Selenium 2.44.0 on port 34466
            Filename: /home/yourself/projects/meteor-cucumber/.npm/package/node_modules/cuke-monkey/node_modules/selenium-launcher/lib/selenium-server-standalone-2.44.0.jar

            Feature: Author a Website

              As a web page author
              I want to set the heading of my page
              So that I can create the simplest website in the world

              Scenario: Author using the Meteor settings file           # features/author_a_website.feature:7
                Before 
                  RuntimeError: RuntimeError
                       (UnknownError:13) An unknown server-side error occurred while processing the command.
                       Problem: POST /session//timeouts/async_script
                  Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
                  System info: host: 'velocuke', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-49-generic', java.version: '1.7.0_75'
                  Driver info: driver.version: unknown

                       Callstack:
                       -> timeoutsAsyncScript(10000)

                Given I have authored the site title as "My Test Title" # features/author_a_website.feature:8
                When I navigate to "/"                                  # features/author_a_website.feature:9
                Then I should see the heading "My Test Title"           # features/author_a_website.feature:10

            (::) failed steps (::)

            RuntimeError: RuntimeError
                 (UnknownError:13) An unknown server-side error occurred while processing the command.
                 Problem: POST /session//timeouts/async_script
            Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
            System info: host: 'velocuke', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-49-generic', java.version: '1.7.0_75'
            Driver info: driver.version: unknown

                 Callstack:
                 -> timeoutsAsyncScript(10000)

            Failing scenarios:
            /tests/cucumber/features/author_a_website.feature:7 # Scenario: Author using the Meteor settings file

            1 scenario (1 failed)
            4 steps (1 failed, 3 skipped)

Note that Firefox **does** start, but nothing appears in the window.  After a minute or two it closes, and *ps aux* no longer shows any Firefox processes.

**Comment by samhatoum** [comment]
Amazing log report :)

I'm unable to replicate this on a mac. I will try on a KVM but I want to sure the latest changes haven't already fixed this issue. Could you try one more time please?

**Comment by martinhbramwell** [comment]
I am on it.  Please note that your README still refers to : 

    Installation : 

        meteor add xolvio:cucumber@0.6.0-rc.8

**Comment by samhatoum** [comment]
sorry I fired that early. 0.6.0 is out. check now please

**Comment by martinhbramwell** [comment]
Done.

Sorry to say -- no apparent change except to versions  (eg "Using velocity:METEOR@1.1.0.2_1 as requested (overriding Meteor 1.1.0.2)")

**Comment by samhatoum** [comment]
Bummer. I'll get to this bug soon

**Comment by samhatoum** [comment]
ok, yet another version to try! 0.7.0 has just been released. Could you try again?

If not, I'd be happy to jump on a hangout with you to sort it

**Comment by samhatoum** [comment]
Sorry it has taken so long to get back to you. I've made a lot of progress on multi is compatibility. Can you try again with 0.8.0 and delete your .meteor/local directory first please?

**Comment by djesuele** [comment]
Hey, so I'm still running into this problem trying to use Firefox in 0.8.3:

```
      RuntimeError: RuntimeError
           (UnknownError:13) An unknown server-side error occurred while processing the command.
           Problem: POST /session//timeouts/async_script
      Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
      System info: host: 'Shagohod', ip: '192.168.0.107', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.7.11-1-MANJARO', java.version: '1.7.0_79'
      Driver info: driver.version: unknown

           Callstack:
           -> timeoutsAsyncScript(10000)
```

**Comment by samhatoum** [comment]
The only thing I can see there is the double slash.

That OS are you on?

**Comment by djesuele** [comment]
I'm running Manjaro Linux. What double slash are you referring to? I guess I'm not really sure what the expected output is

**Comment by samhatoum** [comment]
I mean `POST /session//timeouts/async`. I'm not sure if that's normal behaviour. I'll check and come back to you

**Comment by samhatoum** [comment]
@martinhbramwell so I finally followed your steps, installed Xubuntu in a VM and tested meteor-cucumber. Works with Firefox!

The steps I took to test are:

* install Xubuntu 
* install meteor 
* clone meteor-cucumber
* cd to meteor-cucumber/test-app
* tried `SELENIUM_BROWSER=firefox meteor --test` works
* tried `SELENIUM_BROWSER=firefox meteor` works

What can I do to replicate this error @djesuele and @martinhbramwell ?

**Comment by martinhbramwell** [comment]
@Sam 

I have seen your past remarks on this, but I have been off exploring other aspects of Meteor, and reluctant to take the time to dig back into this problem.  I have had no need for Cucumber since this issue came up and now I am having a hard time remembering the scenario, which is why I do try to get the whole story into bug reports when I write them.

It seems to me that all I would do now is replicate my earlier steps the same way you have and reach the same point you have.  Did you follow the steps with recent versions, or with the extant versions at the time of the report?

Perhaps the issue could be suspended until others complain?

**Comment by samhatoum** [comment]
Thanks for letting me know @martinhbramwell , hope the meteor endeavor is going well. I think @djesuele is still having the issue so I'll follow up with him.

**Comment by martinhbramwell** [comment]
[Off Topic]    This is what I've been doing : https://forums.meteor.com/t/looking-for-courses-or-tutorials-that-build-a-full-application/4403/32  But, I am getting disheartened with my work on Meteoris by the lack of fellow contributors.  I'd be glad to see you weigh in on that discussion.  Do you think the reference model idea would gain any traction?  What would be your pick for the project to focus on?

**Comment by samhatoum** [comment]
I'm not personally a fan of generators at all. To me they are akin to a
glorified copy/paste when I think every problem should be addressed with
fresh eyes. But that's me :)

**Comment by martinhbramwell** [comment]
I agree with you in the case of end user pages on production apps.  However, for the purely administrative section in bespoke projects, and for initially prototyping data management requirements they can be useful time savers.

**Comment by samhatoum** [comment]
can't reproduce
