### ISSUE TITLE
@ignore does not work

### ISSUE THREAD

**Issue by vhmh2005** [xolvio/meteor-cucumber#74]
I added @ignore tag before a scenario but the test still run

**Comment by samhatoum** [comment]
try running Meteor with:

`CUCUMBER_TAGS='~@ignore' meteor`

Let me know if that works and it might be worth including by default

**Comment by vhmh2005** [comment]
that does not work. pls check

**Comment by samhatoum** [comment]
I can reproduce this now, it will be fixes in 0.7.0

**Comment by samhatoum** [comment]
this is now built in to 0.7.0, any @ignore will not run. Also, only @dev will run in watch mode now.

**Comment by vhmh2005** [comment]
great, @samhatoum
