### ISSUE TITLE
After running some tests, it fails to connect to selenium

### ISSUE THREAD

**Issue by djhi** [xolvio/meteor-cucumber#75]
After running something like 100 steps successfuly, all my other tests get a:
```
RuntimeError: RuntimeError
           (ECONNREFUSED:-1) Couldn't connect to selenium server
           Problem: Couldn't connect to selenium server
```

I get this error for a lot of steps after what, it finally stop processing (from what I can see in the logs, it just hangs).

This is probably a prb in `cuke-monkey`. I specified `phantomjs` as browser

**Comment by djhi** [comment]
When using my own selenium-standalone with headless chrome, I don't reproduce the 1st prb but I still get the second. After running a part of my tests, it finally hang and stop running the others.

I have something like 150 steps, maybe more. I'll try to give more details asap

**Comment by samhatoum** [comment]
I think I know what this issue is and my next fix will sorry it out. Currently cuke-monbey is trying to stay a new selenium server on the same port. The new release will stay a new server for each new run. This should be safer.

I'm just trying to tidy up process management and I'll release probably later today.

**Comment by djhi** [comment]
Great !

**Comment by samhatoum** [comment]
try with 0.6.5

**Comment by djhi** [comment]
It's worst when using phantomjs and letting velocity starts its own selenium. It now runs only the 1st test then fails to connect to selenium (same msg).

When using my own selenium standalone with xvfb, it runs fine.

**Comment by djhi** [comment]
Turns out the prb was with my custom commands for Meteor authentication. Everything work as expected using meteor-cucumber configured with defaults (so its phantomjs and no custom selenium).

Great work !
