### ISSUE TITLE
Improve error output

### ISSUE THREAD

**Issue by lorensr** [xolvio/meteor-cucumber#81]
The most common error I get is "A script did not complete before its timeout expired." 

![image](https://cloud.githubusercontent.com/assets/251288/7386166/911cc594-ee05-11e4-81f5-82bf4c0cad65.png)

It's not clear to a newcomer what that means. It makes me think there's some deep problem in the setup, when it just means that `waitForVisible` wasn't able to find `main.ptabs`. While I've figured out what it means and trained myself to look at the bottom of the callstack, it would be nice if:

1. A clearer message is given at top that includes the failing webdriver call.
2. That message is displayed in the web UI, so that for most errors I can just look at that instead of scrolling up in the log tail. Current message is: ![image](https://cloud.githubusercontent.com/assets/251288/7386262/6fd5dfa0-ee06-11e4-9551-a8e52037f6df.png)
3. Perhaps there are other error types in which the meat of the error isn't on the first line, and it would be nice to get the relevant line in the web UI

**Comment by samhatoum** [comment]
I agree this is a scary stack puke! I've already started on humanifying cucumber errors. I'll add webdriver errors to the mix too and make them a little more focused on the UI

**Comment by lorensr** [comment]
Haha, great to hear, thanks

**Comment by cwohlman** [comment]
Another error case that isn't handled well - malformed Gherkin Syntax. I recently typoed in my tests and was quite confused as to why my tests were running and running.

**Comment by samhatoum** [comment]
Fixed the first issue in the browser reporter - will be in 0.7.0. The console reporting is a little more tricky, I'll try to do that for both issues mentioned above

**Comment by jwjames** [comment]
Just want to add my own experience to the discussion:

```javascript
this.Then(/^I should be on the login page$/, function(callback) {
      this.browser.
        .waitForExist('.email', 1000)
        .waitForVisible('.email', 1000)
        .call(callback);
    });
```

I forgot to remove a second dot when I was writing the above test (after `this.browser`) and I had no visible error or warning. My tests would simply not run until I found and removed the dot (which took a good 10 minutes to pinpoint).

**Comment by lorensr** [comment]
I'm on `0.8.0`, and getting a `Element is not currently interactable and may not be manipulated` error. I didn't used to see it on previous versions of this pkg. I was able to fix the error by adding a couple `.waitForVisible`s, but the problem is that the error doesn't tell me which webdriver call in a long chain is the cause, so I have to do a commenting-out binary search to see at which call the error begins occurring. Would be nice to either print out the call, eg `.click '#datetime'` or the line number.

```
   When I login as a@b                                                  # features/parlay.feature:6
[cuke-monkey][hooks] browser error event - capturing screenshot
    When I create a parlay                                               # features/parlay.feature:7
      Element is not currently interactable and may not be manipulated
 ```

**Comment by samhatoum** [comment]
the last few versions have massively improved error logging
