### ISSUE TITLE
FR: screenshot on error

### ISSUE THREAD

**Issue by lorensr** [xolvio/meteor-cucumber#83]
With many errors, such as 

![image](https://cloud.githubusercontent.com/assets/251288/7443256/33017f0a-f0f2-11e4-94f0-c3a1c11572a0.png)

a screenshot of what the page looks like would be very helpful (as done by https://github.com/rjsmith/meteor-robotframework). Webdriver has a function for it:

http://webdriver.io/api/utility/saveScreenshot.html

so it's just a question of how to catch errors and where to save or display the image (robot includes it in a generated report html page).

**Comment by samhatoum** [comment]
:+1: this is easy. I'll add it in the next release

**Comment by lorensr** [comment]
Sweet :)

**Comment by samhatoum** [comment]
Delivered in 0.7.0. Screenshots now go into `/tests/cucumber/.screenshots`

**Comment by lorensr** [comment]
I shouldn't need to do anything to enable this, correct? I've updated to 0.7.2, caused a lot of failed tests, both running default phantom and `SELENIUM_BROWSER=chrome`. Don't see a `.screenshots` dir.

**Comment by samhatoum** [comment]
odd. could you please post the output from `VELOCITY_DEBUG=1 meteor` please?

**Comment by lorensr** [comment]
OMG apparently I'm destined to keep coming to you with faulty bug reports due to old cucumber versions. I erroneously assumed `meteor update` always does what it tells me it did :)

```
me$ a mlg                     
alias mlg='meteor list | grep'
me$ a mu
alias mu='meteor update'
me$ mlg cucumber
xolvio:cucumber                               0.6.6* CucumberJS for Velocity
me$ mu
This project is already at Meteor 1.1.0.2, the latest release.
                                              
Changes to your project's package version selections from updating package versions:
                                              
meteorhacks:kadira                upgraded from 2.20.2 to 2.20.3
sanjo:long-running-child-process  upgraded from 1.0.3 to 1.1.1
xolvio:cucumber                   upgraded from 0.6.6 to 0.7.4

me$ mlg cucumber
xolvio:cucumber                               0.6.6* CucumberJS for Velocity
```

**Comment by lorensr** [comment]
Upgrading somehow fixed my only broken test! Screenshots work great, thanks again for the feature. Atm it's a hidden feature – would be good to feature in readme or note its existence in error output.

**Comment by lorensr** [comment]
I'm also able to take out a lot of `.waitForVisible`s and `.pause`s, which is nice.

**Comment by seanfcarroll** [comment]
I'm on xolvio:cucumber@0.8.9, and I have created a .screenshots directory under /tests/cucumber/.screenshots 

Do I need to do anything special to enable the screenshots on a failed test?
