### ISSUE TITLE
Tests continue to run after package removed

### ISSUE THREAD

**Issue by lorensr** [xolvio/meteor-cucumber#85]
I wanted to turn off testing temporarily because it taxes my computer while I'm continuously saving during development. I tried #21, but the tests still run – should I open a FR for that in the velocity repo?

I then tried removing `xolvio:cucumber`, but the cucumber tests still run, which seems hard to believe, but I'm sure it's really happening :) Note that I still have `mike:mocha` and `velocity:console-reporter` included in the app.

**Comment by samhatoum** [comment]
You found the bug I told you about at the devshop!

Try to kill any rogue node/phantom/selenium processes 

I'm on the final bits of 0.7.0

**Comment by lorensr** [comment]
Haha, k. Not finding anything `ps -A | grep X`, but that's fine, will try again w/ 0.7. Should `VELOCITY=0 meteor` work normally?

**Comment by samhatoum** [comment]
Yes it should, try also CUCUMBER=0

It's really odd that it's still running then!

**Comment by lorensr** [comment]
Alright, after running `CUCUMBER=0 VELOCITY=0 meteor` once, then just running `meteor` doesn't start cucumber anymore :)

**Comment by samhatoum** [comment]
I can't seem to replicate the original error and I tried CUCUMBER=0 and VELOCITY=0 (independently) and both worked. Can you please try with 0.7.0
