### ISSUE TITLE
How would I login with Meteor.loginWithPassword?

### ISSUE THREAD

**Issue by ryanswapp** [xolvio/meteor-cucumber#86]
I have a method in my fixture file:

```
'loginSocial': function() {
      Meteor.loginWithPassword('peekin@chu.com', 'foodbars');
},
```

However, when I call it with ```this.ddp.callAsync('loginSocial', [])``` I get this error:

```
TypeError: Object #<Object> has no method 'loginWithPassword'
```

I assume the reason is because loginWithPassword is a client method and cucumber runs on the server. I've been reading the Meteor testing books which suggests that I add a command in the world.js file. However, with the breaking changes in the newest release I saw a comment from Sam in which he said that we should just remove the hooks.js and world.js files. I now have no idea where I should be adding a command so that I can login... Can you help me with this?

**Comment by ryanswapp** [comment]
Ok, I figured it out. You can login with the following code: 

```
this.browser.
                url(url.resolve(process.env.HOST)).
                executeAsync(function(done) {
                    Meteor.loginWithPassword('maddielee11@hotmail.com', 'foodbars', done);
                }).
                call(callback);
```

I provided more code for context, but the only relevant code is the ```executeAsync``` function. This is called within a ```this.Given``` block.

**Comment by samhatoum** [comment]
Thank you for taking the time to answer back here

**Comment by adamwong246** [comment]
This did not work for me

**Comment by adamwong246** [comment]
but this did work for me
````
  this.Given(/^I am a logged-in user$/, function (callback) {

      this.browser.
        url(url.resolve(process.env.ROOT_URL, '/')).
        executeAsync(function(done) {
          u = Meteor.loginWithPassword('eunice.user@example.com', 'password');
        }).
        call(callback);
    });
```

**Comment by ryanswapp** [comment]
@adamwong246 Yes, I assumed that wrapping my code in a "this.Given" block was implied. I'm sorry if it wasn't.

**Comment by adamwong246** [comment]
no, the difference (for me) was in the callback provided, or in my case NOT provided, to `Meteor.loginWithPassword`

**Comment by samhatoum** [comment]
@adamwong246 executeAsync required a callback. I can't see how your code works without timing out. There may be a false positive in your test somehow. Meteor.loginWithPassword is async and should be calling `done` as its callback.
