### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by rhyslbw** [xolvio/meteor-cucumber#91]
On Mac OS X I've just run meteor add xolvio:cucumber (0.8.0) in an existing project, and have this error. Right now after starting the app with debug mode I see this

    I20150512-21:55:58.949(10)? [velocity] File scan complete, now watching /tests
    I20150512-21:55:58.949(10)? [velocity] Triggering queued startup functions
    I20150512-21:55:58.949(10)? [velocity] File scan complete, now watching /tests
    I20150512-21:55:58.949(10)? [velocity] Triggering queued startup functions
    I20150512-21:56:00.707(10)? Kadira: successfully authenticated
    I20150512-21:56:21.021(10)? [velocity] Mirror registered. Handshaking with mirror...
    I20150512-21:56:21.036(10)? [velocity] Connected to mirror, setting state to ready { framework: 'cucumber',
    I20150512-21:56:21.036(10)?   port: '64520',
    I20150512-21:56:21.036(10)?   host: 'http://localhost:64520/' }
    I20150512-21:56:29.375(10)? [velocity] Mirror registered. Handshaking with mirror...
    I20150512-21:56:29.383(10)? [velocity] Connected to mirror, setting state to ready { framework: 'cucumber',
    I20150512-21:56:29.383(10)?   port: '64520',
    I20150512-21:56:29.383(10)?   host: 'http://localhost:64520/' }
    I20150512-21:56:37.772(10)? [velocity] Mirror registered. Handshaking with mirror...
    I20150512-21:56:37.779(10)? [velocity] Connected to mirror, setting state to ready { framework: 'cucumber',
    I20150512-21:56:37.779(10)?   port: '64520',
    I20150512-21:56:37.779(10)?   host: 'http://localhost:64520/' }

... and in the mirror logs I'm getting:
    
    [sanjo:long-running-child-process]: Exposing imports for testing purposes
    [velocity] Mirror detected - Not adding velocity core
    [velocity] Not adding mirror-registry because NODE_ENV is development  and IS_MIRROR is true
    [velocity] Starting mirror on port 64520
    [xolvio:cucumber] Mirror server is initializing
    [xolvio:cucumber] Starting the monkey
    [xolvio:cucumber] Screenshots dir is /Users/ ~redacted~ /app/tests/cucumber/.screenshots
    [xolvio:cucumber] Starting the monkey with  /Users/Rhys/.meteor/packages/xolvio_cucumber/.0.8.0.1sj1cjw++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/cuke-monkey/bin/cuke-monkey [ '/Users/Rhys/.meteor/packages/xolvio_cucumber/.0.8.0.1sj1cjw++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/cuke-monkey/bin/cuke-monkey',
    [xolvio:cucumber] Cuke-Monkey process forked with pid 94632
    [xolvio:cucumber] Connecting to hub
    [xolvio:cucumber] Connected to hub.
    => Meteor server restarted
    [velocity] Mirror started. Connecting via DDP to parent
    [velocity] Mirror connected to parent. Registering mirror...
    [velocity] Established connection with Velocity.
    Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
    => Exited with code: 7

A new app with the same setup works fine. Does anything stand out?

**Comment by samhatoum** [comment]
Can you try deleting the `.meteor/local` directory please, then run `meteor refresh && meteor update`

**Comment by rhyslbw** [comment]
Thanks Sam, that seems to have resolved the problem.

**Comment by samhatoum** [comment]
:+1:
