### ISSUE TITLE
ddp.call isn't working correctly in 0.8.0

### ISSUE THREAD

**Issue by nathanathan** [xolvio/meteor-cucumber#92]
I'm trying to update a project from cucumber 0.5.3 to 0.8.0. One of the problems I'm running into is that the ddp calls don't appear to work as described in the readme. Passing all the arguments in an array results in the array being passed into the method as a single argument rather than apply style behavior. The largest problem I am facing is that the return values of my fixture methods are not passed back in the ddp.call callback (although the callback is called).

**Comment by samhatoum** [comment]
Can you try to return `this.mirror.apply()` instead?

**Comment by samhatoum** [comment]
regarding the return value, it should be [returned in the promise](https://github.com/xolvio/node-ddp-client/blob/master/lib/ddp-client.js#L468). Can you show me some code perhaps?

**Comment by nathanathan** [comment]
Thanks, using apply, I was able to pass in an arguments array, and I was able to obtain the return value from the promise.

I suggest updating this section of the readme with the information you gave me:

```
Same goes for DDP, you now use this.ddp and be sure to put all params in an array, so instead of this.mirror.call('myMethod', param1, param2, callback) you need to use this.mirror.call('myMethod', [param1, param2], callback).
```

**Comment by samhatoum** [comment]
Awesome. Although this new change matches the Meteor api for DDP calls, it's a breaking change for users such as yourself so I'll be sure to update. Cheers

**Comment by samhatoum** [comment]
Docs updated. thanks
