### ISSUE TITLE
Run meteor --test (CI) with custom settings

### ISSUE THREAD

**Issue by DominikGuzei** [xolvio/meteor-cucumber#93]
Hey there!
I am currently writing my first feature with meteor-cucumber and tried out the sample tests. However it doesn't seem to work correctly when I have custom settings for my app (which I do).

So running `meteor --test --settings=my/app/settings.json` doesn't run all features but only the one with `@dev` tag on it.

Am I missing something or is this my first bug discovery? :wink:

**Comment by samhatoum** [comment]
Just tested it, you found a bug. Having the settings is OK, it's that the `VELOCITY_CI` env var is not being set by our fork of the mirror (I think). See here: 
https://github.com/meteor-velocity/meteor/issues/2


A workaround is this:
`VELOCITY_CI meteor --test --settings=my/app/settings.json`

Or you can also set your own tags ([see here](https://github.com/xolvio/meteor-cucumber/blob/master/src/mirror-server.js#L206))
`CUCUMBER_TAGS=~@dev meteor --test --settings=my/app/settings.json`
(this will run non @dev tagged scenarios)

**Comment by DominikGuzei** [comment]
Ok thanks!
I got it to work with `VELOCITY_CI=1 meteor --test --settings=private/configurations/development.json` (you forgot the `=1` part :wink)

**Comment by samhatoum** [comment]
need :coffee:

**Comment by samhatoum** [comment]
it seems that to get VELOCITY_CI built in, you need to run this way on CI:

```meteor --test --release velocity:METEOR@1.1.0.2_3```

This will use the Velocity fork of Meteor. There's a [PR for the MDG](https://github.com/meteor/meteor/pull/4353) that will eventually mean this step is not necessary

**Comment by shrop** [comment]
sub

**Comment by samhatoum** [comment]
Sup!

**Comment by samhatoum** [comment]
This issue was moved to xolvio/chimp#120
