### ISSUE TITLE
Confusing (wrong?) documentation about fixtures and mirror

### ISSUE THREAD

**Issue by DominikGuzei** [xolvio/meteor-cucumber#94]
Hey there,
I just discovered that one part of the fixtures documentation is not up-to-date:

```javascript
// /tests/cucumber/features/step_definitions/hooks.js
this.Before(function (event, callback) {
  global.mirror.call('reset', [], callback);
}
```
this doesn't work because `global.mirror` is undefined. It should be `this.mirror` :wink: 

This also brings me to my next question – how should we proceed with errors like these? Should I make an extra pull request or just update it if it is so simple. The problem I have, is that I can't be 100% sure if I am right because I am just starting

**Comment by samhatoum** [comment]
Hey Dominik. If it's this simple, just go ahead and update, I trust you! 

I just updated the docs to talk about `this.mirror.call` and `this.mirror.update` docs as I recently made them match the Meteor API. I also removed the reference to global.mirror. There's now a reference to the 'global.ddp' object in case a user wants to use it in a pre-world hook.

I just missed the `global.mirror` alias when creating the [global.ddp connection](https://github.com/xolvio/cuke-monkey/blob/develop/lib/cucumberjs/world.js#L19). Feel free to add that if you need it, or I can do it on the next update.

I want to rewrite the hooks/world code in a test-driven manner like the rest of cuke-monkey soon. It's a little mish-mashy righy now :/

**Comment by DominikGuzei** [comment]
Ok great! Thanks for the feedback :+1: 
The package is working really well so far!
Love how the ddp fixtures work, that's even cleaner than having a `meteor` hook inside the step definitions!  The webdriverIO api is also great, will continue with the basics before thinking about possible widget implementation :wink:

**Comment by samhatoum** [comment]
awesome, looking forward to it :)
