### ISSUE TITLE
Finding elements by their text

### ISSUE THREAD

**Issue by DominikGuzei** [xolvio/meteor-cucumber#95]
Hey ho,
I just figured that webdriverIO provides no simple API to find an element on the page via its text. For me that's pretty important as I want to be able to write feature like this:

```gherkin
Background:
    Given a verified user named "dominik"
    And I am logged in as "dominik"
    And I have a project "Website" with these swatches:
    | TITLE          |  COLOR  |
    | simple         | #ccc111 |
    | With spaces    | #eee333 |
    | special-chars  | #fff    |

  @dev
  Scenario: Accessing the sharing screen
    When I go to my projects
    And I select the "Website" project
    And I click on the project sharing button
    Then I should see the project sharing screen for "Website"
```

As you can see I just reference the project via its title "Website" and would like to find this project on screen even when there are (possibly) multiple projects in the list. Here is the xpath that works in this specific case:

`@browser.click('//*[contains(concat(" ", normalize-space(@class), " "), " label ") and text()="Website"]'`
this clicks the first `.label` element which has the text "Website". However this is not very pretty, and actually I would need an even more specific selector like `.project-list-item .label`

Do you know of any good solution to that problem?

**Comment by DominikGuzei** [comment]
Ah, I found a part of the answer in how pioneer.js handles that:
https://github.com/mojotech/pioneer/blob/master/docs/list.md

You basically select all relevant items first (e.g: `@browser.elements('.project-list-item .label')`) and then filter them by their text

**Comment by samhatoum** [comment]
This would definitely be nice, you can easily add it as a custom WebdriverIO command:

http://webdriver.io/guide/usage/customcommands.html

Perhaps the Widget framework can be done with a set of really nice WebdriverIO commands?

**Comment by DominikGuzei** [comment]
That looks great! Yeah, at least we could build many lower-level commands that can be used everywhere. Widgets are a bit different, they represent something on screen, like a form or a dropdown. So they are useful if you want to "do something" with a widget without having to think about the webdriverio api.

Think about a searchable dropdown like [chosen](http://harvesthq.github.io/chosen/), when you write a widget for it something like this should be possible:
```javascript
var dropdown = new ChosenDropdown();
dropdown.open().searchFor('USA').choose()
```
So its a real DSL for interacting with UI elements on screen (with context).

**Comment by samhatoum** [comment]
I see. chosen looks cool also. Can I close this issue?

**Comment by DominikGuzei** [comment]
For the sake of remembering, here is the complete solution for my case:
```coffeescript
@When /^I select the "([^"]*)" project$/, (projectTitle, done) ->
    @browser.elements '.project-list-item .label', (error, labels) =>
      labels.value.forEach (label) =>
        @browser.elementIdClick(label.ELEMENT).call done
```

found good hints here:
https://github.com/webdriverio/webdriverio/issues/273

**Comment by DominikGuzei** [comment]
no that's actually wrong … have to find the correct way to deal with it :wink:

**Comment by samhatoum** [comment]
keeping it open in case someone else can see and help

**Comment by DominikGuzei** [comment]
Thanks! Here is a first working solution, but it has some logical problems:
```coffeescript
@When /^I select the "([^"]*)" project$/, (projectTitle, done) ->
  @browser.elements('.project-list-item .label')
  .then (labels) => labels.value.forEach (label) =>
    @browser.elementIdText(label.ELEMENT).then (text) =>
      if text.value is projectTitle
        @browser.elementIdClick(label.ELEMENT).call done
```
one problem is, that it doesn't account for multiple projects with the same name. This would result in multiple clicks **and** multiple `.call(done)`.

What I would really need is to iterate over the labels, create a promise for each "check title + click" action and use something like [Promise.any()](https://github.com/petkaantonov/bluebird/blob/master/API.md#any---promise) to check if it was successful. Only then I would call `done`

**Comment by samhatoum** [comment]
This brings back memories for RTD and trying to something similar with the leaderboard player names. I think I ended doing exactly what you just said

https://github.com/xolvio/meteor-rtd-example-project/blob/master/test/acceptance/leaderboard.spec.js#L61
