### ISSUE TITLE
Widgets with higher-level promise based API

### ISSUE THREAD

**Issue by DominikGuzei** [xolvio/meteor-cucumber#98]
Hey there,
For solving my problems with clicking on the first element in a list that contains some specific text I have built a simple draft for a widgets library that provides a high-level contextual API for interacting with webdriverIO elements. This idea is borrowed from [Pioneer.js Widgets](https://github.com/mojotech/pioneer/blob/master/docs/widget.md)

Here is how I can use this in my step definition now:
```coffeescript
@When /^I select the "([^"]*)" project$/, (projectTitle, done) ->
  new @Widget.List('.project-list-item .label') # selector that potentially includes multiple elements
  .findByText projectTitle # act on the result-set of the selector above
  .then (widget) -> widget.click() # the first element with the searched text, wrapped as widget
  .then -> done()
```

Here is the first implementation, that is just included as cucumber support file atm:
```coffeescript
Promise = require "bluebird"
module.exports = ->
  @Before (callback) ->
    client = @client

    class Widget
      api: null
      element: null

      constructor: (@element, @api=client) ->

      hasText: (expectedText) ->
        new Promise (fulfill, reject) =>
          @api.elementIdText @element.ELEMENT, (error, text) =>
            if error?
              reject error
            else
              if text.value is expectedText then fulfill(this) else reject()

      click: -> Promise.promisify(@api.elementIdClick, @api)(@element.ELEMENT)

    class Widget.List
      api: null
      widgets: null

      constructor: (selector, @api=client) ->
        @widgets = new Promise (fulfill, reject) =>
          @api.elements selector, (error, elements) =>
            if error?
              reject error
            else
              fulfill @_wrapAsWidgets(elements)

      findByText: (text) ->
        @widgets.then (widgets) =>
          Promise.any widgets.map (widget) -> widget.hasText text

      _wrapAsWidgets: (elements) =>
        return elements.value.map (element) => new Widget element, @api

    # expose on step context
    @Widget = Widget
    callback()
```

For the promises I use the [Bluebird](https://github.com/petkaantonov/bluebird) npm package, because its awesome :wink:

**Comment by samhatoum** [comment]
We use bluebird in cuke-monkey also, it is awesome.

I like the direction this is heading in. This is going to be make testing a lot easier.

It seems this library is only dependent on the `client` from cuke-monkey. So if cuke-monkey can do all the starting of browsers and session reuse management, the monkey can construct the widget library after cuke-monkey has initialized the browser. 

I'm thinking perhaps we can make this a separate npm package that we use inside cuke-monkey. This will allow us to work on the widget library using coffee. If you like this idea, I can either create a repo on the Xolv.io github account or you can host it. I personally like my coffee strong and black in the morning, but @Sanjo on the other hand drinks whatever is on the table :)

What do you guys think?

**Comment by DominikGuzei** [comment]
Hey @samhatoum, glad you like it! :wink: 
I am totally fine with putting this into its own npm package that gets included by cuke-monkey.
It would be awesome if you could create a xolv.io repo and setup the basic connection with cuke-monkey, so that we can iterate on the widget lib together.

I also like my coffee strong and black, all day long :smile:
Loving all of this so far! Really great work, can't stress that enough!

**Comment by DominikGuzei** [comment]
This issue can be close as we created the [chimp-widgets](https://github.com/xolvio/chimp-widgets) package that will be included with the next version of [chimp](https://github.com/xolvio/chimp) (aka cuke-monkey).

chimp-widgets will be the ongoing effort to provide an easy to use high-level api to interact with "widgets" on the page.
