### ISSUE TITLE
Make screenshot on error optional 

### ISSUE THREAD

**Issue by samhatoum** [xolvio/meteor-cucumber#99]
These will be done in cuke-monkey and exposed in meteor-cucumber also

**Comment by samhatoum** [comment]
no longer happens by default locally

**Comment by Maxim-Filimonov** [comment]
@samhatoum So how to enable screenshot taking now? I can't find any docs for that

**Comment by adamwong246** [comment]
+1

**Comment by Sanjo** [comment]
The documentation is here: https://chimp.readme.io/docs/command-line-options. `--screenshotsOnError`. You set this options with `export CHIMP_OPTIONS=--screenshotsOnError=true`.
